### ISSUE TITLE
Disco

### ISSUE THREAD

**Issue by Zash** [siacs/Conversations#1033]
The solution to #170 is apparently not complete.  Conversations does not perform service discovery and caching based on caps.  This makes it for example attempt Jingle file transfers to clients that don't support it or implements a different version.

**Comment by tfar** [comment]
+1 for fixing this.

**Comment by noonien-d** [comment]
Did some work yesterday regarding this issue. Features are not verified and requested once a session.
The gui integration for filetransfer is only provisional and displays "(no support)" in the resource selection dialog.

https://github.com/noonien-d/Conversations/tree/feature/capabilities

**Comment by iNPUTmice** [comment]
@noonien-d Thank you for this. If you are interested in working on this you should open a PR so we can discuss further steps.
One thing we would definitely need would be some kind of persistent storage.

And just writing (no support) behind the presence isn't a solution because the presence selection dialog is also being used for OTR sessions. Maybe we should add a parameter to the selectPresence method that includes the namespace of the required feature and only return presences that offer this feature.
