### ISSUE TITLE
Feature request: List other clients et can disconnect them

### ISSUE THREAD

**Issue by BrokenVentilator** [siacs/Conversations#1140]
Some times, I leave my home and forget to disconnect my Jabber desktop app.
If, on the outside world, I want to become offline or go out of any network, my contacts continues to see me online and don't understand why I don't responding to their messages.

It would be helpful if I can see the list of other clients connected to my account and can disconnect them.
(Or a better way to solve this problem)

**Comment by jkufner** [comment]
As far as I know, XMPP does not offer mechanism to disconnect other clients. However, little trick with resource could do it. When second client connects with same resource as used by the first client, server will disconnect the first client. Conversations could connect with used resources and imediately disconnect, to let other clients drop their connections.

**Comment by iNPUTmice** [comment]
There is actually [XEP-0146](http://www.xmpp.org/extensions/xep-0146.htm) that could be used for this. But I don't know of any client implementing this.
The 'resource trick' on the other hand is a terrible hack since most or at least some clients will just reconnect.

I usually just ssh into my computer and kill the client if necessary. Or even better teach my friends that only because I'm logged in somewhere doesn't mean i have time for them.
Most (desktop) clients have an auto-away feature for excactly this reason though.

**Comment by TameOfGroans** [comment]
"Or even better teach my friends that only because I'm logged in somewhere doesn't mean i have time for them."

Right up there with teaching about priority & resources. Second only to insisting on language to terminate chats, "bye", instead of socially 'acceptable' silence.
