### ISSUE TITLE
Simplify function for sending position

### ISSUE THREAD

**Issue by karlkarpfen** [siacs/Conversations#1142]
The function to send current position is quite a cool feature but too complicated. I like to use it while driving by car to tell somebody where I am, and there it should be as simple as possible. Currently ohne has to 1. select the menu, 2. select the item "Send Position", 3. look what position was found, 4. allow to send this position (but only when it is a good position).

How about: 1. select the menu, 2. select the item "Send Position" -> now Conversations waits until a valid position with an acceptable GPS-deviation is evaluated and sends it without further questions.

**Comment by Rupersia** [comment]
It would be even better on a single button click.

**Comment by TameOfGroans** [comment]
"while driving"

Is share location the best for that case? Would you not be better served by Glympse, another app? 

http://m.aptoide.com/searchview.php?search=glympse

**Comment by iNPUTmice** [comment]
Please don't use Conversations while driving. You are not only endangering your own life but the lives of others.
1.4.0 implements so called quick actions that can replace the send button with a location button. This should save you the trouble of going through the menu.
However the Share Location Activity has to wait for user input otherwise the App would undermine the permission security model of Android. (Imagine every random app could start ShareLocation and automatically get an answer)
