### ISSUE TITLE
Parse &quot; &gt; and other tags

### ISSUE THREAD

**Issue by sedrubal** [siacs/Conversations#1166]
Pidgin often sends things like this and it would be nice, if conversations parses this to `"` and `>` and so on

**Comment by iNPUTmice** [comment]
is this for OTR messages? If thats the case search the bug tracker for HTML
OTR and pidign

**Comment by sedrubal** [comment]
yes, it's OTR.

I searchd and found: #1116 -> dublicate of #23 (but this and #894 only concerns Adium and is closed, because Adium doesn't send html anymore)

**Comment by iNPUTmice** [comment]
There is no reason for pidgin to to this. On our end there is nothing we can do about this because it would be impossible for us to differentiate between ```&quot;``` and ```"```. Meaning if we were to parse ```&quot;``` to ```"``` people would be unable type ```&quot;```.
Please report this problem to the developer of the OTR plugin for Pidign. The pidgin developers keep marking any issues related to this as invalid because it is a plugin problem.

**Comment by sedrubal** [comment]
OK

But you could catch only this cases: `<space>&quot;word word&quot;<space>`

So there will be only one person in ten years, which wants to see this unparsed but there will be many people writing with someone using pidgin+otr.

But I can understand that you don't want to implement workarounds for other programs pseudo standards...

**Comment by Natureshadow** [comment]
Breaking HTML entity encapsulation is a common mistake in OTR implementations. So far, I ahve seen Conversations do it right, so I can sign there is nothing to change here.

Also, do not use XHTML-IM.

**Comment by herbsmn** [comment]
Hey @iNPUTmice or anyone else reading this, can you help the pidgin-otr people with this bug at all? https://bugs.otr.im/issues/85 

I understand if no one can contribute to help them out, but they seem interested in figuring out a solution to this 7 year old bug. https://developer.pidgin.im/ticket/8453 

I use pidgin on my desktop and conversations on my phone and would love to see this issue resolved.

**Comment by iNPUTmice** [comment]
> I understand if no one can contribute to help them out, but they seem interested in figuring out a solution to this 7 year old bug

Yes the OTR spec allows to encrypt HTML. However in a case where a protocol can transport both there is no way for a receiving client to distinguish the two. Thus [Section 4.1 of XEP-0364](http://xmpp.org/extensions/xep-0364.html#sect-idp733712) specifies that receiving entities should treat incoming text as plain text.

The way for pidgins OTR plugin to fix is to take the plain text message as input for the crypto and not the HTML message.


> I use pidgin on my desktop and conversations on my phone and would love to see this issue resolved. 

Don't use Pidgin. Pidgin is not an XMPP client. OTR is 10 years old and was never designed for modern day instant messaging. Use OMEMO with Gajim instead.

**Comment by herbsmn** [comment]
I use Tails, which uses Pidgin. I'll try to install gajim soon because I want to check it out. I just added some stuff to Gajim's group chat ticket. If you want to add to it and tell them more details on how to impliment OMEMO encryption for group / conference chat here's the link: https://trac.gajim.org/ticket/8154

The pidgin-otr folks said "So instead of their OTR plugin using convert_msg to strip the HTML, they suggest that no one be able to receive markup? That seems suboptimal." https://bugs.otr.im/issues/85

Thoughts?

**Comment by strb** [comment]
Well we've already explained in this ticket why this doesn't work. You *can't* simply "stsip the HTML" because you don't know whether it's HTML introduced by the peer's client, or whether they were just trying to explain to me something like `In HTML if you want a < sign you have to write &lt;`. What they are asking for is literally impossible, so clearly its not the solution. This is why the XEP explicitly specifies how this scenario is to be handled.

I understand that they don't want to break [features that their users may have gotten used to](https://xkcd.com/1172/), but there is absolutely nothing we can do here. Putting HTML into the body in the XMPP world is a hack, plain and simple.
