### ISSUE TITLE
"Send a picture" as another option for the quick action button

### ISSUE THREAD

**Issue by moshpirit** [siacs/Conversations#1221]
In Conversations 1.4.0 it was launched the "quick action" button, but it only includes the send of "audio", "photo" or "ubication", not any other picture, which I, personally, mostly use. Since it's very configurable, I think it could be another option to include.

**Comment by kriztan** [comment]
perhaps this could be extended by a dialog to chose whether to take a photo or chose from gallery

**Comment by moshpirit** [comment]
Then, it wouldn't be a "quick" action anymore :\

**Comment by TameOfGroans** [comment]
I too would like send photo an option in settings for quick action

**Comment by sesceu** [comment]
why wouldn't it be a "quick" action anymore? isn't the quick referring to I can send the stuff quicker than going through the menu?
I did wonder, why there are all send * functions available as quick actions except for sending an existing image, which is the action I am using most.

**Comment by moshpirit** [comment]
It wouldn't be a "quick" action if it would have a dialog, that's what I meant.

**Comment by sesceu** [comment]
I see, but you don't get a dialog for the other options, like "take picture", "record" or "share location"?

**Comment by moshpirit** [comment]
No, I don't, I only get a dialog when I send a picture because I have two different apps for that (the gallery and  the file manager) and I can't select the gallery as the default.  

I don't have the location plugin because I think I remember that it's only in the play store and for the audio I use the audio recorder plugin for Chatsecure as default.

**Comment by sesceu** [comment]
Oh, you meant the android share dialog that shows all available apps for that action. But, correct me if I'm wrong, but this depends on the apps you have installes, meaning: if you had two apps for voice recording you'd also see the dialog unless you choose one app to be the default. So, this is nothing that Conversations could influence, because it depends on the apps that are installed on your device. An honestly, I can live with this dialog, I actually like it, because I use different applications for different types of contents, like web browsers...
Anyway, in my optionion the quick button should be able to send everything, that you could send via the menu, but that's just my opinion.

**Comment by moshpirit** [comment]
Yes, but this is not the issue :-) the issue is for adding "send picture" as another quick action, that's all.

**Comment by sesceu** [comment]
ok, just to be clear. This is the list you can sent via menu vs. the stuff you can sent as quick action:

action | via menu | via quick action
------------ | ------------- | ------------
send location | :white_check_mark:  | :white_check_mark: 
record | :white_check_mark: | :white_check_mark: 
take picture | :white_check_mark: | :white_check_mark: 
send picture | :white_check_mark: | :x: 
send file | :white_check_mark: | :x: 

Your ticket is just about the send picture part, right?

**Comment by moshpirit** [comment]
Exactly :-)
