### ISSUE TITLE
disable vibration/notification sound when CC is enabled and chatting from other resource

### ISSUE THREAD

**Issue by pythonimus** [siacs/Conversations#1222]
Hi,

I have my smartphone in my pocket and chatting through pidgin with my contacts on a CC enabled server.
On every message received my phone will vibrate/play notification sound/push message.
It would be nice if Conversations recognizes that I'm chatting from another resource and don't need notifications on new messages.

**Comment by strb** [comment]
There is no definitive way to detect "chatting from another ressource" with xmpp. Currently, after receiving a carboned outgoing message from another one of your resources, Conversations will disable notifications for a grace period of (IIRC) 90 seconds. 

This is obviously a heuristic that will not always work perfectly, but we have to strike a balance between not notifying while you're at another resource, but also starting to notify you again after you have stopped chatting from that other resource. 

If you have any more concrete suggestions or ideas on what "chatting from another ressource" actually means and how it could be detected, we would love to hear about it, though.

**Comment by strb** [comment]
Just checked the source. It's actually set to 60 seconds. Maybe we could think about increasing this a little bit... Is anybody else experiencing this problem in a significant way?

**Comment by sezuan** [comment]
I found that pretty annoying, too. I've disabled all notifications and switched back to polling ;)

**Comment by deoren** [comment]
I personally am happy with the behavior, so if the behavior is changed it would be great if it were an option that could be togged of/off.

**Comment by RalfJung** [comment]
I can't say I'm happy with the current behavior. I have to unlock my phone several times a day to remove notifications that conversations put there, because it doesn't notice that I am actually chatting elsewhere. Together with OTR messages ending up at the wrong client, this must be the most frustrating part of my "multi-client jabber experience".

Now, I do realize that conversation can't even know I am chatting elsewhere currently, so this probably asks for some extension of XMPP. For example, what is the technology that conversation uses to tell me which messages have already been read by my peer? Couldn't it use the same kind of notification to learn that *I* have read a particular message at another client? If clients tell the server anyway that I just read a particular message, then this may just as well get forwarded to not only my peer, but also all the other clients I am logged in with.
Of course, this assumes clients do this properly and actually test for window focus or things. I just imagine the notification on my phone to disappear the moment I switch the chat tab on my laptop... that'd be amazing :D
Is this a kind of bug/proposal you'd like to track in a separate bug?
