### ISSUE TITLE
Feature: Send file as quick action

### ISSUE THREAD

**Issue by sesceu** [siacs/Conversations#1227]
The quick action button is awesome, but it doesn't allow for all types of chat attachments:

action | via menu | via quick action | ticket
------------ | ------------- | ------------ | ------------
send location | :white_check_mark:  | :white_check_mark: | ---
record | :white_check_mark: | :white_check_mark: | ---
take picture | :white_check_mark: | :white_check_mark: | ---
send picture | :white_check_mark: | :x: | #1221 
send file | :white_check_mark: | :x: | this

As you can see, the "send picture" part is already addressed in #1221, so this request is about the send file. Honestly, the send picture for me is more important, but I can imagine, that while at it, it might be actually pretty simple to do together.

**Comment by iNPUTmice** [comment]
The quick action was originally meant to make it easier to **create** content. (record voice, take picture, 'create' location)

Choose picture doesn't really fit the profile there. But I added it since this is arguably the most commonly used feature. send file however is a different story. The usage of send file is actually discouraged. I don't want users to select send file once by accident and then use send file over and over again just because there is a quick action for it. Plus if you have it in most recently used mode and you do need send file once the chances are high that you don't need it again so there is no point in putting the quick action button into that mode
