### ISSUE TITLE
Chat sync indicator

### ISSUE THREAD

**Issue by jkufner** [siacs/Conversations#1232]
When phone sleeps or is offline for a while, there may be a lot of chat history stored on server which is not available in device. And it may take a while to fetch the chat history from server.

There should be some decent indicator, that history is beeing downloaded. It should also show whether or not is Conversations connected to server at all. Otherwise user cannot know whether there are no new messages or they are not downloaded yet. This is a big issue when signal is weak and connection is unstable.

I guess a simple small dark grey note under a last message in chat view, directly on light grey background would be perfect. The line should be empty when chat history is synchronized and connection to server established, so message will be immediatly sent. But it should inform user about any other situation (disabled account, connection status other than 'connected', chat history download in progress, etc.).

I guess you will say that user should not worry about this stuff, but that is true only when things work. When connectivity is bad, user needs to know when he can walk back downhill, away from signal.

**Comment by singpolyma** [comment]
If you look in the "manage accounts" area, it will not show as "online" until all history has been downloaded, in my experience

**Comment by SamWhited** [comment]
Might be worth revisiting my old [pull to refresh PR](https://github.com/siacs/Conversations/pull/945) (except instead of pull-to-refresh jus using it as an indicator:


[![mamrender](https://cloud.githubusercontent.com/assets/512573/5929137/fe61923c-a64e-11e4-92e8-39b8a4549bd6.gif)](https://cloud.githubusercontent.com/assets/512573/5928884/afcfb06a-a64c-11e4-9184-02795f8893a4.gif)
