### ISSUE TITLE
Feature request: configurable sync cycle 

### ISSUE THREAD

**Issue by theCalcaholic** [siacs/Conversations#1247]
Conversations is definitely the best and most promising xmpp client for Android (actually the only one that is able to compete to proprietary protocol IM's). 
But at least for me, it has a big drawback: high battery/mobile data usage. 
It's always one of the biggest consumers of these resources. 

An option to counteract this issue could be to reduce the syncs per minute. I would greatly appreciate it if I was able to configure this setting myself and adjust it to my needs.

**Comment by iNPUTmice** [comment]
Do you use CSI and SM (see http://conversations.im/#features under Mobile optimizations)

**Comment by iNPUTmice** [comment]
also please try to provide absolute numbers like the battery use details or information on how much mobile data Conversations is using. Be 'highest' in some list is extremely relative and doesn't mean anything if you are not doing something else with your phone.

**Comment by theCalcaholic** [comment]
Oh, didn't expect you to be so fast. 

I'll provide the data.

**Comment by theCalcaholic** [comment]
Regarding CSI and SM:
I *did* use CSI; I disabled it now for testing the effect. 
I however don't know if I was using SM since I've no clue how the related German option is called (my system language is German). 

Die the battery and network usage I've to wait some his, since I blocked conversations for mobile network connections in the firewall so the current values are 0.

**Comment by iNPUTmice** [comment]
please enable Stream Management and CSI (you might also have to activate relevant modules like throttle presence or filter chate states otherwise it just wont do anything)

I'm pretty sure the feature is called Stream Management in German as well.

Also I'm closing this feature request because there is just no such thing as
> syncs per minute

so we can't have an option for that.

Which doesn't mean there is no room for optimization.

Also using our conference might be a more appropriate place to discuss this.
