### ISSUE TITLE
sometimes the first otr message could not be sent.

### ISSUE THREAD

**Issue by hschraep** [siacs/Conversations#1263]
Hello if i could not send the first otr message, i have first to write a clear text message. Then i go back to otr and the message was send. 
Stream management is active. I use conversations version 1.4.3 . Server version is prosody 0.9.8 .
Any ideas for that problem. It happens sporadically. Sometimes it works without problem but after a while it happens.

**Comment by aeuii** [comment]
Hi Developers, I would like to confirm this issue. 

- It seem to be server independent (ejabberd, prosody, both with stream management).
- It is quite a long standing problem since several releases and reported a few times ( e.g. #1087, and in the chat room: “Hi, I have the problem that sometimes messages stay in status "waiting" and wont be delivered. Only some of the messages in a conversation are affected.  In this case my chat partner receives nothing. It takes one day or more to deliver these "stucked" messages. We use OTR encryption.  Is this a problem of the app or a server sided thing?  Regards Adrian”)
- #1099 seemed to improve it and since that PR it does not happen that often (~1-2 a day for me), but still quite annoying

Unfortunately, it's hard to reproduce in a controlled way.

Do you have some suggestions how to debug it?

**Comment by aeuii** [comment]
One more observation: I have only a single contact that I chat daily with and the issue seem to be less frequent, once I added the conversations' chat room. It might be, that it only happens, when you have very few, low traffic contacts. Conversely, people with many contacts might not experience this issue as all.

If that's the case, then it a problem especially for people new to Conversations and XMPP, because they tend to have few contacts.

Could someone confirm that? Thanks!

**Comment by hschraep** [comment]
Hello many  thanks, which release would include the fix?

**Comment by iNPUTmice** [comment]
@hschraep 1.5.1 which is on its way to the play store right now includes the fix
