### ISSUE TITLE
Only notify on changed subject

### ISSUE THREAD

**Issue by JavaJens** [siacs/Conversations#1269]
Since the last (or second last) update I always get a notification stating the subject of my conferences.

This is quite annoying when, for example, on a bad connection. 
I'd suggest to only display a notification if the subject actually changed.

**Comment by SamWhited** [comment]
IIRC this is a bug with ejabberd. Updating your server should fix it.

**Comment by drequivalent** [comment]
Same issue here. It's irritating.

**Comment by JavaJens** [comment]
Thanks! I will look into this. Do you, by any chance, have a link to this ejabberd bug?

**Comment by SamWhited** [comment]
@weiss ⤴

**Comment by weiss** [comment]
The issue was fixed in commit https://github.com/processone/ejabberd/commit/6c712b6caaaed35471452612d643f785bfdf11ee.

I also wrote a [little module][1] to fix the subject stanzas (and other things) I receive when joining conference rooms on remote servers that have not been updated yet.

[1]: https://github.com/weiss/mod_filter_muc_infos
