### ISSUE TITLE
federate with kontalk network

### ISSUE THREAD

**Issue by pravi** [siacs/Conversations#1273]
Kontalk.net runs on xmpp with some customizations. They use a one way hash of phone number to identify users. I was able to send message to a kontalk id by manually entering its id. If conversations can do this phone number hashing, it would be nice. Kontalk currently does not support groups and if this integration works, we could use conversations group feature.

**Comment by moshpirit** [comment]
[AFAIK](https://github.com/kontalk/androidclient/issues/87), Kontalk would allow us to include others XMPP in this app, but not federate its protocol with the rest of XMPP so I think that we should use Conversations just for XMPP. If any person with Kontalk wants to talk with us, s/he can always include a XMPP account and share it via e-mail, SMS or social networks.

What we can to do to make easier the connection between these two clients is asking for a help menu in Kontalk which explain why and how to create a XMPP account if it's not already implemented in order to create a society which doesn't depend of just one centralized host (in this case the Kontalk's server).

**Comment by iNPUTmice** [comment]
I'm afraid that implementing their completely ridiculous phone number hashing would send a wrong message.

**Comment by pravi** [comment]
Best wishes to all the smart developers of conversations. I wish your client remains pure breed of xmpp.

**Comment by TheLastProject** [comment]
@moshpirit Kontalk users can be added from Conversations (or any XMPP client) just fine. They just have to send their Kontalk ID in the "My Personal Key" tab. It should federate without any issue whatsoever.

**Comment by abika** [comment]
@iNPUTmice 
> I'm afraid that implementing their completely ridiculous phone number hashing would send a wrong message.

Can you explain a bit more what you don't like about the hashing?

**Comment by iNPUTmice** [comment]
> Can you explain a bit more what you don't like about the hashing?

@abika sure. Depends on what purpose they are supposed to serve. If their purpose is to hide your phone number from the server operator they fail completely. For verification purposes you are sending your clear text phone number to them (which then triggers a SMS with a verification code.) No one stops them from calculating the hash at that time and store the hash<->phone number mapping in their database. And even if the are not doing this. Just calculating all hashes for all phone numbers in the world is a matter of minutes (hours at best). All available phone numbers are roughly 10^11. Hashes per second (on a CPU) are roughly 10^7

I have no problems with server operators using phonenumber@domain.tld style jids. But using sha1(phonenumber)@domain.tld style jids just makes things needlessly complicated for literally no benefit.

**Comment by daniele-athome** [comment]
First of all, I'd like to say that I like Conversations very much: I use it with my own XMPP server (not Kontalk) and with GTalk, it's very well-made. However, I wouldn't recommend it to my father or any of my non-tech friends. Unfortunately, Conversations is still a bare XMPP client, and despite I like its being pure XMPP (in fact, I use it just because of that), it's not meant for everyone. I'm making an effort to create something that normal people can use, and using the phone number for identification is what people want (see why WhatsApp and Telegram got such a wide adoption).

> If their purpose is to hide your phone number from the server operator they fail completely.

Using the hash is not meant to hide your number from server operators, of course they could be exposed by me (Nexmo, our SMS provider, keeps a record of the last 1000 verifications, at least that's what users can access, who knows if they store their data for the past decades too). The hash is meant for a minimal protection between users, to not expose their numbers to unknown users at the first chance (I prefer a minimal protection layer than having anything at all). I can clearly state that Kontalk is not an anonymous service, it's just private (as in encrypted).

> why and how to create a XMPP account if it's not already implemented in order to create a society which doesn't depend of just one centralized host (in this case the Kontalk's server)

XMPP too had just one server at the beginning...

**Comment by iNPUTmice** [comment]
>  However, I wouldn't recommend it to my father or any of my non-tech friends. Unfortunately, Conversations is still a bare XMPP client [...] it's not meant for everyone. 

So are you saying that the main reason that Conversations isn't user friendly is the lack of a phone number based auto discovery for contacts and the the lack of auto creation of your own account? Or are there other (UX) reasons Kontalk in your opinion is more user friendly than Conversations?

> Using the hash is not meant to hide your number from server operators

Ok fair enough

> The hash is meant for a minimal protection between users, to not expose their numbers to unknown users at the first chance.

I don't understand that. What are unknown users? Users I meet in a chat room? You could have just used anonymous MUCs for that.

**Comment by daniele-athome** [comment]
> So are you saying that the main reason that Conversations isn't user friendly is the lack of a phone number based auto discovery for contacts and the the lack of auto creation of your own account? Or are there other (UX) reasons Kontalk in your opinion is more user friendly than Conversations?

The phone number is one of them for sure. I assure you many people don't even know what a username is.
For instance, some other XMPP definitions such as *presence updates*, or guiding the user in the registration step, or making encryption almost mandatory (because some users don't even know what encryption is, I think we must do all efforts possible to introduce encryption as widely as possible, but of course with standard XMPP this isn't easy, I know, I'm having strong difficulties myself with that).

I'm just saying Conversations is not for everyone. I told you I think it's a great XMPP client and I love it, but that's all.

> I don't understand that. What are unknown users? Users I meet in a chat room? You could have just used anonymous MUCs for that.

Yes, it's especially for groups, but we won't use MUC.

**Comment by moshpirit** [comment]
What about including a Welcome screen which tells the users what's every of these things or some kind of manual / help that makes them understand why and how to use Conversations?

**Comment by daniele-athome** [comment]
Sure, that would be a start.

**Comment by pravi** [comment]
Another difficulty with conversations is having to pay or install via fdroid. Other clients on play store don't have the features conversations offer so I have to insist on conversations. Many people could not go through the many steps to get a reliable encrypted chat with conversations. But kontalk has been well received by non technical folks. If the idea is xmpp purity and elites only chat, conversations would suffice. But if the idea is to get working encryption for as many people as possible, the kontalk goes a long way. If we avoid duplication we can target more platforms. If the idea is to compete between apps on the android platform, then its fine. But if we want to enable secure communications to everyone then avoiding duplication and more collaboration will help us. Encryption is unfortunately has become a necessity to preserve human rights and democracy, cost of taking an elitist position is too high for people believing in human rights and democracy.

**Comment by moshpirit** [comment]
>Another difficulty with conversations is having to pay or install via fdroid. 

In F-Droid is totally free, people has to pay using Play Store. I think that it's a good way to promote free software and a little remuneration for the work. I prefer to using F-Droid and donate.

>Many people could not go through the many steps to get a reliable encrypted chat with conversations. 

Many steps? AFAIK activating OTR is not a big deal at all and Conversations allows End to end encryption in Security settings.

**Comment by pravi** [comment]
When WhatsApp is free of cost, having to explain about donating and why you have to pay won't get you far when they are not aware of Free Software. Having to enable non-trusted apps, installing fdroid from browser, then installing conversatiins, then finding an xmpp service, then registering (some allow in band and some only via web, so you got to figure this out), and after going through all these steps, otr cannot work when both contacts are not online. So the second dance of open key chain, pgp keys starts. Do you seriously think common folks would go through all these steps when WhatsApp is already working for you? I'm not saying theoretical situation here. I had to give up in it and switch to sms (which is daylight loot and is not a smooth experience, lost messages, delayed delivery...). Kontalk has been simply amazing. It just works for everyone. This saturday I was giving a talk on privacy and their director started using kontalk and he posted about it in their staff WhatsApp group. It can happen with Conversations only in dreams.

**Comment by andersruneson** [comment]
Why, if already stated I apologize, do you need Conversations to work with
kontalk if kontalk is so great that you say?

**Comment by moshpirit** [comment]
>When WhatsApp is free of cost

""""""""""""free of cost""""""""""""". Paying with privacy is a huge cost and it supposedly costs 0,89€/year.

> Having to enable non-trusted apps, installing fdroid from browser, then installing conversatiins, then finding an xmpp service, then registering (some allow in band and some only via web, so you got to figure this out), and after going through all these steps, otr cannot work when both contacts are not online. 

That's why we need to people understand that these steps totally worth it. Anyway, I can send messages to an offline contact, s/he'll read it when s/he gets online, just like happens in any other IM.

> Do you seriously think common folks would go through all these steps when WhatsApp is already working for you? I'm not saying theoretical situation here. 

Yes if they really appreciate their privacy. Don't you?
IMO the big deal is letting them understand that all of this work is because privacy is really important and if they prefer to use first any other IM like kontalk which only allows them to talk with people with the only server of kontalk instead of using xmpp and talk with people who enjoy their freedom from any other xmpp server it's OK to us, but we prefer to use XMPP bc it respect our privacy more than kontalk. I'm not saying that kontalk is bad, I'm saying that it's better than Whatsucks and Telegram but it's not better than Conversations or Xabber. 

>This saturday I was giving a talk on privacy and their director started using kontalk and he posted about it in their staff WhatsApp group. It can happen with Conversations only in dreams.

I'm really glad to read this, seriously, it's a really good thing, but the goal is using xmpp, not kontalk if we really want freedom.

**Comment by moshpirit** [comment]
>Why, if already stated I apologize, do you need Conversations to work with kontalk if kontalk is so great that you say?

He doesn't _need_ Conversations, he just want to people be able to access to kontalk by using conversations

**Comment by andersruneson** [comment]
WHY does he want to people be able to access to kontalk by using
conversations?

**Comment by moshpirit** [comment]
Please, this is not a chat, read the issue before asking this kind of things.

>Kontalk.net runs on xmpp with some customizations. They use a one way hash of phone number to identify users. I was able to send message to a kontalk id by manually entering its id. **If conversations can do this phone number hashing, it would be nice**. Kontalk currently does not support groups and if this integration works, we could use conversations group feature.

**Comment by pravi** [comment]
I need conversations to work with kontalk for interoperability. I'm technical enough to setup conversations, but I should be able to talk to a friend who can't get conversations to work. Kontalk does not block other xmpp servers. I was able to talk to my kontalk account from a regular xmpp account. So kontalk does not federate is simply not true. @moshpirit so you prefer people continue paying with their privacy? Conversations does not lose anything other than its ego of being pure and elite by making it easy ti federate with kontalk network. We all win if efforts spend on both kontalk and conversations is combined and we take xmpp/kontalk to iphones, firefox oses, windows phones and the rest. You might not like it, but if we have to beat WhatsApp and bring real privacy to our friends and families who are not geeks like us, we have to work together and collaborate. Other than the usernames kontalk is just another service in the xmpp federation.

**Comment by moshpirit** [comment]
>@moshpirit so you prefer people continue paying with their privacy? 
Privacy shouldn't be something we should pay, but nowadays we're paying for not having privacy and xmpp developers and xmpp hosts needs donations to keep fighting for our privacy and freedom, so yes, we need to pay a really low cost compared to what society lose everyday using centralised and privative software.

>We all win if efforts spend on both kontalk and conversations is combined and we take xmpp/kontalk to iphones, firefox oses, windows phones and the rest.

Well, I totally appreciate your work, Kontalk is doing it really good but it's just not for me, I prefer to keep using XMPP and I think that we all should use it so I think that we should focus in the real goal improving xmpp clients and servers and publicizing it and informing people about it.

>Conversations does not lose anything other than its ego of being pure and elite by making it easy ti federate with kontalk network.  We all win if efforts spend on both kontalk and conversations is combined and we take xmpp/kontalk to iphones, firefox oses, windows phones and the rest. You might not like it, but if we have to beat WhatsApp and bring real privacy to our friends and families who are not geeks like us, we have to work together and collaborate. Other than the usernames kontalk is just another service in the xmpp federation.

I don't see it that way, @iNPUTmice created Conversations with a really good idea in mind that you don't share and that's fine because Conversations uses a GPL license so you are always welcome to fork his work (and the work of the rest of the developers) and create your own version and distribute it for free. In fact, that would be great. 

Don't misunderstand me, I think that your intentions are really good and you want to bring privacy to the rest of the society, but I think that directly improving xmpp is a faster and better way to make it possible.

**Comment by pravi** [comment]
@moshpirit even if conversations does not want to federate with kontalk, the reverse can happen making conversations redundant. 

https://github.com/kontalk/androidclient/issues/496

**Comment by daniele-athome** [comment]
Well it's not entirely true... Conversations is a plain Xmpp client
