### ISSUE TITLE
Are PGP messages signed? Can the signing be enabled/disabled?

### ISSUE THREAD

**Issue by viric** [siacs/Conversations#1299]
In OTR, it is clear what it does. But for PGP I don't know if the messages are signed or the signatures are verified.

Sometimes I'd like my text not to be signed (less liability), sometimes signed; could that be an option?

**Comment by iNPUTmice** [comment]
PGP messages are not signed.


I personally have stopped using PGP encryption a while ago. That means I can no longer eat my own dog food. And dogfooding generally is what makes Conversations such a great product. While I don't see an immediate reason to remove OpenPGP support from Conversations I think everyone would be better of if the PGP encryption part would be handled by someone who actually uses this on a daily basis.

So I'm calling out for someone to take over the responsibilities with OpenPGP. A first step would be to migrate to the new API version of openpgp-api. Later on you there are several open issues like:

#632
#711 (Decryption when in background) - Important one imho
#822
#957
#1013
#1299

If you are interested in that you would be given a lot of freedom in the architectural decisions.
Changing the way keys are discovered (JID lookup, instead of presence announcement) might also be an interesting step.

**Comment by viric** [comment]
Thank you for the proposal; I just wanted to use PGP when OTR fails. I was trying to push people to use it for an eventual group chat, but I agree that PGP is not the best solution.
Do you foresee any implementation of the group OTR or so, for more than two participants?

**Comment by viric** [comment]
Nevertheless, I have to note that I'm surprised by the revival of PGP the keybase.io people is doing.
