### ISSUE TITLE
Force loading MAM on opening chat 

### ISSUE THREAD

**Issue by kriztan** [siacs/Conversations#1328]
I've often noticed that after joining a left room not all messages arrived my phone. So I would like to force a MAM reload on opening the chat view or maybe on tipping a button. 
My current workaround is clearing all messages and I have to wait until there are as many messages in the list that I could scroll to the top of the messages. Only in that case I'm able to 'force' a MAM reload. Not really user friendly... Or is there another way to force reloading?

**Comment by Tokodomo** [comment]
I have to agree, because of this weird duplicate message bug with MAM: https://github.com/siacs/Conversations/issues/1357... I often clear my message history in Conversations, but there is no option (in Conversatons) of force reloading the history from the server via MAM. The only quick solution for me so far, is to remove and re-add my account, but doing that is rather stupid, because I lose all my fingerprints (and more)... And finally, there is actually no way to delete single messages in Conversations, it would make life so much easier - I could simply delete all the duplicate or uwanted messages! This is really a must have, and almost all Messenger on the market give you that choice.

**Comment by iNPUTmice** [comment]
just as an FYI you can clear the history and end the conversation (there is
even a button for that) and when you reopen the conversation it will try to
load the history from mam

**Comment by Tokodomo** [comment]
That would be nice, but as kriztan already stated, after you clear the history, you have to wait until there are as many messages in the list that you could scroll to the top of the messages. Only in that case you are able to force a MAM reload.
