### ISSUE TITLE
Receiving files... 

### ISSUE THREAD

**Issue by kriztan** [siacs/Conversations#1342]
... were often delivered as button with checking file size. This happens on images and other file types. I couldn't figure out, why this doesn't happen on every file. But I think this happens if the phone is in sleep mode.

**Comment by iNPUTmice** [comment]
what version?

**Comment by kriztan** [comment]
A self compiled Conversations 1.6.0 with latest httpuploadcomponent


-------- Ursprüngliche Nachricht --------
Von: Daniel Gultsch <notifications@github.com>
Gesendet: 21. August 2015 08:43:28 MESZ
An: siacs/Conversations <Conversations@noreply.github.com>
CC: "Christian S." <christian@pix-art.de>
Betreff: Re: [Conversations] Receiving files...  (#1342)

what version?

---

**Comment by hanz1** [comment]
I've also came across that intermittently, but now I keep getting just urls for the file uploaded to the upload server. 

I tried to figure it out, but so far what I can see is that Conversations did not issue the HTTP HEAD request to get the filesize (both for http/https) so it would just get the link to the file instead of showing a thumbnail for the images/files.

FYI, I was testing this on two devices with self compiled conversations (latest version + httpuploadcompnent) and the thumbnails did show up for one-to-one chats. The way I managed to recreate the error is when sharing files through conferences.
