### ISSUE TITLE
make encryption a simple toggle

### ISSUE THREAD

**Issue by pravi** [siacs/Conversations#1352]
Instead of the current drop down it could be made a simple toggle (just a lock/unlock button). When omemo is available, use it, if not fall back to otr. Try openpgp as last option. I think this would make it much simpler for most users. Many non technical users would not be able to distinguish between omemo or otr (openpgp is for advanced users anyway)

**Comment by marix11** [comment]
Agree. It should remember last used encryption option like it was before 1.6

**Comment by strb** [comment]
This is likely to lead to a lot of confusion with most users. I'm all for automating settings to simplify them, but in this case I don't think it's a good idea, because the UX of the different encryption schemes is very different. They are not at all interchangeable, from a usability point of view as well as from a feature point of view.

**Comment by iNPUTmice** [comment]
Conversations 2.0 will probably drop everything besides OMEMO. But it is a way to early for that. OMEMO is still in an experimental stage and there is not a single desktop or iOS client that supports OMEMO.
