### ISSUE TITLE
omemo can't be used when contact is not 'online'

### ISSUE THREAD

**Issue by pravi** [siacs/Conversations#1355]
There was some issue with presence updates and we could not use omemo even though both were really online and chatting with plain text (contact details showed 'last seen: never). Why does the initiation needs this? Ironically otr option was available.

One contact was onenetbeyond.org and another on yax.im (tried with poddery.com). Not sure if its a conversations bug in presence subscription.

First try,

Yax.im could not see onenetbeyond.org (reverse worked)

Second try,

Poddery.com could see onenetbeyond.org (reverse was not)

**Comment by strb** [comment]
Just to clarify, by "can't be used", you mean that the option was not available in the encryption selection menu, correct? This sounds like an issue with PEP. In order for OMEMO to work, the server(s) need to support XEP-0163, because PEP is used to announce keys.

Can you give me some additional info or maybe logcat output regarding the problems with presence updates?

**Comment by pravi** [comment]
Yes, the option was disabled. Ok onenetbeyond.org does not support pep 0163 (all xeps checked by conversations are unavailable)
