### ISSUE TITLE
Improve handling of physical keyboards

### ISSUE THREAD

**Issue by enko** [siacs/Conversations#1387]
At the moment conversations barely has support for physical keyboards.

What would I suspect:

* Shift+Return: Sends message (When the return setting is not ticked)
* Ctrl+Tab: Activate the drawer/sidebar with the conversations (maybe some other keycombo, but it should be activateable).
* Be able to navigate with the arrow keys in the drawer/sidebar

**Comment by iNPUTmice** [comment]
i started working on this in 6308dcfdd42adabbe1f4e3ec28ec8e2b4f766f8c

> Ctrl+Tab: Activate the drawer/sidebar with the conversations

that sounds reasonable and is implemented in above mentioned commit

> Be able to navigate with the arrow keys in the drawer/sidebar

I changed that to Ctrl+Up/Down to avoid potential confusion with trying to move the cursor back and forth in the input field

> Shift+Return: Sends message (When the return setting is not ticked)

I changed this to allow Shift+Return to enter a line break in the inputfield when the enter is send option is set. I feel like this is more natural and close to other chat programs

I'm not completely done with this i'm planning on implementing some convince stuff that for example if you start typing in the input field the drawer/sidebar will close automatically

And I might also implement Ctrl+[0..9] to switch to the respective conversation (which might not be very usefull since you might not know the position of the  conversation you are tryping to open but it probably won't hurt either.

BTW the keycodes for up/down and left/right are switched on my anker bluetooth keyboard... I worked around that by also allowing left/right to navigate between conversations...

**Comment by SamWhited** [comment]
> And I might also implement Ctrl+[0..9] to switch to the respective conversation

IRSSI uses Alt+[0..9] (and Alt in general as an application-specific meta key, since most system specific shortcuts use Ctrl, I think). Not sure that it matters, but it might be looking into what other things do, I suspect that more things use alt for application specific shortcuts and Ctrl for more global cross-application shortcuts (copy/paste and the like). That's just a guess on my part though.

**Comment by jkufner** [comment]
Both ctrl+number and alt+number work in Chromium. Unless there is a good reason, I would support both combinations.

**Comment by iNPUTmice** [comment]
Conversations now supports alt and ctrl.

On my android device I feel that ctrl+key works better because for example alt-tab is linked to some task switcher... However in Arc I don't receive ctrl+keys at all...

Also fixed the directional keys issue. For some reason the mapping was specific to the device orientation...

**Comment by enko** [comment]
Nick completions would be cool with tab key. Ctrl+numbers works fine in arc here.

**Comment by iNPUTmice** [comment]
bbbc30e8234f14c9f340e0c29bb6b91a4bf640ee adds tab completion in conferences

**Comment by iNPUTmice** [comment]
let me know if you have other ideas for key bindings.
I'm thinking maybe Ctrl-q to leave a conversation but Conversations usually lives by the principle of keeping conversations open...

**Comment by krt16s** [comment]
When I am in the Contact list (Start conversation), just typing a character should automatically filter/search the list, like e.g. WhatsApp does that.
