### ISSUE TITLE
OMEMO deniability

### ISSUE THREAD

**Issue by knoy** [siacs/Conversations#1391]
I skimmed through the code and it appears that according to XmppAxolotlMessage OMEMO is using AES-128-GMC. GMC mode is an AEAD and is self-authenticating so wouldn't this mean that OMEMO is not deniable because it can't be spoofed even without an HMAC ?

Perhaps I'm misunderstanding the flow of the crypto or something. 

Another point to note is that is if this the case deniability (of say OTR) does not apply as much today because of mandated TLS use by XMPP operators. GMC mode is also one of the latest, fastest and most secure modes of AES operation.

**Comment by strb** [comment]
Good thinking, but not quite. While it is true that GCM is an authenticated encryption mode, it's still symmetric, meaning the authentication is performed using a *shared* secret. If you receive a message from me, you can use this shared secret to check authenticity, so you can be sure I sent you this message, but you can't prove to anybody else that I wrote it, because you also know the shared secret, so you could have forged this as well.

In fact, OMEMO messages are just as deniable as axolotl messages are. There is an additional encryption step in between, but as no other data is fed into this other than that which is contained in axolotl messages, this doesn't change the deniability properties.

In other words, let's say you have a session with me, and you send me a message X. Let's call the plaintext P, ciphertext C, payload key K, axolotl header H, and axolotl header shared secret S. We both know S, and can use it to derive the keying material for the header encryption and authentication, but nobody else knows S. So because I know I didn't generate message X, I know it must have come from you, because nobody else could have generated H. But I could also forge such a message. I could generate a different K, call it K', use this to authenticated-encrypt forged plaintext P', yielding C'. Then I generate a forged header H' containing K' using the same secret S. To outsiders, the resulting forged message X' is just as "authentic" as X, and thus X is deniable.

To interested parties I can only recommend this [blog post](https://whispersystems.org/blog/simplifying-otr-deniability/) by the WhisperSystems folk on this topic.

**Comment by knoy** [comment]
OK cool, thanks for clearing things up
