### ISSUE TITLE
no more photo and file sending in 1.6.10 (multiuser chats)

### ISSUE THREAD

**Issue by israuor** [siacs/Conversations#1435]
why's that?

**Comment by iNPUTmice** [comment]
you have to update your HttpUploadComponent

**Comment by israuor** [comment]
you mean on the server?

**Comment by israuor** [comment]
you mean on the server?

**Comment by iNPUTmice** [comment]
what ever provides the http upload functionality needs to be updated

**Comment by israuor** [comment]
got it .. thank you 
--

**Comment by ashutoshshukla1** [comment]
Hi @iNPUTmice 
Sorry, I did not get your solution. Can you please explain me a bit more how can we enable photo sharing in the multi user chat ? 

Thanks

**Comment by SafwatHalaby** [comment]
In order to use file sharing in MUCs and/or with offline contacts, one must use [XEP-0363: HTTP File Upload](http://xmpp.org/extensions/xep-0363.html). HTTP File Upload requires an extra server module. @israuor 's server module was out-of-date and updating it resolved the issue.

The general component, which the OP is talking about, is available [here](https://github.com/siacs/HttpUploadComponent). Alternatively, an Ejabberd [contrib-module](https://github.com/processone/ejabberd-contrib/tree/master/mod_http_upload) and a [Prosody module](http://modules.prosody.im/mod_http_upload.html) are available.
