### ISSUE TITLE
Support server names that are different than UID domains

### ISSUE THREAD

**Issue by rbarlow** [siacs/Conversations#1437]
XMPP servers don't always have the hostname (or the certificate) that corresponds to the domain name that is part of the userid. For example, the user might be user2@example.com, but the server might actually be chat.example.com. When this happens, Conversations rejects the server's TLS certificate since the server's hostname does not match the user's domain. Many XMPP clients allow the server hostname to be specified independently of the username for this situation.

A workaround is for the server's certificate to use the subjectAltName extension so that the user's domain is valid, though this may not always be possible.

**Comment by iNPUTmice** [comment]
even if you specify a separate hostname the certificate must still be valid for the domain and not the hostname. Clients that let you specify the hostname only do this to circumvent DNS issues.

> Conversations rejects the server's TLS certificate since the server's hostname does not match the user's domain

thats not correct. Conversations rejects the certificate because the CN in the certificate doesn't match the domain. Conversations works perfectly fine in scenarios where hostname!=domain

**Comment by rbarlow** [comment]
I'm new at hosting an XMPP server and did not know about http://wiki.xmpp.org/web/SRV_Records. Apologies for the noise!

**Comment by BuddyButterfly** [comment]
Just to hook to this old entry. I am not able todo what iNPUTmice suggests: hostname!=domain.
Where can I set this?
