### ISSUE TITLE
Conversations uses an avatar file format not known by some clients

### ISSUE THREAD

**Issue by Dragnucs** [siacs/Conversations#1442]
Conversations is using a file format for avatars that is not support by any other client I tried. Be it web, android or desktop.

Related bug on another software if you want to cooperate with them: https://github.com/edhelas/movim/issues/49

**Comment by Natureshadow** [comment]
Are you actually talking about a file format issue, or about an issue with the way the Avatar is shared?

Some clients use vCard for Avatars, others use PEP. This is far from perfect. So, in order to evaluate this bug report, could you make clear whether data is actually shared with the other clients, and that this data is errornous?

**Comment by Dragnucs** [comment]
It is mostly related to a file format issue. If you look at the movim bug, you'll notice that the client there knows that the avatar has changed but fails to display it. On other clients, they too know that it changed but they either use an older functioning one or do something unexpected.

Also, if I change my avatar using another client, my own conversations client on my phone doesn't get updated but it gets updated elsewhere for users using conversations.

The way the avatar gets propagated is deterministic due to file formats issues and bugs. If you want me to do a certain test case, please let me know.

**Comment by lsanderson** [comment]
I'm seeing this too. If I set my avatar from Conversations, the image is uploaded and stored as a webp image file on my prosody server. I use Gajim for the desktop and here the image is never shown, I asume because of the format. If I set my avatar from Gajim, the image is uploaded in jpg or png, and then both clients can see it.

**Comment by andersruneson** [comment]
As far as I know, gajim does not support pep avatars anyway.

**Comment by Dragnucs** [comment]
@andersruneson Most other clients have problems with WebP even if they support the avatar's PEP.

**Comment by abika** [comment]
+1 here. Native support for WebP is limited to Chrome, Opera and Android. Reducing bandwidth is important but there is no point in exchanging images which cannot be displayed.

How about publishing the user avatar additionally in png or jpg format? The standard (XEP-0084) allows clients to choose which format they want.

**Comment by fiaxh** [comment]
Conversations does not comply with the standard here. Data stored on the `urn:xmpp:avatar:data` node may only be PNG "to ensure interoperability".

Quote from XEP-0084 (User Avatar):

> User publishes avatar data for "image/png" content-type to data node and optionally publishes other content-types to HTTP URLs.

>The \<data/\> element is used to communicate the avatar data itself, and **only for the "image/png" content-type** (support for which is REQUIRED).

Furthermore, the "bytes" field in the `urn:xmpp:avatar:metadata `info is falsely set to 0.

**Comment by mimi89999** [comment]
@iNPUTmice Could you please comply with the XEP and make Conversations publish PNG avatars because no client can show that WEBP avatar? That is really annoying. Even if you consider WEBP better than PNG, that is not a reason to break compatibility.

**Comment by Dragnucs** [comment]
This is no longer an issue.
