### ISSUE TITLE
Encryption method indicator / auto enable encryption

### ISSUE THREAD

**Issue by tbeitter** [siacs/Conversations#1456]
1) right now there is no indicator to show the encryption method a contact used to send a message. As Conversations does not automatically switch to the incomming method right now I have to guess if I have to answer using PGP/OMEMO/OTR.

2) I do not see an option to enable such a thing like "automatically answer encrypted to encrypted messages". I think that would be nice, for example if the user already has an accepted omemo/otr fingerprint or a PGP pubkey of the sending contact. This option would be a workaround for 1) as it could use the right encryption method itself.

**Comment by therob84** [comment]
Hey,

I would say point 1) is not quite correct :
- If you have some received messages in the history, below each message you can see the encryption type
- Dependent which current encryption type you have choosen, the label of the encryption type is changed according to this choice. 
- BUT, I think the behaviour is still NOT working as intended!
As one can see on my screenshots, between the choice OMEMO and unencrypted there is no change of the encryption label at the messages....
- should I open a new issue for this? 
Together with the wrong coloring around the messages this could be related to #1441 .

![screenshot_2015-11-03-19-11-11](https://cloud.githubusercontent.com/assets/15350793/10917397/d364e888-8260-11e5-9208-8bc093436f81.png)
![screenshot_2015-11-03-19-11-00](https://cloud.githubusercontent.com/assets/15350793/10917398/d37037ce-8260-11e5-9042-7271b09d82e2.png)
![screenshot_2015-11-03-19-10-45 width=50](https://cloud.githubusercontent.com/assets/15350793/10917396/d360c064-8260-11e5-93fe-e603d7b1a48b.png)
[how I can resize the imags here?]

**Comment by iNPUTmice** [comment]
this is going to sound cryptic but I'm jet lagged and can't sleep.
the default value for getPreviousEncryption() should be
conversation.getNextEncryption() instead of NONE. this would in the case of
the posted screenshots paint the plain text bubbles red if the user selects
OMEMO as next encryption.

in general: the red bubbles aren't there to indicate the type of encryption
but simply to warn you if something is odd.

cryptic... get it?

**Comment by strb** [comment]
>  Together with the wrong coloring around the messages this could be related to #1441 .

Just for our understanding, how is the coloring wrong in your opinion?

**Comment by therob84** [comment]
Thank's guys for coming by!
1.) Before your explanation, I did not know how the colors should be interpreted at all, I must admit!
So, your intention was: red color = warning? Could you explain this?
At the Screenshots [and additionally not shown in screenshot]:
- If OMEO is checked --> all are green. OK, why not. [but: OTR messages are red! why?]
- If OTR is checked --> all is green --> OK, it is at least encrypted. [but: OTR messages are also red! why?]
- If un-encrypted is checked --> same coloring as OTR would checked! --> why?

I don't get the point of this coloring, sorry.

2.) What would you say about the idea, make the coloring just according to the used encryption, as I wrote in #1441 ? (OMEMO = green / PGP & OTR = yellow / not encrypted = red)

3.) If you still want to warn in any way, make a red border around the message-input-area, would be my suggestion. (While I still don't understand, what this warning should be about...)

4.) Additionally, this proposed 'new' coloring would also make sense to apply for the sent-messages at the right side (now: all are grey!)

5.) What is your comment on introducing a  <i>"long-tap on a message should provide a 'properties' window with the used encryption method and the <b> sending and (delayed) receiving </b> time" </i>? 

6.) do you maybe mean the other way round: <i>"default value for conversation.getNextEncryption() is getPreviousEncryption() instead of NONE"?</i> Would make more sense in my opinion...a new conversation should continue with the last used encryption type, right?

Could I make my point clearer and does it sound like a reasonable approach for optimising?
Sorry for beeing that long-winded...
Cheers, Robert

P.S.: Will you go to the google meeting this weekend? If yes: can we expect any news about conversations/OMEMO afterwards? How is the status at the XMPP-Standard-Foundation draft for OMEMO? (PM would be also nice ;-) )

**Comment by iNPUTmice** [comment]
the warning is not to prevent unencrypted messages but to prevent an
attacker from sneaking wrong messages into your conversation. let's say you
are using encryption method x. and an attacker manages to inject a message
encrypted with y into your conversation that message will be marked red.

**Comment by therob84** [comment]
1.) OK, understood, more or less! But: you are describing a highly unlikely scenario!
- If you think you are able to reliable recognize sneaked messages, you should probably warn the user more drastically, because in this case he has a seriously problem with his communication infrastructure...right?
- But in the daily live of an average user he is just botherd by red or green colors, every time the encryption mode is changed (triggered by the partner or the user itself, a malfunction or a unintentionally click), and In the case of a real sneaked message he wont pay attention anymore!

2.) Still I think your intended function is not working properly, if I have a look at my screenshots.
I canot bring togehter your explanation with my screenshotted experience. But maybe I still did not understand your idea behind for 100%...

3.) I would highly appreciate if you can comment on all my other points above in a short way, because my intention was to increase usability (and security) of your app.

Cherers, Robert

**Comment by d9h02f** [comment]
> But in the daily life of an average user he is just botherd by red or green colors, every time the encryption mode is changed

I think the idea is that after setting the encryption method you want to use, you would never change it again.

**Comment by therob84** [comment]
OK. But the "problem" starts already if I am using a second client (desktop) with the same account, only supporting OTR (which I can't try myself, yet), or not?

BUT, while nobody tells anything against it: I am still convinced that <b>my idea of coloring</b> (OMEMO = green / PGP & OTR = yellow / not encrypted = red) can provide the <b>same feature</b>, while even adds more functionality by assigning <b>colors to the encryption strength</b>.
Who disagrees and why?

**Comment by therob84** [comment]
iNPUTmice: Do you like to comment on my last post? 
Without defending why it is like it is, but just an explanation what you think about my suggestion.

**Comment by iNPUTmice** [comment]
this issue is all over the place and mostly duplicate to other issues such as #1350 or the (fixed) #1454
