### ISSUE TITLE
Minor feature request: don't notify on topics

### ISSUE THREAD

**Issue by rbarlow** [siacs/Conversations#1503]
I have a minor request for a behavior change. Currently, Conversations will notify me if a user sets a topic in a multi-user chat. Unfortunately, this means that if my phone disconnects and reconnects, I get a notification (even if the topic is the same as it was before). Could we do one of these two things?

1) Don't notify on topic changes.
2) Upon reconnecting, don't notify about the topic, unless it is different than it was the last time Conversations was connected.

Thanks!

P.S. I really enjoy Conversations. I recently tried to get my parents on my XMPP server and they have iPhones. There aren't any good clients for iPhones at all, so it really made me appreciate this one even more!

**Comment by SamWhited** [comment]
Conversations does not notify on topic chanegs; are you running an old version of ejabberd, by any chance? As I recall there was a bug where ejabberd sent topic changes as normal messages (with a body) a while back (so conversations will show it, because it's a normal message, not just a topic change).

**Comment by rbarlow** [comment]
@SamWhited Oh interesting! I am running 14.07 and I see that 15.09 is released, so perhaps that is what is going on. Sorry for the noise!
