### ISSUE TITLE
Conversations offers the possibility to change a MUC topic even if the user is not allowed to do this 

### ISSUE THREAD

**Issue by philipflohr** [siacs/Conversations#1542]
Preparation:
1. Start a MUC using Conversations
2. Invite some friends, dont give mod rights to them
3. Take the phone of one of your firends

Steps to reproduce:
1. Using the phone of a normal user, enter the conference details activity.
--> In the ActionBar the user is allowed to change the MUC topic
2. Change the MUC topic
--> nothing happens

I think the edit button should not be presented to normal users. If we can't determine if the user is allowed to edit the MUC topic, an error message should be displayed

**Comment by strb** [comment]
The issue here is that it might be possible for members to modify the topic (see http://xmpp.org/extensions/xep-0045.html#subject-occupant) but we can't actually know that without trying it seems, as http://xmpp.org/extensions/xep-0045.html#roomconfig states

> If the <user@host> of the 'from' address does not match the bare JID of a room owner, the service MUST return a <forbidden/> error to the sender

It might make sense to still disable this button as such room configuration is probably not very likely.

**Comment by iNPUTmice** [comment]
fixed in 60211a315ee8cf83a6b87836c30abc28e4dec272
