### ISSUE TITLE
Share file in group

### ISSUE THREAD

**Issue by sushrita** [siacs/Conversations#1547]
I want to share photos,media,files in groupchat /conference like we are doing it on one-to-one chat. I tried to add this feature by my own but I couldn't do that. So I thought you may help me.

**Comment by andersruneson** [comment]
For support, join the Conversations muc.
Or use jabber.at which has XEP-0363 support.

**Comment by jkufner** [comment]
Share via HTTP upload should work exactly in the same way as in
one-to-one chat. If there is no share button, it should be only matter
of UI change.

Share via all other means is problematic and most likely will not work
at all, because the protocol is not designed to do that. Your client
would have to upload he shared file to each other recipient separately,
meaning N uploads for N recipients. But with HTTP upload sharing it
means only one upload to web server and rest is on server.

**Comment by sushrita** [comment]
@jkufner so after adding the ui for attachment upload as in one-to-one chat there should be some extra things that need to be done for group chat.

**Comment by strb** [comment]
If your server supports [XEP-0363: HTTP Upload](https://xmpp.org/extensions/xep-0363.html), sharing files in MUC works. There's no need to add anything. 

Furthermore, this is an issue tracker, not a support forum. If you need help with something, join our MUC.

**Comment by 8015540242** [comment]
I need to attach the file on the MUC conversation I don't know how to enable that feature on this Application so kindly anyone help me out with this issue. Thanks in advance.

**Comment by licaon-kter** [comment]
@8015540242 Just click on the paperclip icon just as usual.
What server? Does it support http_upload?

**Comment by 8015540242** [comment]
am Using XMPP server...ya its support for one-to-one user chat. I need to implement the file attachment option for the MUC chat also.
