### ISSUE TITLE
Build failure

### ISSUE THREAD

**Issue by msva** [siacs/Conversations#1621]
Hi there! Can you advice, hat can be the reason of such build failure?
```gradle
:libs:MemorizingTrustManager:compileReleaseJavaWithJavac (Thread[main,5,main]) started.
:libs:MemorizingTrustManager:compileReleaseJavaWithJavac
Executing task ':libs:MemorizingTrustManager:compileReleaseJavaWithJavac' (up-to-date check took 0.012 secs) due to:
  No history is available.
All input files are considered out-of-date for incremental task ':libs:MemorizingTrustManager:compileReleaseJavaWithJavac'.
Compiling with JDK Java compiler API.
/home/mva/.vcs_repos/Conversations/libs/MemorizingTrustManager/src/de/duenndns/ssl/MemorizingTrustManager.java:564: error: cannot find symbol
                n.setLatestEventInfo(master.getApplicationContext(),
                 ^
  symbol:   method setLatestEventInfo(Context,String,String,PendingIntent)
  location: variable n of type Notification
1 error
:libs:MemorizingTrustManager:compileReleaseJavaWithJavac FAILED
:libs:MemorizingTrustManager:compileReleaseJavaWithJavac (Thread[main,5,main]) completed. Took 0.922 secs.

FAILURE: Build failed with an exception.
```
Only difference from the in-repo state of the library is:
```diff
diff --git a/libs/MemorizingTrustManager/build.gradle b/libs/MemorizingTrustManager/build.gradle
index 47491fe..8104897 100644
--- a/libs/MemorizingTrustManager/build.gradle
+++ b/libs/MemorizingTrustManager/build.gradle
@@ -10,11 +10,11 @@ buildscript {
 apply plugin: 'android-library'

 android {
- compileSdkVersion 19
- buildToolsVersion "19.1"
+ compileSdkVersion 23
+ buildToolsVersion "23.0.2"
  defaultConfig {
          minSdkVersion 7
-   targetSdkVersion 19
+   targetSdkVersion 23
  }

  sourceSets {
```
(to use the same buildtools versions, that Conversations itself)

btw: error persists even with up-to-date git-HEAD version of MemorizingTrustManager.

**Comment by iNPUTmice** [comment]
this is a bug tracker not a support forum. if you have questions try our conference at conversations@conference.siacs.eu

**Comment by msva** [comment]
Actually, the error message, that javac throws makes me think this is a
bug (in bundled library).

I just tried to keep polite discussion tone in the report, and provide
an option that I did something wrong. Although, I assumed that just
cloning is enough, if android build tools is already set up and build
another things fine.

// Btw, happy new year.

**Comment by strb** [comment]
Well we're not going to debug issues with your modified version for you. That's what @iNPUTmice meant by "this is not a support forum". What you're reporting is not an issue with Conversations, as it doesn't occur with upstream Conversations build system. And what's more, the error is, as you've correctly stated, in a bundled library. So you might want to report this to [them](https://github.com/ge0rg/MemorizingTrustManager) rather than to us. But any way you take it, it doesn't belong here. 

I hope you don't take this the wrong way. We're not trying to be assholes here, but it's already hard enough to keep a good overview of what's going on with the project without support requests for modified versions littering the issue tracker. As has been said, you're more than welcome to raise this in our MUC. But it does't belong in our issue tracker. Thank you for understanding.

**Comment by msva** [comment]
Anyway, as @ge0rg mentioned in the conference, please, apply https://github.com/ge0rg/MemorizingTrustManager/pull/46 to the bundled MTM ;)
