### ISSUE TITLE
OTR and OMEMO fingerprint verification UIs are inconsistent and suboptimal

### ISSUE THREAD

**Issue by RalfJung** [siacs/Conversations#1632]
The UIs used in OTR and OMEMO mode to validate the keys of the peers are inconsistent. Furthermore, they both nag users into accepting keys as verified without performing actual verification.

The OTR UI allows sending encrypted messages to a contact before validating his fingerprint. This is important, because it may not always be possible to immediately verify a fingerprint. OMEMO forces me to either acknowledge the fingerprint or not send the message - of course, people will just acknowledge and forget that they should do some further verification "later". I've done this myself.
On the other hand, OTR shows a rather large "Unverified contact" popup in the chat window that uses ~25% of the screen in landscape mode. This is very annoying, it may even lead people to just say "Yes, yes, I verified" just to get rid of this popup. OMEMO, instead, indicates untrusted incoming messages by changing the padlock to a red one. The change may be a little too subtle, but at least it doesn't nag people into incorrectly claiming they performed verification.

A possible solution to the "immediate verification or no message" problem in OMEMO could be to introduce another state for OMEMO fingerprints: There could be a distinction between a key that was accepted as "known", and a key that has actually been verified. Messages would be sent to all known keys, but if there was an unverified key amongst them messages would appear similar to incoming messaged from unknown keys - somehow indicating that this _has_ been encrypted, but the identity of whom exactly it has been encrypted for has not been verified. The hardest part here may be finding a UI that doesn't scare users off, doesn't lead them them to just skip verification, but reminds them to actually perform verification when possible.
The bonus option would be to have some QR-code based key verification and gamification, leading users to verify their OMEMO keys without even knowing what they are doing ;-)

This same UI could then also be used for OTR: When establishing an OTR session with a previously unseen key, the key has to be at least acknowledged as "known" before a message can be sent. Within this session, messages are either marked as "encrypted but unknown peer" (that would be a red lock right now), or as properly encrypted, depending on whether they peer's key is just known or actually verified.

I'm sure there are better names for distinguishing these two states. The point is that people have to notice when a new key appears (as that's what an MitM attacker would do), they have to perform some confirmation before sending messages to a previously unseen key - but at the same time, they may not be able to immediately verify that this key is actually the correct one, because the peer is just living on another continent. They should be able to start chatting encrypted with unverified keys, as that's better than no encryption at all, but they should somehow be reminded that the connection isn't full secured until an actual verification has been performed.

Wow, this issue got longer than anticipated. If you agree with me that the issue I brought up is real, I'd be happy to discuss how it can be fixed and to help implementing that fix. However, I am not a UI designer nor an Android developer, so I may need some guidance.

**Comment by iNPUTmice** [comment]
Hi,

I think OTR can be considered to be end of life. Putting any more work into this is probably not worth it.

From a pure technical standpoint there is no difference between a trusted session and a verified session in your proposal. Messages would behave exactly the same. (A user can send and receive messages in that session) Thus strictly speaking a 'verified state' would just be eye candy and not behave any differently.
For an experienced user - who understands the technology behind this - the process of actually verifying sessions (in person) also isn't different if there was a verified state. Meaning if during verification they would discover an unknown session they would just purge it or at least move it into an untrusted state. Not having a verified state would actually mean less work for an experienced user as they could just leave trusted sessions as trusted and only purge unknown sessions (which there hopefully aren't any.)

So if we can agree that there is no difference from a technical standpoint and no difference for an experienced user the question remains if adding a verified state on top of the trusted state would make the life of a novice user easier. This can probably only be discovered in user studies but I would make the case that it doesn't.
Right now the behaviour for someone - who at least puts some work into understanding end-to-end encryption - is pretty straight forward: There are devices. Devices are identified by fingerprints. I can either trust a device then messages will get send to that device or I don't trust a device then messages won't get send to that device. 
Imho adding a third state to what is actually pretty straight forward (Trust or No trust) might only make things more complicated.

I'm not trying to be too negative here towards new ideas and new concepts. I think the crypto world is in desperate need for new ideas. Right now the only working solution is trust on first use - which obviously has some downsides and doesn't work well with mult-end-to-multi-end encryption. 

I personally doubt that encryption will ever become easier than comparing fingerprints.

**Comment by strb** [comment]
I've given this some thought. I think the first thing we need to note is that this:

> OMEMO forces me to either acknowledge the fingerprint or not send the message

really only applies to the first message that you exchange with a contact. If after that, devices are added, you can just as well choose not to accept the new fingerprint at that time, but still send messages. They will then just not arrive on the new device. And in that context you can very well use the existing trusted session to verify that fingerprint. So the scenario in which this applies is somewhat more limited right off the bat.

That being said, I'm not entirely opposed of the idea of a "trusted but not yet verified" state, or "known" as you've called it. I would see this as an opportunity for the app to keep track of which keys you have actually manually verified, so that you don't have to. This would make it easier for the user to go the trust-on-first-use route, while still verifying keys when you get the chance. I see this as a "best of both worlds" approach. The big problem, and you've already pinpointed this correctly, is building UX for this.

Now there are a lot of ways to go here visually (Orange locks?), but I think what it boils down to is that there is no way to design UI for this that is intuitive in the sense that it would be fully understandable by just looking at it without knowing the tech that underlies the protocol. The big risk that I see is that we're going to introduce features with very specific use-cases, where it is not immediately obvious to the "non-technical" user what the actual use-case for the feature is. This always leads to what seems like misuse , but is actually bad design ("you're holding it wrong").

So I actually really like the idea of using gamification here. I think the UI itself is not as important, visually that is. What's more important is what actions we allow the user to take, and what they're called. I do think that we won't get very far without making the trust names explicit in the UI. We're already pushing the bounds of how much information we can convey with a simple slider (Fun fact: under the hood we already have 9 different trust states). This is already a little problematic. At the moment, it's more a "it makes sense when you know it" UI, and less a "it makes sense when you look at it" UI. Making things more explicit by showing a "rating" for the current trust state would help a lot in making the UI understandable to newcomers. It also gives an opportunity to frame things in such a way as to guide the thought process of the user regarding actions to take on a key. 

Currently, the names of the trust states are descriptive. I think we need to use terminology that is more actionable. Currently, we're mainly talking about ```Trusted``` and ```Untrusted``` keys. These don't really convey any information on the effect of their status. ```Untrusted``` could conceivably be just such a ```Known``` state as you've proposed. All the information about what this state *means* for the communication must be derived from context. Furthermore, there isn't really a good middle ground between trusted and untrusted. There's no good way to term a new state that should lie between the two such that it's immediately obvious that that's the intention behind it. It might make more sense to move to simpler, more placative terms, for example the scale: ```Rejected``` -> ```Accepted``` -> ```Verified```. These terms are very clear in what effect the states are, and have an immediately obvious order. Furthermore, they correspond very well to understandable actions. So for example, if a new key is published, it will be rejected by default. I need to accept it before it is used. If I want to be extra sure it's the right key, I can then further verify it.

By constricting the actions the user can take, we can further shape their understanding of this scale. For example, we could make the default "verify" action use QR codes or NFC. This makes it clear that the user is supposed to actually "physically" verify the key itself, not just take a pro forma action designed to make the UI happy. We of course need to figure out a good way to still include manual verification here, but maybe it's already enough to send the message if the default action is QR/NFC. Basically we need to figure out how to make the user *want* to upgrade (so as to encourage them following through on verification), but not feel like they *need* to (so as to prevent verification just to dismiss annoying warnings).

This also turned out a lot longer than intended. I'm just brainstorming here. Thoughts are welcome.

**Comment by zak333** [comment]
Hello everybody,

I agree that key verification is not very well designed. The main problem I think is, that the whole concept of verifying a persons identity from a security perspective (Man-in-the-Middle) is completely unknown to any casual user. Unfortunately this concept is not solvable only through technical means (yet). The user *has* to do some deliberate interaction to verify a key and he has to do it with at least some minor background information what this verification is used for. So annoying the user with some warning message is not the way to go, because people will just click the button without verifying anything.

On the other hand forcing the user to do some key verification before being able to send any message at all is still bad because it is an added barrier which lowers simplicity and users will complain what this stupid thing is used for and why the heck this supposedly so much better messaging app is so complicated.

So my proposal for this is as follows:
At the first session with a user, the key is exchanged and encrypted messages are sent without any explicit user interaction needed. A single informational message is printed, notifying about a new key and that it should be verifyed in the account details. (Maybe a button "verify by QR now" or something like that could be added.)

In every users account details all the keys are then listed and can be verifyed by using NFC or QR codes as mentioned. Here some explanation could also be added which can be expanded using a nice UI element. Additionally an option to simply verify the fingerprint should be available as well but probably at the last option. If this is selected, a longer text can be displayed showing the fingerprint and explaining what you have to do (-> comparing the fingerprints by phone for example) but usually users will hopefully not need to do that.

For further messages, if any not verifyed key is used, a minor information can be displayed next to the lock icon. This information should not be that annoying to make users blindly accept all keys without awareness but still be visible enough to make users curious about what this icon means. If they then look further, they hopefully have motivation to do the verification correct.
A different lock color is probably not good, because new users will then see only the unverifyed color at first not knowing that it means anything at all.

As for OTR encryption: I agree that in comparison to OMEMO it is obsolete, but as long as there are still Jabber clients used who do not support OMEMO I think it should still be supported. Unfortunately it surely will take a long time until OMEMO gets a wider usage so I hope the to-be-implemented solution will be extended to OTR keys as well. This will of course also make the UI more consistent when keys are not handled differently in these cases.

**Comment by iNPUTmice** [comment]
>> OMEMO forces me to either acknowledge the fingerprint or not send the message

> really only applies to the first message that you exchange with a contact. If after that, devices are added, you can just as well choose not to accept the new fingerprint at that time, but still send messages

and

> At the first session with a user, the key is exchanged and encrypted messages are sent without any explicit user interaction needed.

I thought about adding a TRUST_ALL_EXISTING_SESSION_ON_FIRST_USE config parameter that would basically do what @zak333 said and which would fix the problem @strb mentions.

However I'm kinda afraid that this might lead to a confusing 'what is this now?!' if the trust keys activity will then appear at some time in the future.

Like I said I have no idea how to actually solve this problem but...

> For further messages, if any not verifyed key is used, a minor information can be displayed next to the lock icon. 

...just adding *more* UI elements certainly will not help the problem.

On a broader scale, instead of dumbing down the UX and potentially make it less and less secure I would rather go the route of educating the user and try to explain (with some UI overlays / some sort of tutorial) how encryption works. 

Personally I think that encryption doesn't have to be grandma proof. If you and your grandma are on a private server you are running on a plastic router in your living room you are already secure enough. No one will care enough about what you have to say to your grandma to actually exploit your router. On the other hand - people who actually need encryption are usually not stupid. I'm pretty sure that if we do the explaining right that those people will be able to understand.
If you don't care enough about encryption to make the effort to understand some basic concepts - meaning if your life doesn't depend on it - just don't use it. Nobody cares about what you have to say. Especially not the admins of the public XMPP server you are using.

To quote from the mission statement I wrote a while back

>  However Conversations is aware that end-to-end encryption by the very principle isn’t trivial. Instead of trying the impossible and making encryption easier than comparing a fingerprint Conversations will try to educate the willing user and explain the necessary steps and the reasons behind them. Those unwilling to learn about encryption will still be protected by the design principals of Conversations.

**Comment by zak333** [comment]
> However I'm kinda afraid that this might lead to a confusing 'what is this now?!' if the trust keys activity will then appear at some time in the future.

I think it depends on the way the message is displayed and what it says. A big red exclamation mark in a red box with an alarming message urging the user to do something important is certainly confusing. I would recommend a subtle message in an unflashy color, something like:

New [OTR|OMEMO] key added for $USER. [Button]Verify now[/Button]

Maybe with a sort-of-info-icon at the beginning. It can be discussed to even not show a verify-now-button. Or maybe a small link "Futher info..." can be added in a very small textsize.
My idea is to inform the user about that something is going on. Users who don't care just ignore it, but if you are interested (maybe at a later point) you have the possibility to look further into it.

> ...just adding more UI elements certainly will not help the problem.

Well I didn't mean to add them but to exchange the current UI. But I have to note that I only know the OTR behaviour for now. I didn't have the possibility to test OMEMO yet, but as I understand there is some UI for accepting the key.

For the other remarks I agree that it shouldn't be too "grandma proof" and I like the idea of "[educating] the willing user" in a decent way. That's exactly what I want to accomplish with my idea.

**Comment by lovetox** [comment]
>I thought about adding a TRUST_ALL_EXISTING_SESSION_ON_FIRST_USE config parameter that 

this is a good idea, it should be on per default.

experienced users, the ones who understand the tech behind it, would know or have an indication somewhere in the UI that its not a verified fingerprint, for example the contact is orange or some other color. you could then go into the contacts details and verify the fingerprint.

i think Threema does it like that.

People who dont care, still have reasonable security, can chat and are not annoyed by messages or warning symbols.

People who need the extra "I am not watched by NSA" proof, can verify the fingerprint.

**Comment by RalfJung** [comment]
@iNPUTmice
> I think OTR can be considered to be end of life. Putting any more work into this is probably not worth it.

I agree it is legacy technology. However, until at least Pidgin supports OMEMO, it's better than nothing... (though it *is* annoying, I frequently get OTR gibberish on one client when I have an OTR session going on in the other client.)

> For an experienced user - who understands the technology behind this - the process of actually verifying sessions (in person) also isn't different if there was a verified state.

I think I count as an experienced user, and I do see a difference. (This is actually something that also bothers be a lot with TextSecure/Signal.) Namely, I will sometimes want to just accept a key - either because this is the first OMEMY key, so I have the choice between accepting that key and not using encryption, or because I *do* know my friend got a new phone, but he's not here right now to verify the fingerprint. In this case, I'd really like to remember that there is a fingerprint here which I should manually verify. Right now, I have to remember this manually. I'd prefer if the program could remember this additional bit of information for me.

I also believe that this will help improve the security for novice users. Threema has been mentioned above, I think their idea is brilliant: They kind of turned the boring "manually verify your friends' keys" into a game. In the contact list, you can see whether you just have "a" key of that contact (yellow), or whether you actually did a manual comparison of the keys (green). I think it also shows you for example a global percentage of "how many contacts have you verified", and some more UI design which makes people want to "just get all their contacts green". You know, it's like an achievement. To get a contact green, you have to scan a QR code from your contact's screen. People don't even know they are doing end-to-end fingerprint verification, it's just fun and a game.

Now, OMEMO with its multiple endpoints is special here. You already mentioned that TOFU is less of a great solution. But I think this "gamification of manual verification" could still work. (And it doesn't have to be all gamified from the start.) Since I may not want to do a QR-pairing with all individual devices of a friend, the QR code could actually contain all fingerprints of devices of the same owner that this device has manually verified, so e.g.
* Person A scans his tablet's QR code on his phone. Now the phone knows 2 keys, and both of them are fully verified.
* Person B scans the QR code from A's phone, now trust *both* of A's keys.

> I personally doubt that encryption will ever become easier than comparing fingerprints.

I agree. But I think comparing fingerprints can be easier than one person reading the key out aloud, and the other person checking whether this matches. Plus, applications can help remembering *which* fingerprints I compared.

@strb 
> (Fun fact: under the hood we already have 9 different trust states).

oO
Is this documented anywhere? I did read the OMEMO summer of code blog, and I do remember something about 5 states or so, but not 9.

**Comment by iNPUTmice** [comment]
I mentioned that before in other places but it fits in here as well so I say it again.

Things will get easier UX wise once we drop OTR and PGP support in Conversations 2. You are mentioning Threema as an example. They don't offer three different kinds of encryption either. (4 if you count 'unencrypted') They just do encrypted messages and encrypted only.
Differentiating between, trusted, untrusted, verified, unecrypted, pgp encrypted, otr encrypted makes the UI unnecessarily complex compared to differentiating between trusted, untrusted and verified. So IMHO the focus of UX design be under the premiss that there are only OMEMO encrypted messages and nothing else.

> However, until at least Pidgin supports OMEMO

only a mad man would ever write an OMEMO plugin for pidgin so no that should not be the condition under which we drop OTR support.

**Comment by zak333** [comment]
> Things will get easier UX wise once we drop OTR and PGP support in Conversations 2.

Well the day Conversations drops OTR support will be the day I uninstall it (with regret). Right now all my contacts either use Pidgin or Xabber or Psi+ and neither supports OMEMO and as I already said I doubt it will happen in the foreseeable future.

I really do think that OMEMO is superior as well. But in this case it comes down to the question: Do you want to create your ideal messaging app or do you want to create a messaging app that is usable and therefore indeed used by as many users as possible, meaning keeping other XMPP clients in mind and being compatible to them.

Anybody who wants to create a software application to become established by many users either needs a killer feature or already a userbase to work with. As far as I see it, Conversations has neither.

If I misunderstood you and Conversations 2 is indeed a long term project not due in at least the next 2 years then you can of course ignore this post.

**Comment by licaon-kter** [comment]
If vers. 2.0 drops OTR why won't you still use 1.8.3 then?

**Comment by zak333** [comment]
> If vers. 2.0 drops OTR why won't you still use 1.8.3 then?

Using an out-of-life version is not an option (no further fixes and security updates, etc.).

**Comment by RalfJung** [comment]
> Things will get easier UX wise once we drop OTR and PGP support in Conversations 2. You are mentioning Threema as an example. They don't offer three different kinds of encryption either. (4 if you count 'unencrypted') They just do encrypted messages and encrypted only.
Differentiating between, trusted, untrusted, verified, unecrypted, pgp encrypted, otr encrypted makes the UI unnecessarily complex compared to differentiating between trusted, untrusted and verified. So IMHO the focus of UX design be under the premiss that there are only OMEMO encrypted messages and nothing else.

You have a point. I think Conversations is doing a remarkably good job here. Thanks a lot :-)

That said, I think the trust level and the used encryption are rather orthogonal. So, every supported encryption should be able to map every message it sends/receives to "untrusted, known, verified", and that's what should then determine the UI (red, yellow, green - in Threema terms). For example, unencrypted is always untrusted. Both OTR and OMEMO and PGP have a notion of keys and fingerprints that have to be compared, so all of them you define "keys that were manually verified = verified, keys that I have seen before = known, keys I did not see before = untrusted".

> only a mad man would ever write an OMEMO plugin for pidgin so no that should not be the condition under which we drop OTR support.

Obviously I have no saying in your decision for dropping OTR support. All I can say is that the vast majority of my friends are using Pidgin, so the day Conversation drops OTR support will be the day that I have to stop using end-to-end encryption with them. (And honestly, right now I can't outright recommend Gajim either.) However, this discussion is also entirely orthogonal to this issue ;-)

**Comment by Natureshadow** [comment]
Pidgin has always been a major issue in all of XMPP. Point me at only one thing it does reasonably good and you get free beer everytime we meet (if we ever should).

So if we hold XMPP development back for Pidgin users, I don't think we'll ever make it a mainstream accepted messenger.

**Comment by zak333** [comment]
> So if we hold XMPP development back for Pidgin users, I don't think we'll ever make it a mainstream accepted messenger.

I don't think we're holding XMPP development back when still supporting OTR as compatibility feature for other clients.

Threema has two disadvantages:
1. Closed Source
2. All users who want to exchange messages with Threema users do have to install/buy Threema as well.

When dropping OTR support Conversations will basically have the second disadvantage as well. And it is already hard enough to persuade other users trying out another messaging app. Right now my argument then is, that Jabber is an open protocol where you have a lot of different programs already available to choose from.

My friends use Pidgin primarily not because they think it is a good program, but because it supports different messaging protocols (like ICQ for example). I will never be able to tell them that when they want to continue exchanging messages with me they have to install Gajim. And I would not expect them to do.

In an ideal software world I would agree with all of you. Unfortunately reality looks different.
Just imagine LibreOffice not being able to open Word documents...

**Comment by d9h02f** [comment]
The thing Conversations has going for it, which NO other XMPP client has, is that it actually works. All other clients are so horrendously awful it makes no sense to hold off on implementing certain functionality simply because those clients are too crap to implement it as well.

**Comment by zak333** [comment]
> it makes no sense to hold off on implementing certain functionality

Again: I am not proposing to hold anything back.

**Comment by LuccoJ** [comment]
Woah, isn't it a bit too soon to drop OTR when it's the technology that every single other client uses, except for a somewhat incomplete OMEMO plugin for Gajim?
OMEMO might be nice, but it's new and was developed for Conversations first. Making Conversations drop existing technology in favor of it, after bare months OMEMO was introduced, sounds like wanting to dictate standards to all other much better established clients.
This is unless "Conversations 2" has a long way to go, but the current version is 1.9.1, so...

**Comment by strb** [comment]
> but the current version is 1.9.1, so... 

Yes, and soon we'll be on 1.10. Semver is not decimal numbers, so don't worry so much.

**Comment by lovetox** [comment]
@strb indeed ! i also thought after 1.9 comes 2.0 :D

**Comment by djmaze** [comment]
Another related question: Is there a reason OMEMO doesn't support authentication through SMP, i.e. through asking a question, like OTR? I think it is a major drawback we have to exchange fingerprints manually via a separate channel.

**Comment by cyBea** [comment]
Hi there!
I really appreciate having OMEMO in conversations right now!
My experiance as a guy how has advanced knowledge in encryption:
This morning I tryed to created an jabber account for/and with a friend how is has only basic knowlegde and little patience. When we added our accounts the default encryption was OMEMO which I consider quite good - know as I know of OMEMO (read a lot on github and other bugtrackers). Our Problem was this only switch to accept the other fingerprint with no hint how to see the own fingerprint. Not finding it in 2 minutes we fallback to OTR with easier verification. Damnit!

I have some suggestions for UIs
- "OMEMO Fingerprint trust" page:
  - No option "on" or "off" but "verify now", "verify later" and maybe "reject" - "reject" could also be shown only for additional devices to same account
 - dont show fingerprint
- "Verify now" Page
  - Display others AND own fingerprint (or provide Button to see it easily)
  - Button to show own keys QR-Code and Button to scan others QR-Code
  - (SMP (https://en.wikipedia.org/wiki/Socialist_millionaire_problem) would be great as well if possible)
- This UI could be consistent with OTR (which I would keep until mayor IMs have support for OMEMO)

I support different lock colors like "yellow" for "known" and "green" for "verified". If the user chooses to stick unverified she should not be bothered (except with yellow lock)

> only a mad man would ever write an OMEMO plugin for pidgin
@iNPUTmice Why do you think so?

**Comment by kousu** [comment]
Please don't be to rash to give up on OTR. v4 is adopting axolotl, so says word of God: https://lists.cypherpunks.ca/pipermail/otr-dev/2016-March/002447.html

The brand recognition of OTR will be strong competitive with OMEMO's head start.

**Comment by kousu** [comment]
Please don't be to rash to give up on OTR. v4 is adopting axolotl, so says word of God: https://lists.cypherpunks.ca/pipermail/otr-dev/2016-March/002447.html

The brand recognition of OTR will be strong competitive with OMEMO's head start.

**Comment by kousu** [comment]
Please don't be to rash to give up on OTR. v4 is adopting axolotl, so says word of God: https://lists.cypherpunks.ca/pipermail/otr-dev/2016-March/002447.html

The brand recognition of OTR will be strong competitive with OMEMO's head start.

**Comment by kousu** [comment]
Please don't be to rash to give up on OTR. v4 is adopting axolotl, so says word of God: https://lists.cypherpunks.ca/pipermail/otr-dev/2016-March/002447.html

The brand recognition of OTR will be strong competitive with OMEMO's head start.

**Comment by iNPUTmice** [comment]
OTRv4 is a long way from revision, standardization, and even longer from adoption.

If OTRv4 gets adopted in the XMPP world we would still need an OMEMO-like wrapper around it to support multiple devices. OTRv4 could - if it were a thing - and it's not - replace the signalprotcolol part of OMEMO.

**Comment by devurandom** [comment]
Coming back to the original issue of OMEMO and fingerprint verfification UIs:

I use OMEMO myself with other people and also enabled it once for a non-technical user, so they don't have to bother with the verification steps. Recently they wanted to switch servers (i.e. created a new Jabber account on a server with better capabilities), so I walked them through the process.

Then we began writing, and apparently they accidentally tapped the enable-encryption button or similar. At least I suddenly received OMEMO encrypted messages, even though previously I was unable to enable encryption for my chat with that user (Conversation said that there were no OMEMO keys for them available). Now they got a notification about some "fingerprint" - that's what they wrote to me - but I was not able to assist them, without accepting their fingerprint - Conversations refused to allow me to skip the verification. And because the message was annoying them and they had no clue about encryption and they didn't actually need it, either, they just accepted the fingerprint they were presented.

We both each have only one device capable of OMEMO encryption (i.e. Conversations). Thus there is no multi-end, yet.

The experience would have been better, if they would not have been presented with a cryptic "verify fingerprint" dialogue that only contains a bunch of numbers and an unlabeled switch. It would also have been better, if I would not have been forced to mark the other user's fingerprint verified - encryption is not something we rely on for our lifes, but just a nice extra and in this case even unintended.

So much for the problem, now about how to solve it: I like the idea of unifying the UI of the different encryption technologies. As a non-technical user I don't care whether I am using OTR or PGP or OMEMO. I might want to know that the message was encrypted and whether it came from a verified source - or not. Thus the traffic light / "Threema" model, regardless of the used technology, seems good. I would adjust this model to not use any colours until encryption was actually enabled - i.e. show the messages in usual black/white, if the conversation has always been unencrypted - MAM can further improve the certainty of the never-encrypted state. Further details about the used encryption technology, keys, and so on, can be put into a long-tap "message details" dialogue (like Signal does).

That the user cannot immediately destinguish the encryption technology used for a message does not appear as problem to me, as no one will be able to sneak in messages through a previously unused encryption technology - those messages would appear as "unverified" or "yellow" and alert the cautios user.

Verification should indeed be just a UI thing - it should not prevent me from communicating at all, if I was not yet able to verify the fingerprint. This will just make encryption feel annoying and prevent people from helping each other out, as was shown above.

The verification dialogue could offer some guidance text (maybe behind an info button), support the use of QR/camera and NFC by default, instead of cryptic numbers, and use a checkbox instead of a switch button. The description could e.g. be something like "we want to make sure the person you are writing to cannot be impersonated by anyone else, thus please take a photo of the QR code on their screen or touch their device with yours (make sure NFC is enabled)".

**Comment by knoy** [comment]
Hi guys,
A bit late to the party I think everything @devurandom said in his last paragraph is spot on. OMEMO has seem some formal adoption by different clients & security audits but I think the biggest hurdle right now is verification of keys. Practically speaking impersonation attacks are probably a lot more likely to be attempted than traditional interception attacks as almost all connections to OMEMO-capable servers are already secured with TLS. On top of this breaking the crypto isn't feasible unless an attacker has a lot of time or resources to study the implementation.

I think this verification UI is terrible and needs to be fixed ASAP for OMEMO to be considered useable. Blindly being forced to click a toggle switch next to a bunch of numbers or not be able to send messages (and none of this explained) is really bad UX. Mandatory verification makes security worse. Keys should be verified whenever possible, but the chance that a victim COULD verify keys at any moment is often enough for a targeted attacker not to risk it.

If OMEMO is going to be the replacement to OTR it needs to be able to at least do what OTR can already do.  And OTR's strongest selling point for a long time has been easy key verification (especially with SMP). Like @iNPUTmice said I think it should be considered EOL at this point and not further developed,

**Comment by iNPUTmice** [comment]
Conversations is now using [Blind Trust Before Verification](https://gultsch.de/trust.html).
