### ISSUE TITLE
[enhancement] advanced account config

### ISSUE THREAD

**Issue by tmarchst** [siacs/Conversations#1657]
It would be nice if JID, and Server could be configured separately.

On some Servers the JID is <user>@<domain>.<tld> and the actual server is something like xmpp.<domain>.<tld>.

**Comment by strb** [comment]
Since your post is a little unclear, I'm assuming you're referring to [this situation](https://github.com/siacs/Conversations#where-can-i-set-up-a-custom-hostname--port) where the JID would be ```alice@example.com``` but the server is reachable under ```xmpp.example.com```? In that case, your server setup is broken, and you should [fix it](http://prosody.im/doc/dns#srv_records). Also, please read the FAQ and/or search through past issues before opening a new one, this has been discussed many times before.
