### ISSUE TITLE
[Not a bug] UI flaws.

### ISSUE THREAD

**Issue by MRZA-MRZA** [siacs/Conversations#1749]
Hello.
I'm experiencing troubles using Conversations. I compiled them to the list below.

- I didn't find a way to group contacts by accounts. I have the same contacts on my accounts so my contact list in Conversation confuses me by same contacts repeating few times.

- I don't see contacts' statuses. How do I know whether contact is online or offline?

- Font size is too big. But it's only possible to increase it.

- Same as for contacts, conferences are not grouped by account.

- No option to disable avatars and "bubbles" in chat. Also no option to make my messages appear on the left.

- List of participants takes whole screen. It would be good to have it constantly visible (with quick show/hide function) to the right of chat.

That's all I noticed so far. I hope it would be helpful to improve usability of Conversations.

**Comment by licaon-kter** [comment]
> I don't see contacts' statuses. How do I know whether contact is online or offline?

Enable `Settings -> Send button indicates status` but yeah you need to enter a discussion with said contact to see it.

> Font size is too big. But it's only possible to increase it.

But it's ok in other apps? That's by your system settings I guess.

**Comment by iNPUTmice** [comment]
>> I don't see contacts' statuses. How do I know whether contact is online or offline?

> Enable ```Settings -> Send button indicates``` status but yeah you need to enter a discussion with said contact to see it.

There is also ```Show dynamic tags``` which shows the status in the contact list. (Not the conversation overview.)

> I didn't find a way to group contacts by accounts. I have the same contacts on my accounts so my contact list in Conversation confuses me by same contacts repeating few times.
> Same as for contacts, conferences are not grouped by account.

Out of curiosity. Is there a good reason you have the same contact/conference in two accounts?

**Comment by jkufner** [comment]
> Out of curiosity. Is there a good reason you have the same contact/conference in two accounts?

I have plenty of theese duplicates too. It is mostly historical thing, but it is not practical to remove them, since other account may be a backup account and it would make history inaccessible in many clients. Same problem is with legacy networks and popular ugly networks available via transports. Then one person may be represented by four or more contacts in roster.

A good solution is to use metacontacts (XEP-0209) to group these together and have one of them as a primary contact, however, Conversations does not support this feature.

**Comment by MRZA-MRZA** [comment]
> There is also Show dynamic tags which shows the status in the contact list. (Not the conversation overview.)

Thanks. But how can I group contacts by status e. g. online first?

> But it's ok in other apps? That's by your system settings I guess.

The problem is that I usually want to see more text on the screen
 without scrolling. But Conversation uses two strings for message: first is for message and the second for nickname and time. I'd like to use something like "[timestamp] Nick: message". It is more compact.

> Out of curiosity. Is there a good reason you have the same contact/conference in two accounts?
I have backup account in case if server goes down.

**Comment by kousu** [comment]
As far as I know you don't. Conversations isn't like other IM clients. It's aping Hangouts/SMS apps/Facebook messenger, where you just have a list of conversations sorted by recency, and if you want to talk to a specific person you look them up in your contact list (either the system contacts or searching Conversations by text). I've heard that presence support in the UI wasn't even added until a bunch of feature requests came in about it. It weirds me out still too, because I'm used to the ICQ heritage of ICQ design, but I'm starting to get used to it and to see the wisdom. In a mobile world people's presence is always inconsistent, so it's better to focus on read receipts, like SMS.

If you want to sort by presence, use Xabber.

**Comment by MRZA-MRZA** [comment]
Another small issue I found: when I tap on participant's avatar I get their nickname and a colon symbol (':') in message text field but I want comma, not colon. So I tap backspace twice and input comma and space.

**Comment by iNPUTmice** [comment]
I'm quite happy with how the UI is right now.
