### ISSUE TITLE
Domain Name Associations (DNA)

### ISSUE THREAD

**Issue by rufoa** [siacs/Conversations#1782]
Hi all,

Do you have any plans to implement any part of [RFC7712](https://tools.ietf.org/html/rfc7712) (currently in draft)?

The POSH prooftype alone would be a great step forward for multi-tenanted environments like Google Apps, which are currently plagued by mismatched CNs in certs.

Many thanks.

**Comment by iNPUTmice** [comment]
Hi,

no there are currently no plans to implement POSH. And right now the benefits to the average end user are very small because to my knowledge there is no provider of multi-tenant XMPP.
If however you plan to become one or have some sort of commercial interest in this I'd be more than happy to make you an offer. My contact details or on [my website](https://gultsch.de).

**Comment by rufoa** [comment]
Thanks for your quick response!
