### ISSUE TITLE
[Feature] Button for viewing the whole topic in MUC

### ISSUE THREAD

**Issue by PapeCoding** [siacs/Conversations#1783]
If i'm not the owner of the conference (or have other rights) i cant change the topic of the MUC. This results in not being able to see the whole topic if it is longer than the screen is wide. If i could change the topic myself, than i could scroll through the topic while editing to read it.

Would be really cool, if it is possible to view the whole topic of a MUC via a button (or otherwise) even if the screen is small and the topic long.

**Comment by uchchishta** [comment]
*I thought I would post this here rather than a new issue:*

Currently Conversations uses "subject" in MUCs' titlebar than the "Title". It also can't be read fully even on my tab. So it should properly show Title, Subject & Description. Maybe in a card or two in conference details.

But I also think it will be handy if I can also just pull a card down from the titlebar in chat view itself; title also can show a notification badge if there is a update of the subject or description.

---

*You pull down from the title bar like you pull down your system notifications drawer; It expands!*

![tmp_14896-muc2144335460](https://cloud.githubusercontent.com/assets/25387925/23995684/a195a448-0a70-11e7-81c3-81328d139919.jpg)
---
<sup><sup><sup><sup> (*Just a rough sketch*)</sup></sup></sup></sup><sup><sup><sup><sup><sup><sup> *anyone wanna do this*?</sup></sup></sup></sup></sup></sup>

**Comment by iNPUTmice** [comment]
Implemented in current `master`.
