### ISSUE TITLE
Picture Upload / Transfer hangs at 0%

### ISSUE THREAD

**Issue by coupeborgward** [siacs/Conversations#1792]
Using PGP and having no issue to send each other encrypted messages. But when we try to add an image to the conversation it starts sending the image but hangs at 0%

using latest app, xmpp server (gtalk,hangout)

**Comment by iNPUTmice** [comment]
Let me start of by saying that gtalk is a terrible XMPP server unfortunately. XMPP server can provide a lot of extensions that make your life easier. Assist you in saving battery, increase reliability, provide file transfer and so on. Gtalk doesn't provide any of this because google of course wants users to use Hangouts.

So in order to send files over the gtalk server Conversations has to send them inband - meaning base64 encode them and split them up into hundreds of pieces. This should work but is (understandably) extremely slow.

So are you sure:
> But when we try to add an image to the conversation it starts sending the image but hangs at 0%

actually hangs and is not just super slow? If not can you provide and adb logcat from both sides? That will help to debug the issue. Might be that google is blocking inband file transfer.

In any case to make a long story short: If both parties use Conversations anyway I can only recommend using a proper XMPP server (for example jabber.at) - You can keep your gtalk for people who don't use Conversations at the other end.

**Comment by coupeborgward** [comment]
Daniel 

I followed your advice and I have to admit jabber.at is so much better. Thanks again

Rolf

**Comment by coupeborgward** [comment]
Daniel

I think we have a bug here.

I was trying to setup a conference using pgp. If the conference has only 2
members its all working really well. As soon as the third one joins the
third one can't decrypt any messages but the first ones can see and decrypt
all of them including the messages from the third one.



cheers
 rolf

**Comment by iNPUTmice** [comment]
There is an FAQ entry about encrypted group chats. TLDR: Using OMEMO might be the much better choice.
If for what ever reason you want to stick to PGP make sure that everyone sees everyones PGP key id in the conference details and can send pgp messages to them individually. However PGP was an experiment in a time where we didn't have OMEMO. And since no other client than Conversations supports PGP encrypted group chats there is virtually no reason to use PGP.

**Comment by coupeborgward** [comment]
yep we can send each other individually encrypted messages using pgp. so
the pgp key id has been exchanged. So theoretically it should work

**Comment by akallabeth** [comment]
I encounter image (and file) upload issues too.
The weired thing is it only occurs when the following circumstances are met:
* Server supports http upload
* File is >1MB

When sending small files everything works as expected, with larger ones it reports delivery failure.
* Logcat did show some SSL error
* Local Images can not be found for transfer afterward (Image can not be found, although the image is still on the phone)
* Same server works flawlessly with gajim

Just for the record, using conversations 1.11.6 from f-droid

**Comment by akallabeth** [comment]
Ok, the SSL error was SSLV3_ALERT_BAD_RECORD_MAC
and I'm using cyanogen 13 but I also encountered the issue with some friends phone using cyanognemod 11 and 12
