### ISSUE TITLE
Optional<one-time prekey>

### ISSUE THREAD

**Issue by sebastianv89** [siacs/Conversations#1832]
Version 3 of the OWS Signal protocol allows the one-time prekey to be empty in the PreKeySignalMessage (because the server might run out before the users comes online again and uploads more prekeys). This should never happen in OMEMO, because the server sends the complete list of prekeys. But the Conversations app uses the OWS library and thus it also allows the one-time prekey to be empty. By allowing this, the PreKeySignalMessage has no forward secrecy.

**Comment by iNPUTmice** [comment]
cc @strb

**Comment by iNPUTmice** [comment]
Hi,

since you obviously have some knowledge of the code do you think that that checking for the presents of the prekeyid after this line: https://github.com/siacs/Conversations/blob/master/src/main/java/eu/siacs/conversations/crypto/axolotl/XmppAxolotlSession.java#L170 is enough?

Inserting the line I mean:

```
if (!message.getPreKeyId().isPresent())
  break;
````

**Comment by sebastianv89** [comment]
Yes I believe that would solve the issue.
