### ISSUE TITLE
Pay for app even if available for free on F-Droid?

### ISSUE THREAD

**Issue by SecUpwN** [siacs/Conversations#1865]
Good evening `Conversations` developers, thanks for this wonderful app! I've just been reading a stunning comparison on the [German Kuketz IT-Security Blog](https://www.kuketz-blog.de/conversations-sicherer-android-messenger/). One of the main things that *really* makes me puke, is that your wonderful project does not mention the free availability of `Conversations` [on F-Droid](https://f-droid.org/repository/browse/?fdfilter=conversations&fdid=eu.siacs.conversations).

This not only draws away valuable contributors, but also people who may discover your website after having received a recommendation from people like me. **Please add the following to your README:**

[![F-Droid](https://upload.wikimedia.org/wikipedia/commons/thumb/0/0d/Get_it_on_F-Droid.svg/320px-Get_it_on_F-Droid.svg.png)](https://f-droid.org/repository/browse/?fdid=eu.siacs.conversations "Conversations on F-Droid")

* Badge to copy and paste to your `README`:

```
[![F-Droid](https://upload.wikimedia.org/wikipedia/commons/thumb/0/0d/Get_it_on_F-Droid.svg/320px-Get_it_on_F-Droid.svg.png)](https://f-droid.org/repository/browse/?fdid=eu.siacs.conversations "Conversations on F-Droid")
```

**Comment by iNPUTmice** [comment]
The F-Droid version is maintained by a third party and doesn't have official support.

**Comment by licaon-kter** [comment]
> This not only draws away valuable contributors

https://github.com/siacs/Conversations/pulls ? Really?

> also people who may discover your website after having received a recommendation

Those people that aren't valuable contributors of any kind, that can't get away from the Google Play ecosystem, that can't compile their own version or that they can't even use a search engine to find the F-Droid version can just show their support by paying the low price.

> The F-Droid version is maintained by a third party and doesn't have official support.

Yet it has plenty of support [here](https://github.com/siacs/Conversations/issues), if you have the logs :)

**Comment by IzzySoft** [comment]
I don't mind paying a reasonable price, so please don't get me wrong with what I'm saying now:

I'm using the F-Droid version, and I don't use Playstore (a.o. for privacy reasons; except for one phone, all my devices are either running without GApps or having no Google Account set up). The version from F-Droid runs fine, but has one big draw-back: Due to the lack of GCM, it brings down battery duration of my Wileyfox Swift from ~5 days (with Conversations disabled) to less than 2 days (Conversations running).

Now, I don't want to bind myself to Playstore for this – and F-Droid wouldn't accept the app with GCM built in. If you could attach the `.apk` (can be the same you put on Play) to the corresponding `releases/`, I could add it to [my repo](https://apt.izzysoft.de/fdroid/). Updates would be available within ~24h of your posting them here (tag + APK). Donation URLs would be shown in the F-Droid app (with my repo enabled there), and also on the WebIF (currently just one Donation URL, fix is on my 2do list to show all of them).

Would that be acceptable to you? Would you support that? As pointed out: as soon as it's attached to the release, I'd maintain the repo part. It would be the `.apk` built by you, with your signature.

**Comment by iNPUTmice** [comment]
You can't compare the fdroid version w/o GCM to no Conversations at all in
regards to battery consumption. You would have to compare GCM vs no GCM.
In my testing the version w/ GCM consumes the same amount of battery
compared to the version w/o GCM (same server same usage patters on average).
Receiving and processing messages will always consume resource. No matter
if GCM is in use or not.

**Comment by IzzySoft** [comment]
Thanks for your fast response, @iNPUTmice – so you're saying switching to a GCM enabled version wouldn't solve my "core issue" anyway? I'm using conversations for about a year now, but the battery issue just got very bad lately (for about 1..2 months). For a work-around I've hibernated the app – but without GCM that means I only will be informed about new messages when explicitly opening it again (while GCM would enable it to be "awakened on incoming message").

Maybe this should go to a different issue then? I had some peaks in the past, but they usually got cured by closing Conversations and reopening it (or at least by restarting the device after cleaning the cache). Lately, that doesn't help anymore. Might well be the server-end responsible here, so switching to a different account could solve it – but that again would cause a mess with OMEMO-enabled conferences I'm part of…

**Comment by licaon-kter** [comment]
It might be a device issue, working fine here and on other devices (without GCM), Conversations has little battery impact, albeit plenty of wakelocks.

Do open a new issue with logs & pics from BetterBatteryStats for a whole 100%-5% battery cycle having Conversation cunning all the time. (Do mention server, modules, Android version etc)

**Comment by IzzySoft** [comment]
Thanks, will do as soon as I have a "full cycle" complete. BBS is installed anyway, so I just need to find what logs to export from there and which pics you need. I could already provide a screenshot of Android's own battery stats, where Conversations is shown responsible for ~70% of battery consumption (as said, never had that before – just started about 3 versions back and got worse since then).

**Comment by licaon-kter** [comment]
Maybe something changed on the server? 
BBS has an "export report" thing IIRC, which has all the data, sanitize that I guess.
