### ISSUE TITLE
FR: Confirm image send after choosing an image

### ISSUE THREAD

**Issue by ivucica** [siacs/Conversations#1879]
Currently (1.12.x) involves tapping the image send button and picking an image to transmit.

It's easy to mistap the image. Especially with http upload, things happen so quickly that it's impossible to abort the transmission.

Certain other clients on Android allow confirmation before the image send happens.

Please consider adding an expert option to enable confirmation after choosing a file, but before it gets actually uploaded.

**Comment by nikolanik** [comment]
That's a great option!
Some preview before sending...

Also, it will be nice if users can select multiple pictures, like in Viber (eg. max 10).

**Comment by alexara** [comment]
It could be done like in What'sApp: You choose the picture and the picture will be previewed.

![example](https://cloud.githubusercontent.com/assets/13819719/15557304/9c09794a-22d2-11e6-941a-35b96a711ee5.png)

Below the preview there could be an input field where you can write a caption, which will be sent together with the image

**Comment by th3Bold** [comment]
To have such a function, to confirm the chosen image (or file), is really important.

At the moment it's very dangerous to send a picture (or file), because all you need to do is to click on the wrong image (or file) by accident [while scrolling] and some data you don't like to share is shared...

@iNPUTmice Hope you can insert a simply query, if the chosen picture (or file) is the correct one :-)

Thanks!

**Comment by Zekario** [comment]
I think this would be very nice to have.  I accidentally send images way too often. I've resorted to opening an image gallery app and then sharing the image to avoid accidental sending of images.

**Comment by stopANALytics** [comment]
> some data you don't like to share is shared

Enable editing of messages ;)

**Comment by ivucica** [comment]
@stopANALytics Hopefully, you are not serious :)

I'd prefer to not send photos to a remote HTTP server in the first place without a confirmation. I'd prefer not to get clients a chance to autodownload an image I shared by accident. I'd prefer not to depend on a remote client supporting message editing. I'd prefer not to send photos by accident to a type of group chat where the message cannot be edited (esp. XMPP to IRC gateways).

**Comment by tmolitor-stud-tu** [comment]
This is a very important feature that should be implemented!

I accidentally shared a photo I didn't want to share just a few minutes ago and my internet was so fast I didn't even had the ability to stop the transfer.

**Comment by pworldx** [comment]
This will be a very good feature for conversation

**Comment by eldoali** [comment]
This bit me twice, the second time was especially infuriating considering that I was also reconnecting at that time, and the list of open conversations refreshed under my finger just in time for a mistap. Considering the many votes for this issue, Is there any blocker preventing some progress on it?

**Comment by Kandr0s** [comment]
@eldoali Nobody is blocking it. Fell free to implement it.

**Comment by tmolitor-stud-tu** [comment]
Just use the Conversations Fork over here: https://xmpp.pix-art.de/
It shows a confirmation dialog before it sends an image.

Additional improvements over vanilla Conversations are:

- no external plugins required (voice recorder and maps plugin are both already included)
- the screen is automatically turned brighter when viewing images/videos
- fine granular settings for auto download sizes per connection type (roaming, cell network or wifi)
- fine granular settings for video and image compression quality
- progress notification for video compression (no silent background compression without any indication of progress at all)
- smaller mobile friendly video sizes (30 seconds video --> 2MB @ 360p versus 22MB in conversations)
- better settings menu with clearly arranged subgroups
- daily backup of history to sdcard and reimport on app reinstall (like whatsapp)
- daily text backups of history if wanted, too
- more modern design (round avatar images, background color of chat bubbles is nicer)

**Comment by licaon-kter** [comment]
@tmolitor-stud-tu Indeed some features are nicer, but feel free to either open a new issue with each feature request or add your voice to the existing ones.

**Comment by ivucica** [comment]
@tmolitor-stud-tu A fork is valued, and I'm glad to learn about it, but it is not the answer, especially not one clearly aimed mainly for German speakers and distributed only off-Play Store. Your post feels like an advertisement?

**Comment by tmolitor-stud-tu** [comment]
@licaon-kter @ivucica I came to the impression that @iNPUTmice doesn't want or can't implement some features clearly needed to make Conversations usable for non tech-savy people in standard day-to-day usage.

This long standing issue is not the only one. https://github.com/siacs/Conversations/issues/2126 would be another one.

And only recently @iNPUTmice added an inline player for audio, despite voices asking for this for a long long time (he tried to hide behind "too much permissions", a reason why a voice recording feature is still not buildin despite android allowing for permission requests at runtime since at least android 6).

Another long time issue that finally got somewhat resolved is the compression of video files.
In the corresponding issue @iNPUTmice told he won't ever implement this because he doesn't think this is a feature any IM app should have.
It took a long time and quite some persuasion until he eventually implemented it.

But it's these "small" things that make a messenger usable for non-tech users.

Its my general dissatisfaction with some of his decisions and the way he isn't open to strong arguments that would make Conversations usable for a larger audience of ordinary people _**and the fact that he is apparently ignoring all attempts I made to communicate directly or indirectly with him in the past year**_ that gave rise to my "advertising post" above.

And no: I'm not the developer of this fork, but as far as I know he made some similar experiences in regard to @iNPUTmice .

**Comment by licaon-kter** [comment]
@tmolitor-stud-tu Looking around [I'm not seeing any PRs from you](https://github.com/siacs/Conversations/pulls/tmolitor-stud-tu), ok, **it might sound harsh**, but all these are just feature requests, which will materialize when someone (not necessarily iNPUTmice!) actually codes them.
Coding (as other things) is plenty of work so I hope you understand that one will code whatever *they* want/like first.

As mentioned in the readme and plenty of times in the issues comments, PRs are welcomed, so if you are wiling to port some features from Pix-Art (or elsewhere) feel free to do it (don't port the colour theme though, that's just ugly, sorry :))

You can't code? [Neither do I](https://github.com/siacs/Conversations/pulls/licaon-kter), but I try to not feel entitled to anything, hence please, once you've said your opinion stop spamming with comments.

**Comment by daivat15** [comment]
@licaon-kter I was just going through the image picking and sending procedure but I am struggling to understand the work flow and the order in which functions are being called. It would be great if you can help me out with this so that I can attempt to solve the issue.

**Comment by licaon-kter** [comment]
@daivat15 No idea...

**Comment by Rudd-O** [comment]
This is the "oh shit I was about to send self-porn, phew, thank god that did not happen" feature.

**Comment by licaon-kter** [comment]
:+1: Work In Progress: https://github.com/siacs/Conversations/commit/3608b0eb44633ffae845b59e5b19fdfd8c0d96f4

**Comment by iNPUTmice** [comment]
Implemented in head

**Comment by wiktor-k** [comment]
This works very well! :clap:
