### ISSUE TITLE
Feature request for exporting/importing OMEMO keys

### ISSUE THREAD

**Issue by fuesschen** [siacs/Conversations#1892]
It would be a nice feature to be able to export and import the OMEMO keys for backup and transferring to a new device. So it should be possible to get the old history via MAM on a new device back.

Since this feature could also be dangerous in case of key leaking this maybe should be hidden in the expert settings.

**Comment by iNPUTmice** [comment]
https://github.com/siacs/Conversations/blob/master/README.md#how-do-i-backup--move-conversations-to-a-new-device

**Comment by DrAzraelTod** [comment]
What? That's a workaround, but a very poor one, that no ordinary User will ever be able to use.

And it produces unencrypted Backups (containing links to downloaded files that might not be there on the next phone and similar stuff), not i.e. just a key - encrypted with a keyphrase you had to choose while exporting.

So this is poor workflow, will result in more bugs/problems AND is less secure.

**Comment by bashrc** [comment]
I've just been complaining about this again, and yes it's a very cumbersome workflow which isn't particularly secure. I admit that I am not the average user and occasionally completely change Android images, so losing keys each time is irritating. What I'd like is a backup/restore keys option with a passphrase so that the exported file isn't in plain text. I could plug in an external USB drive and save it there, then keep the drive offline.

It's sufficient of an itch that I might try to implement this myself at some point.

**Comment by licaon-kter** [comment]
Same here with `adb backup`, basically exporting went ok, got an encrypted file (since the device was encrypted) that one can unpack (not sure if it had what it needed though) and then trying to restore nothing happens, no error or anything, but files are not actually restored.

I'll try a backup/restore soon, but it's a pain to deal with it failing :(

@iNPUTmice Was this tested before ? Did it work at some point?

**Comment by ivucica** [comment]
Please reconsider reopening this, @iNPUTmice. :-)

Manual use of `adb` is hardly a user-friendly workaround.

How about passphrase-protected backup onto a storage access framework-selected location, or using a share button? This would allow storing passphrase-protected keys onto something like Drive, or emailing, or onto a self-hosted SFTP location, or whatever the user considers secure enough.

**Comment by magoralczyk** [comment]
This is an absolute must have. In my family we're 6 people and everyone is getting a new phone every year, so I have always the situation where I cannot see my old messages, because they were not encrypted for my current device and moreover I have to greenlight the new key in all my gajim installations for carbons and tell the other people that I have a new key and they have to accept it in their gajims. This is totally crazy to get a new key with every new phone! This is the main flaw that drew my friends to telegram and whatsapp, and it is really ard to sustain on the good side...

**Comment by thomaspeterthiede** [comment]
please reopen it!!!!!!!

**Comment by mDfRg** [comment]
How exactly can I backup my key wit adb backup? Can anyone link some tutorial? And is it possible with encrypted device?

**Comment by licaon-kter** [comment]
@mDfRg version 2.4.0 will include full backup (history&keys) for an account

adb backup copies the whole app install.
