### ISSUE TITLE
SMS/texting support

### ISSUE THREAD

**Issue by luke-jr** [siacs/Conversations#1906]
Is there any possibility of using Conversations as Android's SMS app? I'm trying to set my wife's phone up to be simple, but having two different apps for messaging is just annoying...

**Comment by iNPUTmice** [comment]
Not on our todo list right.

**Comment by joshp23** [comment]
It would be great if conversations had sms support as well. This would make it indispensable for me.

**Comment by participante0** [comment]
@luke-jr, @joshp23: https://github.com/SilenceIM/Silence

**Comment by luke-jr** [comment]
That doesn't support XMPP... might as well use the native messaging app at that point. :/

**Comment by uchchishta** [comment]
You can also use SMS transport...

**Comment by licaon-kter** [comment]
Better have an app that does one function and does it better.
See this discussion too: https://github.com/SilenceIM/Silence/pull/390

**Comment by luke-jr** [comment]
@uchchishta Hmm! You mean an app that translates XMPP to SMS on the phone, and connect to it like another server? That'd be an interesting approach - does it exist already?

@licaon-kter SilenceIM seems to have some obsession with encryption, but it's pretty rare that I want to use encryption, and most of my contacts don't give a crap.

**Comment by licaon-kter** [comment]
@luke-jr To each his own

**Comment by uchchishta** [comment]
@luke-jr no, a server service that does that, and only one I know of is (Cheogram)[https://cheogram.com] but I have not used it, so I don't how it works.

**Comment by joshp23** [comment]
> @luke-jr no, a server service that does that, and only one I know of is Cheogram but I have not used it, so I don't how it works.

it works

**Comment by jcrben** [comment]
Xabber also declined to pursue SMS (https://github.com/redsolution/xabber-android/issues/137).

Looks like Silence planned to integrate SMS, but development has slowed. Once this is done, it seems like we could get a sync of all messages across web and mobile. Non-technical users can more easily gradually convert to XMPP which will expand opportunities for growth.

**Comment by jcrben** [comment]
In the long-run I suspect it's better if we migrate away from SMS into something more open. SMS is encumbered by dependencies on mobile networks, and while I'm not super familiar with its technical details there appear to be issues (see e.g. https://en.wikipedia.org/w/index.php?title=SMS&oldid=824629169#Unreliability).

But the vast majority of people I talk to use SMS. I would like to drop down to SMS when there's no XMPP available, meanwhile upgrading to XMPP where available, without even having to think about the transportation protocol. That helps people gradually migrate to XMPP.

**Comment by licaon-kter** [comment]
@jcrben So let's throw XMPP over TCP over SMS when SMS is ` emcumbered and unstable` let alone suspect to hijack and MITM? :smiley:

**Comment by jcrben** [comment]
I'm not really following. I'm not super familiar with the protocols involved, but the reality is that there are currently *zero* people in my life who want me to hit them up with XMPP.

Conceptually, the app I have in mind would figure out if a contact has an app which supports XMPP (for example, they're using the same app that I am), and send it over XMPP in that case. Otherwise SMS.

At that point, all you have to focus on is making an app with amazing UX and we begin a gradual adoption of XMPP more broadly.

Sadly, right now it looks like proprietary messaging protocols will dominate the world for the foreseeable future.

**Comment by licaon-kter** [comment]
You don't "hit them up with XMPP" because they don't "hit up with SS7 or Axolot or...", no, you just introduce them to *Conversations*, tell them to enter a new account, `nick@my-server-choice.im`, check register, and then they tell you their ID. Done. This works....

**Comment by jcrben** [comment]
I've actually tried to get friends to use an app just to talk to me and only me. It's never worked for me - congratz on your success. 

Ultimately we can just agree to disagree. I think the approach you've outlined is why XMPP is widely viewed as dead (see https://blog.fastmail.com/2015/11/16/shutting-down-our-xmpp-chat-service/).

**Comment by licaon-kter** [comment]
> I've actually tried to get friends to use an app just to talk to me and only me

This applies both ways, you should install Whatsapp/Telegram/Wire/Signal for the same reason?

Your article:

> (such as WhatsApp, Facebook Messenger, iMessage, etc.), or niche privacy focused platforms (such as Telegram, Whisper etc.).

So following that logic, Facebook Messenger/Telegram/Whisper should close, right? We have Whatsapp and iMessage... Did you see that `etc.` at the end?

Oh come on, the federation `dream has evaporated` then you look at https://conversations.im/compliance/ and you see 95 servers (which have a report, these are not all!), where 62 are (almost) up to date on features, yeah, dead... see... How many connected servers ( https://network.trashserver.net/ ) ?

Anyway, in the meantime (2-3 years!!!) Conversations came, ejabberd/prosody/other servers have constant releases, new features, Chat Secure/Zom/Monal grow slowly on iOS, Xabber/Yaxim on Android.

Should I start talking about Matrix now?

**Comment by 0pLuS0** [comment]
@uchchishta how do we use SMS Transport, or can anyone elaborate?

I thought maybe there was an option in Conversations for adding this in, and I've been surfing around, still haven't figured it out.

I'm a Geek, but all my friends and family aren't Geeks that will use Conversations, Noobs/Newbies don't care... I've been at this sort of thing a very long time, and it's never changed, among the clueless...

I want the security, they don't care, so trying to have the best of both worlds is difficult. There needs to be the merging of the two. SMS might not be great, but we need to have this ability for all our non caring friends to chat with.

Also charging for this service, another reason the Newbies aren't going to use Conversations, when they'll tell us that chatting on their iPhone is free, and why do I need to pay for this...

The only way I see this winning bigger, we need a major Snowden Storm of how Providers Store users sms/mms data, maybe then, we can change their minds, or if Conversations, was the default app in Android...

Anyhow, is it easy to add in this SMS transport?

Thanks

**Comment by luke-jr** [comment]
> @luke-jr no, a server service that does that, and only one I know of is Cheogram but I have not used it, so I don't how it works.

@uchchishta That wouldn't use my phone's number or service...

**Comment by 0pLuS0** [comment]
Is MAXS Transport the idea here for SMS with Conversations?

https://play.google.com/store/apps/details?id=org.projectmaxs.transport.xmpp

**Comment by 0pLuS0** [comment]
Is MAXS Transport the idea here for SMS with Conversations?

https://play.google.com/store/apps/details?id=org.projectmaxs.transport.xmpp

Cheogram & JMP;

https://jmp.chat/

We need to have these services and their number and this adds the SMS Transport, by going through this service/telephone number to be able to send/receive sms?

No offense to anyone, I've known Jabber/XMPP since it's been around, but I've never used it, and these sites, look so shady... :(

**Comment by 0pLuS0** [comment]
Is MAXS Transport the idea here for SMS with Conversations?

https://play.google.com/store/apps/details?id=org.projectmaxs.transport.xmpp
https://play.google.com/store/apps/details?id=org.projectmaxs.module.smssend
https://play.google.com/store/apps/details?id=org.projectmaxs.module.smsread
https://play.google.com/store/apps/details?id=org.projectmaxs.module.smswrite

Cheogram & JMP;

https://jmp.chat/

We need to have these services and their number and this adds the SMS Transport, by going through this service/telephone number to be able to send/receive sms?

No offense to anyone, I've known Jabber/XMPP since it's been around, but I've never used it, and these sites, look so shady... :(
