### ISSUE TITLE
Request: connection status

### ISSUE THREAD

**Issue by rqcy** [siacs/Conversations#1936]
Hi, it could be useful to have an indication, if Conversations is connected to the server.

Idea: the top bar could turn gray, if there's no connection to the server, green (currently implemented) otherwise.

Thanks!

**Comment by licaon-kter** [comment]
That "send button shows status" settings option covers this, maybe.

**Comment by rqcy** [comment]
> That "send button shows status" settings option covers this, maybe.

Partially, because it's hard to distinguish between “not connected to
the server” and “contact offline.”

**Comment by iNPUTmice** [comment]
Being connected is the default. Conversations will tell you when it is **not** connected.

**Comment by licaon-kter** [comment]
Ok, so I though a bit more about this since I'm facing an issue, network gets cut off pretty aggressive in my current config.

Anyway, the options right now in Conversations are:
* account disabled -> small notification "account disabled: activate"
* account enabled and connected+contact offline -> black send button
* account enabled and connected+contact busy -> orange send button
* account enabled and connected+contact connected -> green send button

But in my case, given the network/Conversation reconnection on screen on, I get another state:
* account enable BUT NOT connected -> black send button just like when actually connected (!?)

So I would like another small notification like when account is disabled, one that says something in the lines: `account reconnecting in progress` while it's `reconnecting`, `security error`, `could not connect` and what ever else is actually doing during a re-connect.
