### ISSUE TITLE
[Feature request] online status in main screen

### ISSUE THREAD

**Issue by mglinux** [siacs/Conversations#1937]
#### General information

* **Version:** eg 1.13.3
* **Device:** eg Samsung Galaxy S5
* **Android Version:** eg Android 6.01 Cyanogenmod
* **Server name:** self hosted
* **Server software:** prosody
* **Installed server modules:** eg Stream Managment, CSI, MAM
* **Conversations source:** PlayStore, F-Droid

Hi!

A quick overview like different colors or a small text/tag with "online" in the main screen would be nice. Right now we have to open each contact and look at details or at least the green arrow :-)

Thanks for this great app!

**Comment by thundergreen** [comment]
+1 would be highly appreciated

**Comment by iNPUTmice** [comment]
It's a design decision not to focus on presence.

**Comment by dnut** [comment]
Not sure how I missed this issue. Maybe it was closed already when I posted mine.

Anyway, sorry to say, but this just sounds like poor design. I could understand if you said you had limited development resources, but design? I don't buy it. How does this benefit anyone? Why have any way to detect presence at all if it doesn't matter?

If we look at Facebook, as much of a privacy nightmare as it is, they have possibly the best instant messaging UX. As forward thinking as they are, they still keep this core feature. People want to know who's available.

**Comment by vanitasvitae** [comment]
You can see, whether the user is online by opening a chat. If the send button is green the user is online, otherwise he/she is not.

**Comment by mglinux** [comment]
But that's not very comfortable. An option to enable/disable would be great. It's not a big deal but it would be useful though

**Comment by guennie** [comment]
+1

**Comment by strb** [comment]
You might try reading the [FAQ entry](https://github.com/siacs/Conversations#where-can-i-see-the-status-of-my-contacts-how-can-i-set-a-status-or-priority) about this topic. Or, you know, [any](https://github.com/siacs/Conversations/issues/46) of [these](https://github.com/siacs/Conversations/issues/1585) [other](https://github.com/siacs/Conversations/issues/1197) [issues](https://github.com/siacs/Conversations/issues/61) on the topic.

**Comment by dnut** [comment]
The FAQ entry doesn't even address the whole point of statuses. "In the past status has been used to judge the likelihood of whether or not your messages are being read." I'm sure someone has used them for that before, but that is not now and never was the primary purpose. The purpose is to look at the list and quickly discover who is actually available to chat, not to discover who is likely to eventually have the ability to read a message.

One shouldn't have to message every single person to discover who is available. I don't know about you, but if I have 100 people on my buddy list, and only ten are likely to respond right away, I would really appreciate having status indicators that make it obvious who those ten people are. Users want to be able to click on a name, knowing they can say "hi" and have a high probability of getting a "hi" back right away. That's why it's called "instant" messaging. Without a status indicator, it starts to resemble e-mail.

Furthermore, the whole argument about carbons is nonsensical. If anything, statuses were less useful for the proposed purpose before carbons because someone could be online and still not receive the message. Now that carbons guarantees that simply being online means you will receive the message, status is more meaningful for this purpose.

What really boggles my mind is why we have status indicators in conversations. Don't get me wrong, I appreciate that there is at least some way to detect status, but it is totally inconsistent with the logic used to banish indicators from the conversation list. If we look at every possible implementation of status indicators and try to identify the one most likely to be used to detect if a message will be sent successfully, and try to identify the one least likely to be used for any other purpose, wouldn't that be turning the send button into a status indicator? Wouldn't moving the status indicator outside of the conversation make it less oriented towards the use developers consider useless? Even according to the developers' logic, the current implementation is less sensible than an implementation that has indicators in the conversation list.

**Comment by strb** [comment]
> The purpose is to look at the list and quickly discover who is actually available to chat

Status doesn't reliably do that in a mobile context though. I might be on the subway where I have no reception so I'd be "offline", even though I'll be back on in a few minutes when I get off. Similarly, I might have just turned off my phone for a meeting, but due to stream management timeouts, I'm still "online" though I won't be reachable for a few hours. Status *sucks* for mobile.

> I don't know about you, but if I have 100 people on my buddy list, and only ten are likely to respond right away, I would really appreciate having status indicators that make it obvious who those ten people are. 

If this is your main use-case, I guess Conversations just isn't for you, sorry.

> What really boggles my mind is why we have status indicators in conversations. 

Because people kept complaining about it, ignoring the fact that it doesn't fit into the project's vision. Coloring the send indicator is a low-effort, mostly unobtrusive solution, mainly intended to appease people that "can't live without status". Same principle as the "delivered" tick mark. Yes, it's useless, and you shouldn't need it so it probably shouldn't be there, but some people are really paranoid about this stuff, and this is an easy way we can make them happy without doing too much harm.

Status in the conversation list is different. It's worse than unnecessary, it's actively harmful and misleading. In situations like I mentioned above, it will lead the user to believe things that aren't true. 

Sure, it would be nice to have a decent indicator for the problem you're describing. We just don't believe status is the solution. We would rather have nothing at all, than use a poor metric that's misleading for the use-case of most of our users (i.e. heavy mobile use). This is also why the "last seen" indicator was removed somewhat recently. It just didn't really indicate what people thought it did, making it harmful and confusing.

Understand that Conversations has a set of goals and priorities that might not align with yours. If you just want pidgin for android, you're better off using a different app. And as always, feel free to fork if you think the direction of this project is misguided and you can do a better job (no snark intended). You're also always welcome to join our MUC at `conversations@conference.siacs.eu` if you're looking for further discussion. But please refrain from continuing to beat this long dead horse on our issue tracker. 

I'm locking this thread, because there is nothing more to say on this point.
