### ISSUE TITLE
Add Setting to force end-to-end-encryption to make Conversations foolproofed

### ISSUE THREAD

**Issue by lupusmeatus** [siacs/Conversations#1944]
To allow wide-spreaded usage of Conversations without getting the reputation of being unsafe, there should be a setting to disable unencrypted communication.

#### Steps to reproduce

Try to use conversation with some non-IT-people. Install conversation and set it up, so that they can only communicate encrypted.

#### Expected result
This should be really easy to  do.

What do you see instead?
One of them disabled PGP-Encryption and sent data unencrypted and even published some really sensitive data, due to https://github.com/siacs/Conversations/issues/1943

#### General information

* **Version:** eg 1.13.3
* **Conversations source:** F-Droid

**Comment by iNPUTmice** [comment]
Conversations doesn't try to force e2e on its users. If you want to do this with your users feel free to distribute your own build that disables plain text. You can very easily do this with a compile time flag at [Config.java](https://github.com/siacs/Conversations/blob/master/src/main/java/eu/siacs/conversations/Config.java#L15).

Personally I think you are way better off just using your own server instead of trying to get "non-IT-people" to use PGP but that's just me.
