### ISSUE TITLE
Purge archived messages by expire or manually

### ISSUE THREAD

**Issue by mollat** [siacs/Conversations#1961]
Hi everyone,
just fiddling around with conversations and omemo, and it looks like the very last word in instant messaging... So far so good.

But did I get something wrong or is it just not possible to clear the message archive?

#### General information
* **Version:** 1.13.6
* **Device:** several
* **Android Version:** CM 11, 12
* **Server name:** conversations.im
* **Conversations source:** self build (latest HEAD)

#### Steps to reproduce
1. go to conversation
2. menu -> clear history (I hope I translate the menu items quite right into english... ;)
3. push checkbox 'end conversation'
4. push 'clear messages'
5. Start a new conversation with the chat partner
6. push 'load messages'

#### Expected result
I would love to see: 'nothing'... ;)
But I see all old messages again. So obviously it is only the local cache that was cleared.

For some security purpose I would like to delete chats history now and then, or have an automatic expiry window (e.g. 2 Weeks) to do this. I found some 'expire' option in XEP-0136, but before I read further (specs and source), does anyone know how i can achieve this with the existing state? Are there external possibilities? (Set some server options for my account) or is there any 3rd pary tool around that would clean message archiving from XMPP accounts?

Thanks for reading, Andreas

**Comment by strb** [comment]
What you are seeing are logs retrieved from the archive on the server. Conversations makes use of [XEP-0313: Message Archive  Management](http://xmpp.org/extensions/attic/xep-0313-0.2.html). Expiration of messages in the archive is implementation-defined, and AFAIK no implementation supports users setting their own expiration times. In prosody at least, this is a server configuration option that applies globally.

Since OMEMO messages can not be decrypted again (the ephemeral keys are deleted after use), you shouldn't be seeing this behavior in OMEMO-encrypted chats. The messages are still there, mind you, but they can't be decrypted anymore, because the keys are gone, so they won't be displayed.

**Comment by mollat** [comment]
Thank you for clarifying this! So there is no security issue for me anymore.

However - looks like I have to live with all my ugly unencrypted test messages until the expiration timeout of conversations.im will get me rid of them... ;)

**Comment by iNPUTmice** [comment]
> However - looks like I have to live with all my ugly unencrypted test messages until the expiration timeout of conversations.im will get me rid of them... ;)

Or you could simply not hit the 'load messages' button.

**Comment by mollat** [comment]
This is - of course - the preferred solution. However - I set up a group of phones/accounts for a project of colleagues and customers. But when I tell them not to push the 'load messages' button, not to see all my silly test messages, guess what they will do... ;)

Would be nice to 'reset' accounts somehow, but in the end it really does not mind.
