### ISSUE TITLE
Extended evaluation on Play Store

### ISSUE THREAD

**Issue by pltxtra** [siacs/Conversations#1966]
Conversations seems like a promising XMPP client - however, my guess is that I am not the only one who hesitates to install this since it costs money. Initially Whatsapp for example was free for the first year, then they charged $1 per year after that. Couldn't Conversations use a similar model? Free for a year, then a recurring yearly fee? If the yearly fee is $1 then a longtime user would yield a higher return than a fixed one time fee, but at the same time it would be a simpler choice to install the first time.

I think this would create more paying users in the long run... As it is now I will probably just build my own APK and use that... It's easy enough for me to do, and I don't have to take the risk of paying for something I'm not sure I will like.

**Comment by iNPUTmice** [comment]
When I buy a coffee at Starbucks (which is even more expensive than Conversations at the PlayStore) I don't get to have the first sip for free either.

> Couldn't Conversations use a similar model? Free for a year, then a recurring yearly fee?

No because there is no way to make Conversations stop working after your subscription runs out.

> As it is now I will probably just build my own APK and use that

Have fun. If after a dozen or so updates you are tired of building it every other week the PlayStore version is waiting.

**Comment by pltxtra** [comment]
Well, it's automatically built every time you make a release. So no hassle
for me. I make release automation for a living.

I was merely making a suggestion for you to increase the amount of users.
For me personally I will pay if it's good, no question there.. I guess
you're not open for suggestions. Your loss.

**Comment by d9h02f** [comment]
With the introduction of the paid conversations.im account, I do think it's strange you still have to pay for the Conversations client as well.

**Comment by iNPUTmice** [comment]
@d9h02f These are completely separate products. With an account on conversations.im you are paying for the operation of the server. With buying the App on the PlayStore you are at least partially supporting the development of the App. There is no cross financing going on. The PlayStore sales are not supporting the server (they couldn't because the do not even cover the development) and the server fee is not supporting the app development.

**Comment by d9h02f** [comment]
I know, but someone who just wants to talk to their friends doesn't know and doesn't care about the distinction.
