### ISSUE TITLE
XEP-0144: Roster Item Exchange

### ISSUE THREAD

**Issue by jkufner** [siacs/Conversations#1967]
When using Facebook transport (purple-facebook & Spectrum), it adds new contacts to roster using [XEP-0144: Roster Item Exchange](https://xmpp.org/extensions/xep-0144.html). Gajim supports this and displays dialog to confirm adding new contacts. But Conversations ignores this completely and when my Gajim is not online, I see only numeric user IDs instead of their names and there is no easy way to identify the contacts.

The XEP-0144 provides also a way to update and delete contact, but adding a new contact is the important feature.

The expected behavior is to show a dialog to confirm adding the new contacts and (if confirmed) add them to roster. There can be a lot of contacts at once so a list of contacts should be displayed. The new contacts should be automatically authorized.

**Comment by iNPUTmice** [comment]
Approving every change in the roster manually sounds very clunky. IMHO spectrum should either support XEP-0321: Remote Roster Management or become a privileged component with XEP-0355 and XEP-0356. Neither of them require support in the client.

**Comment by kousu** [comment]
[XEP 0321](https://xmpp.org/extensions/xep-0321.html) sounds like the right solution because it modifies the roster on-server, where the roster lives, but no one has implemented it: especially neither [prosody](http://prosody.im/doc/xeplist) (and they're [not looking to])(https://prosody.im/issues/list?sort=&q=xep-0355) nor [ejabberd](https://www.process-one.net/en/ejabberd/protocols/), so [XEP 0144](http://xmpp.org/extensions/xep-0144.html) is the only option gateway's have got.

The way Gajim handles this is that, upon each batch of JIDs received, a dialog with a ListBox with all of them listed appears and you can approve or disapprove all of them at once. Approving each individually is super annoying but a batch method with a single button is not so bad.

Also, I want to point out that http://xmpp.org/extensions/xep-0100.html#rosters + http://xmpp.org/extensions/xep-0144.html#entities-gateway together spec that Conversations could have a kind of trusted-transports dialog "Allow this transport to add contacts to my roster" which is the only UI you would have to expose the user to:

> the receiving application SHOULD process such roster item suggestions.
> Such processing MAY occur automatically (i.e., without the user's approval
> of each roster item or batch of roster items) if and only if the receiving
> application has explicitly informed the user that it will automatically process
> roster items from the gateway


The other option is to insist that people who want to use transports with Conversations need to also use them with Gajim every so often in order to sync their remote roster. This sounds like what @jkufner did, but Gajim didn't save the user aliases to their roster for some reason, or Conversations is ignoring the aliases it saved. That's a different problem, and should go beyond RIE. Can you tell us which it is, @jkufner ?

**Comment by Zash** [comment]
There's a 3rd party module for [XEP-0321](https://modules.prosody.im/xeps.html#xep0321): [mod_remote_roster](https://modules.prosody.im/mod_remote_roster.html).

**Comment by jkufner** [comment]
@kousu When Gajim is online, it displays roster update and waits for user to confirm. In this case, everything is fine. But when Gajim is not online, the roster update is ignored and plain authorization requests are shown later, because Conversations does not deal with it and therefore the user aliases are not populated. Gajim simply does not receive the roster update later, because it is not repeated ever.

**Comment by kousu** [comment]
@Zash, I missed that! Thank you! I withdraw my complaints entirely.
