### ISSUE TITLE
Closing conversations by swiping is too easy. No way to recover.

### ISSUE THREAD

**Issue by gerg5c42g542g2c54g52c** [siacs/Conversations#1997]
When in the conversations list (swipe right), when I swipe on any conversation it instantly gets removed, the "Conversation closed" message appears for a few seconds with an undo option. When one misses that (and that's super easy to do by accident), the conversation is gone, that's pretty bad.

There should either be an access to closed conversations with an ability to view and restore them or a confirmation box lessening the chance of accidental deletion (but not preventing it, it's just one tap, so there should be a way to recover). I'd question myself if closing conversations has any point at all, the only thing I can think of is pedants and people with that syndrome where all the pens have to lay down equally straight.

**Comment by d9h02f** [comment]
If you go to the contacts list again and open a conversation with that contact again, all your messages will still be there.

**Comment by conrad-heimbold** [comment]
1. Your conversation is not deleted, see poster above. It gets just removed from the "current conversations"-list, so to say archived. 
2. That's the way to do it on Android. You can find LOTS of other examples, where it is done the same way: Gmail (if I remember correctly), SMS-App, ApkTrack. I am using the archiving functionality a lot. 

I think, the problem lies rather somewhere else: 
That bar on the right side (showing only parts of the last conversation) can lead to problems when swiping to the left - if you do it too much to the left, you do not end up in the last conversation; but instead accidentally archive a conversation. 
So for this kind of problem, there are two possible solutions: 
(A) Disable archiving when swiping a conversation to the left (rather a workaround and quick fix). 
(B) Get rid of the conversation preview (which is also ugly, IMHO, on small-screen devices like smartphones). You can still open the last conversation by just tapping on it in the list. 
Instead, swiping to the right inside of a conversation could bring you back to the conversation overview, like in Telegram. 

But for that problem, having a separate issue is better, too much discussion from me already, IMHO.  

So is (A) the solution you're looking for? If no, please open another issue for solution (B) and close this issue.

**Comment by mimi89999** [comment]
I have such a device... It feels natural to swipe to the left, but it is difficult to grab the conversation several millimeters from the edge of the screen.

**Comment by herbsmn** [comment]
Closing conversations by swiping is too easy, imho. Yes, you can get the conversation back by opening up a conversation with that contact again, but I have had times when it all happened so fast that I wasn't able to see which conversation it was with before it was sucked into the memory hole. The name of the contact is not visible at all after an accidental left swipe. All that can be seen is the option to click the "undo" button and it is only up for a second or so. This problem is exacerbated by the fact that I use a Replicant phone and all the graphics are rendered on the CPU, which results in screen lag and makes it less likely for me to hit the "undo" button in time. It would be great to offer an option in the settings or expert settings to make this left swipe thing optional. Users could always just go into the conversation and then hit the setting button and hide the conversation that way. It also just seems odd to not have a place where you can go view all the archived conversations. idk, this has definitely been a problem for me and just wanted to post my experiences on the matter.
