### ISSUE TITLE
Provide a list of recommended clients for other platforms

### ISSUE THREAD

**Issue by medikoo** [siacs/Conversations#2048]
It would be great to have some recommendation list from you, stating which client is best to use on other (non Android) platforms.

Which iOS, OSX or Windows client would play best if other user uses Conversations on Android?
- Which is closest in supporting same functionalities as Conversations (e.g. file transfers)
- Which is closest in UX to Conversations.

Use case: My wife has iOS and I'ld like to speak to her via XMPP most convient way :)

If it's not the place to report such request, please kindly guide me where should I post it (?)

**Comment by d9h02f** [comment]
Monal is the XMPP client of choice for iOS, and there is an OSX version as well which looks and functions essentially the same. For Windows or GNU/Linux nothing comes close. There is Gajim which technically has the most functionality, but all the important things are hidden in endless menus and it also just looks terrible. That said, if you have to use something, use Gajim, because everything else is way worse.

**Comment by medikoo** [comment]
@d9h02f great thanks for this recommendations I'll look into those apps

**Comment by andersruneson** [comment]
Spelling mistake:
"Plugins can be installed from *withhin* the app."

**Comment by blevant** [comment]
monal is feature impaired

**Comment by blevant** [comment]
ios: chatsecure 
osx: wait for gajim port
windows:  gajim, jitsi, psi+ [dev ed]
