### ISSUE TITLE
Questioning three defaults

### ISSUE THREAD

**Issue by STPKITT** [siacs/Conversations#2054]
#### General information

* **Version:** 1.14.4
* **Device:** Samsung Galaxy S III mini
* **Android Version:** Android 5.1.1 Cyanogenmod
* **Server name:** jabber.at

Under "Konten verwalten" -> "Konto-Details" why does the user have to click menu and then "Server-Info" to show the corresponding information?

In Conversations's settings there are two options where I'd like to question the default value or what thought is behind the default:
- ""Senden"-Schaltfläche zeigt Online-Status": default is disabled
- "Empfangsbestätigungen anfragen": default is disabled

**Comment by iNPUTmice** [comment]
I'm fine with these settings.
We don't want to emphasis the presence because presence is meaningless especially when using push (on iOS clients for example)
The users shouldn't be bothered with the details of what their server supports or not. Maybe at some point in the future we'll display some aggregated score or something.

**Comment by STPKITT** [comment]
""Senden"-Schaltfläche zeigt Online-Status": ok, but where is the disadvantage of enabling it by default?

I strongly disagree about the users bothering with server supported features, as some of them are essential for Conversations' advertised features to work. If all servers would be the same or XMPP would be a centralized system ok, but both are not the reality.
Otherwise one could ask why the GUI offers the possibility to show supported XEPs at all!?!
