### ISSUE TITLE
OMEMO keys should show key creation or key received dates

### ISSUE THREAD

**Issue by knoy** [siacs/Conversations#2076]
Right now managing multiple OMEMO keys is very difficult without memorizing fingerprints. It would be much easier for novice users if there was a date displayed (either the date the key was created or the date the key was received by Conversations) next to the key to ease in verifcation/management. This seems like a basic useability/security issue that could be fixed simply

**Comment by DrAzraelTod** [comment]
a last-seen-date would be further useful…

i've got the situation where i've reset my phone (or installed conversations on different devices) a couple of times and contacts now have a list of ~10 OMEMO-Keys, where nobody knows what is current and what's no longer needed.

If someone would just connect under my name and insert a new key, nobody would even bother to check anymore. At this point security dropped to pretty much nothing. (Well, you'd need my jabber-password to connect, to create another key first, so it's still a bit better than just network-encryption)

**Comment by lovetox** [comment]
read again
if **you** generate a lot of keys its **your** responsibility to regularly hit the "clear devices" button
not your contacts.

what information do you derive from the date you got the key?

**Comment by DrAzraelTod** [comment]
what?

Yes, I should be responsible for removing my old, unused keys, of course.

But what does that change?

It doesn't matter if it's me or anybody else who SHOULD do this. When clearing the keys there is some hint needed what keys can or cannot be deleted. Currently there is none.
All i see is "current key for this device" and a list with other keys.
If i'd want to clear those, i'd have to run to every device, check what key responds to what device and find out what keys I no longer find. I have >3 Devices that are connected to my account. What if I forget one?

Showing a date of "last seen" would solve this. A date of creation or "first seen" could help further.

And what if I don't do this? Then I suffer no problems, but all my contacts must decide what keys are current and what aren't. Every fucking person in my list gets a List with >10 keys and has to decide what key might be the current one. THERE ISN'T EVEN A DISTINCTION WHAT CLIENTS ARE CURRENTLY ONLINE.

That's just plainly unusable.

**Comment by iNPUTmice** [comment]
> When clearing the keys there is some hint needed what keys can or cannot be deleted. Currently there is none.

When you hit the clear devices menu entry unused keys appear gray out / inactive.

**Comment by iNPUTmice** [comment]
I have the feeling that people don't actually use the clear devices button. Maybe we should somehow make it more visible.

**Comment by DrAzraelTod** [comment]
> When you hit the clear devices menu entry unused keys appear gray out / inactive.

you get the difference between "all other devices" and "the devices i no longer use"?

**Comment by lovetox** [comment]
you misunderstand how "clear devices" works.

there is nothing you can choose, clear devices means that the list of devices/keys on your server (not your device) is set to zero.
this is published to all of your contacts and yourself + your other devices.

if a device receives a device/key list of zero, it sets all keys to inactive.
if an active device of yourself becomes a device/key list of zero, it knows this is wrong, and adds itself to the server list again, everyone of your active devices does this.

so you end up with an up to date server list of only devices that are active, devices that are not in use cant add themself to the server list.
this all happens of course in seconds.

**Comment by DrAzraelTod** [comment]
> if an active device of yourself becomes a device/key list of zero, it knows this is wrong, and adds itself to the server list again, everyone of your active devices does this.

I was indeed missing that part. So now that makes a lot more sense. Thanks

But still, for my (pretty uncommon) usecase, this still kinda fails, since most of my devices are offline most of the time. So any messages recieved until $device connects the next time are unreadable to this device?

And what about people trusting that keys? How does the following scenario work out?

* A knows/trusts keys 1,2 and 3 of B
* B selects "clear devices" from the app with key 1 -> keys 2/3 are disabled
* A sees this
* B connects with second device with key 3
* A sees this

does A still trust key 3?

**Comment by knoy** [comment]
This is getting pretty sidetracked from the original point. Regardless of how "clear devices" works that doesn't remove the usefulness of a date for keys, especially a 'first seen' date.

@lovetox I think you're misunderstanding the use case. You're assuming all your contacts will act like good citizens and clear their keys regularly so that you dont have to manage 10 different keys. How ever no matter how well you behave, you will inevitably get people who won't do this because they're technically incompetent, can't be bothered, etc. The entire point of verification is the user should be able to choose which keys to trust without having to rely on external parties

**Comment by lovetox** [comment]
> The entire point of verification is the user should be able to choose which keys to trust without having to rely on external parties

are you serious? The Point of verification is that you and an external party (your contact) verify the fingerprint over **another** channel. Thats the **only** way it should happen, everything else is you just trusting in whatever is given to you and has nothing to do with a save verification.

So you are the best example of why such meta data never should be implemented, because you think you can derive from such metadata if you can trust a key or not, instead of doing an actual verification with the contact.

So until now the only usecase i see is, that you just dont want to ask your contact if he still uses a key. But that process is called verification.

And if you cant rely on your contact telling you if a key is not in use anymore or stolen or whatever, then encryption is only a gimmick, nothing you could ever rely on.

what is true is that keys that are not active for a certain period of time could be set inactive automatically without userinteraction. to my knowledge this is planned in the future.

@DrAzraelTod the second the old device with the inactive key comes online, the key is set active again, i dont know if conversations would reprompt a verification, i think it would not. the key would be trusted because you verified it.

if you truly want to ban a key forever you have to click on it and click delete key, you cant make this undone, the key can never be active again, only if you delete your account from conversations and readd it. this would trigger a new key generation for yourself, which all contacts would have to verify again. Deleting a key is only if you are sure the device can never come online again, or you never want to receive messages from it.

**Comment by DrAzraelTod** [comment]
> So until now the only usecase i see is, that you just dont want to ask your contact if he still uses a key. But that process is called verification.

good point, you might be right here

i still would find it usefull to remove from MY OWN keys what has been unused for some time. But you could use the same argument here as "you should check your own keys" (although i find it less convincing for that)

**Comment by lovetox** [comment]
removing from where? from your own device? you can do that, just click on it and click delete key, then its gone.

**Comment by DrAzraelTod** [comment]
> removing from where? from your own device? you can do that, just click on it and click delete key, then its gone.

yes, and (as stated before) i've still got a list of >10 keys in front of me, that i'd need to check on every device weather it's still used or not. A alphanumeric key isn't really good memorable, so a timestamp, or even simpler, just a freetext-label that i can fill myself in (similar to the authorized_keys file in /.ssh), would help to discern what key is what device.

And yes, as @iNPUTmice already said, that's not the currently desired way of cleaning that up. (see: disable all, let it sort itself out) - i still think it might be a valid feature

**Comment by lovetox** [comment]
i really dont get it, if you hit "clear device" you dont have to trust each key anymore on another device, only the active ones

**Comment by lovetox** [comment]
Also what you are saying is, you dont want to trust a long key, you want to trust a label, but that is not possible, a label like "Home" can have every encryption key behind it, a cryptographic fingerprint can only have one single key behind it, that is the whole point why its save if you verify it.

**Comment by knoy** [comment]
You guys can argue till you're red in the face over how making something worse and less useable will somehow make it more secure. At the end of the day, a 'first seen' date correctly implemented by the device can't be faked and helps massively with power users who have hundreds of contacts. It's ridiculous to assume all your contacts will clear their keys regularly, or to assume Conversations will be the only OMEMO client anyone will communicate with.

>are you serious? The Point of verification is that you and an external party (your contact) verify the fingerprint over another channel. Thats the only way it should happen, everything else is you just trusting in whatever is given to you and has nothing to do with a save verification.

@lovetox that's actually not correct. SMP uses in-band verification. TOFU is another similar key verification system that doesn't require out of band use. ZRTP also verifies keys using the content. More importantly I think you're missing the point entirely. The point is you don't use the dates as your ONLY method of verification, just as an aide when you have no other information available, as well as an easy way to see whats NOT sane.

This is getting sidetracked . "Clear devices" and dates on keys are not mutually incompatible and it makes no sense to label them redundant, they do completely different things.

**Comment by DrAzraelTod** [comment]
> you dont want to trust a long key, you want to trust a label

you misunderstood what i wrote

I want to be able to label my keys, so i can remember what key is what.
This can be done completely local.
So i.e. I could take my phone, go to each other device, check if keys are the same and if they are, then i could write "Phone B foo XYZ" behind the key in the UI of my primary device.

So if i'll need to go over those again in 1-2 years i'll still remember what key was on what device.

It all boils down to: please give me ANY chance of managing the keys myself (other than writing them on a piece of paper to remember that stuff externally)

**Comment by lovetox** [comment]
the only use case i see as i said like 10 posts above is to untrust not used keys - but this will happen automatically in the future so you dont have to do this.

**Comment by iNPUTmice** [comment]
All that arguing about the security aspects of showing a date has kept us from seeing the real issue here.

> contacts now have a list of ~10 OMEMO-Keys, where nobody knows what is current and what's no longer needed.

This is the real problem. Nobody has 10 legitimate devices. (Speaking about physical devices. Not keys.) I think most people have two devices: Desktop and smartphone. Some few people might only have one and a few people might occasionally use a tablet.

As @lovetox stated the solution to accumulating ~10 keys over time is to hit 'Clear devices' every time you get rid of an old device. (Or do a reinstall.) However:

> You're assuming all your contacts will act like good citizens and clear their keys regularly so that you dont have to manage 10 different keys.

The solution to this is not to implement work-arounds for a user to *maybe* make it a little bit easier to trust 10 keys (It's never gonna be easy.) but to fix the actual problem: The user is not clicking 'Clear devices'.

In the future Conversations will try to a) make the clear devices button more accessible b) automate that process.

Furthermore I think it should be said that the problem only arises if the user keeps reflashing their ROM and/or keeps reinstalling Conversations. Normal users don't do this. Looking at the number of keys of my none-developer friends, I see that they only managed to accumulate about three keys (two in use) over the entire year that OMEMO exists. This is way more manageable then ~10 keys.

I think being in that developer/reflashing/reinstalling world let's us believe that a problem is way more extreme than it really is. If you like reinstalling your ROM you probably have the capabilities to properly backup Conversations and spare your friends from having to verify new keys every other day. (Or if you don't at least hit Clear devices afterwards.) That being said and to repeat my previous statement: Conversations will make the Clear devices button more obvious and also (carefully) try to automate the process.

**Comment by DrAzraelTod** [comment]
> Furthermore I think it should be said that the problem only arises if the user keeps reflashing their ROM and/or keeps reinstalling Conversations. Normal users don't do this.

…or buys a new Device, or factory-resets his phone because it became "unstable" or "unusable". Normal users do such things.

> If you like reinstalling your ROM you probably have the capabilities to properly backup Conversations and spare your friends from having to verify new keys every other day. 

Well, what ways do you mean? I'm pretty sure i've never used any of those apart from stuff that needs root-access and/or was vendor-specific and thus didn't work after switching my phone.

I still don't understand why it should be so hard to give users a way to set (local) labels for own keys, like SSH does it after "=".

**Comment by iNPUTmice** [comment]
> Well, what ways do you mean?

There is a section in the README on how to backup Conversations.

> I still don't understand why it should be so hard to give users a way to set (local) labels for own keys, like SSH does it after "=".

Local labels for own keys is a completely different issue than showing key received dates for remote keys.

**Comment by licaon-kter** [comment]
So an "auto purge keys older than X days" thing?

**Comment by iNPUTmice** [comment]
> So an "auto purge keys older than X days" thing?

Kinda. Purging has nothing to do with it since purging is local only. Instead we would remove a device from the device list announcement after X days of inactivity until that device reannounces itself or sends a message (and thus proving it is still active.)
