### ISSUE TITLE
[Feature] XEP-0085: Chat State Notifications

### ISSUE THREAD

**Issue by kruks23** [siacs/Conversations#210]
Hi,

It would be nice if you implement this xep to notify others when you are typing them and show when they are typing you.

**Comment by dejIO** [comment]
I would like to bump this feature request, especially the `<composing/>` state.

While it's true that the read markers give an indication as to wether someone is paying attention to the conversation or not, those are not sufficient to guarantee a coherent conversation.

When my friends and I are chatting, our messages are scattered about, so that it's difficult to make sense of the conversation. If there were typing notifications, it would allow me to rather wait a few seconds for the other to finish what they want to say.

Elsewhere I have read someone say that this would clutter the interface. This is not the case. I am aware of Threema's implementation (granted, not XMPP) which puts a static "three dots" icon in the upper "menu bar" when someone is typing.

Which is why I think this is an essential feature for one-on-one chats. I'm unaware of how much work it would be to implement this, but I would be very grateful if someone were up to the task and I would also gladly send some coins their way (just write me a PM).

Cheers,

dej

**Comment by iNPUTmice** [comment]
I just started working on this

**Comment by dejIO** [comment]
Awesome, @iNPUTmice! When you announce that it's available for testing I'll see if I can build it and help you test! :)
