### ISSUE TITLE
TLS issue

### ISSUE THREAD

**Issue by drixter** [siacs/Conversations#2118]
#### General information

* **Version:** eg 1.12.2

n/a

* **Device:** eg Google Nexus 5

n/a

* **Android Version:** eg Android 6.0 Stock or Android 5.1 Cyanogenmod

n/a

* **Server name:** eg conversations.im, jabber.at or self hosted

patchcord.be

* **Server software:** ejabberd 16.04 or prosody 0.10 (if known)

ejabberd 16.09 with nginx as proxy

* **Installed server modules:** eg Stream Managment, CSI, MAM

n/a

* **Conversations source:** eg PlayStore, PlayStore Beta Channel, F-Droid, self build (latest HEAD)

n/a

#### Steps to reproduce

With nginx have forced TLS 1.2 with ciphers there is a problem with handshake.

2016/11/13 15:18:58 [info] 1883#1883: *28 SSL_do_handshake() failed (SSL: error:140760FC:SSL routines:SSL23_GET_CLIENT_HELLO:unknown protocol) while SSL handshaking, client: X.X.X.X, server: 0.0.0.0:443

Forced options:
ssl_protocols TLSv1.2;
ssl_prefer_server_ciphers on;
ssl_ciphers ECDH+AESGCM:DH+AESGCM:ECDH+AES256:DH+AES256:ECDH+AES128:DH+AES:ECDH+3DES:DH+3DES:RSA+AESGCM:RSA+AES:RSA+3DES:!aNULL:!MD5:!DSS;

When I disable it, Conversation works ok with http_upload

#### Expected result

Correct work with TLS1.2 and forced ciphers.

What is the expected output? What do you see instead?

Unable to upload file via http_upload

#### Debug output

https://patchcord.be/upload/4a3e9b34615e2e41003905d680f22ca53f736df9/xlvFhvy9AuclubvRs0ELTWnikQQflV7qgAxQOcsU/4fe38b06-75a3-4d14-9db1-30d6f70bc69a.jpg

````
adb logcat -s conversations
````

**Comment by GrimKriegor** [comment]
+1 on Conversations 1.14.9 from F-Droid running on Replicant 4.2

```
D/conversations(26178): send file message
D/conversations(26178): uploading to https://patchcord.be/upload/4a3e9b34615e2e41003905d680f22ca53f736df9/VCOuSQkpgVYunZzDpLHH8JuO2UU3R8P33IZrDVYP/6df2270d-23a0-432f-97d5-0892ebd5e483.jpg
D/conversations(26178): http upload failed SSL handshake aborted: ssl=0x4daf3438: I/O error during system call, Connection reset by peer
```

**Comment by iNPUTmice** [comment]
It would be helpful if you could fill out the full bug report and include
your device and Android version because this is most likely a limitation of
old Android versions.

**Comment by GrimKriegor** [comment]
Replicant/Android 4.2 is quite outdated indeed. Device is a Samsung Galaxy S2 (i9100).

I assume TLS 1.2 support is a system wide "feature", how should I go about testing that?

Results from SSLLabs indicate support for TLS 1.2 at least on Firefox 49.0

![screenshot_2016-11-13-15-36-21](https://cloud.githubusercontent.com/assets/1028205/20246847/9de2c4e4-a9b7-11e6-85ab-a10b069334b2.png)

Thank you for your time, gentlemen.

**Comment by iNPUTmice** [comment]
TLS and ciphers are indeed system wide features. However Firefox is not a
good test because it brings its own TLS stack. However an unmodified
Android should support TLS1.2 in Jelly Bean so my guess would actually be a
missing cipher.
Conversations removes some unsecured ciphers (see the Config.java) but
otherwise leaves all TLS related things to the system.
Please understand that toying around to find the perfect cipher suite might
be a nice hobby but we don't have the time for that.
If you find one cipher that is supported by your operating system but for
some reason excluded and you think that Conversations should not exclude
this please open a specific issue for that.

**Comment by drixter** [comment]
OK

**Comment by GrimKriegor** [comment]
You gentlemen were correct, Replicant 4.2 simply didn't list TLS1.2 as a supported protocol, and since patchcord.be required it the HTTP Upload couldn't happen.

For reference, the solution was simply to hack replicant-4.2/libcore and add TLS1.2 to the default and supported protocol arrays.

```
diff --git a/luni/src/main/java/org/apache/harmony/xnet/provider/jsse/NativeCrypto.java b/luni/src/main/java/org/apache/harmony/xnet/provider/jsse/NativeCrypto.java
index 65373ff..6b7edd3 100644
--- a/luni/src/main/java/org/apache/harmony/xnet/provider/jsse/NativeCrypto.java
+++ b/luni/src/main/java/org/apache/harmony/xnet/provider/jsse/NativeCrypto.java
@@ -463,16 +463,20 @@ public final class NativeCrypto {
     public static native long SSL_clear_options(int ssl, long options);
 
     public static String[] getDefaultProtocols() {
-        return new String[] { SUPPORTED_PROTOCOL_SSLV3,
+        return new String[] {
+                              SUPPORTED_PROTOCOL_TLSV1_2,
+                              SUPPORTED_PROTOCOL_TLSV1_1,
                               SUPPORTED_PROTOCOL_TLSV1,
+                              SUPPORTED_PROTOCOL_SSLV3,
         };
     }
 
     public static String[] getSupportedProtocols() {
-        return new String[] { SUPPORTED_PROTOCOL_SSLV3,
-                              SUPPORTED_PROTOCOL_TLSV1,
-                              SUPPORTED_PROTOCOL_TLSV1_1,
+        return new String[] {
                               SUPPORTED_PROTOCOL_TLSV1_2,
+                              SUPPORTED_PROTOCOL_TLSV1_1,
+                              SUPPORTED_PROTOCOL_TLSV1,
+                              SUPPORTED_PROTOCOL_SSLV3,
         };
     }
```

No idea of the implications of this change, if any of the readers do, please educate me.

Thanks you both for your time and awesome work.
