### ISSUE TITLE
Idea: get transports and features from other messenger apps

### ISSUE THREAD

**Issue by Piruzzolo** [siacs/Conversations#2136]
[Signal](https://github.com/WhisperSystems/Signal-Android) has some good features: 

- WhatsApp-style callings
- Unification with SMS and MMS
- Cool Material Design UI

Telegram has its own, spread over protocol, Secret Chat mode (with message auto-deletion) and BOTS with easy to use APIs.

[Orbit](https://github.com/haadcode/orbit) is an experimantal distributed, serverless, peer-to-peer chat application built on top of [IPFS](https://ipfs.io/) - it really worth reading about IPFS!

So...
===
Their transport protocols could be merged into Conversations, so the user can choose which one to use. This might require a better separation between front-end and back-end code, so the protocols can be snapped-in through a common interface.

Their good features could be merged too! 

Any thoughts?

**Comment by licaon-kter** [comment]
> WhatsApp-style callings

What's that?

> Unification with SMS and MMS

Out of scope

> Cool Material Design UI

You mean other colours? Low priority

> Telegram has its own

And you want them recoded here? Why?

> So...

This is a XMPP client, all these look way out of scope, red this: https://gultsch.de/mission.html

Yes, most users hate having 14 different apps for chat, but this issue is not made here, each app though they could do better than XMPP... do read this to get their thoughts: https://whispersystems.org/blog/the-ecosystem-is-moving/

And read this too after that: https://gultsch.de/xmpp_2016.html

/close this

**Comment by licaon-kter** [comment]
> Telegram - Secret chat mode

OMEMO does this

> Message autodeletion

You mean disable MAM? You can set this already in app.
