### ISSUE TITLE
MUC Messages not appearing in Conversations, though MAM is active

### ISSUE THREAD

**Issue by adoa** [siacs/Conversations#2145]
#### General information

* **Version:** 1.14.9
* **Device:** Fairphone 2
* **Android Version:** Android 5 (or 5.1?)
* **Server name:** self hosted, I am my own server admin
* **Server software:** prosody-trunk (hg:0011889c928f)
* **Installed server modules:** Stream Managment, MAM, plenty more
* **Conversations source:** F-Droid

This does not always happen. Which is why it confuses me.

#### Steps to reproduce

1. Have a MUC room on the server
2. Make it private, moderated and non-anonymous
3. Activate OMEMO
4. Have more people join the room, everyone using Conversations with OMEMO activated for that room – some of them having their account on the same server, some are on different servers.
5. Install Gajim on a desktop (or maybe two) with OMEMO plug-in installed
6. Keep Gajim open non-stop
7. Have Conversations run in foreground
8. Move around town with phone -> lose internet connection and reconnect
9. Write and read messages with the other MUC participants

#### Expected result

I expect the message logs of Conversations on my phone and the one in gajim to be synchronized due to activated MAM, which is default and forced in all MUC rooms.

#### Actual result

What does happen: The Gajim Instances (I actually have two of them) keep on getting all messages. Independent of whether they were online or not while the messages were composed and sent. Conversations does not get all of them. Sometimes it receives messages upon reconnection to the server – and only cross-checking with the log of gajim shows that not all of them arrived.

Whenever the phone has a stable network connection, all messages arrive. Which is reassuring.

#### Confusion

Is this due to improper disconnects, due to the messages not being encrypted for Conversations or due to Conversations not properly accessing the Message Archive of the room? Can I force Conversations to access the Message Archive?

And if yes, how do I start digging into these questions?

#### Cross checks

The MySQL database storing the muc_log has plenty of entries, both status changes and messages. So in principle the MAM works. Also Conversations confirms MAM to be active in that room. The messages in the archive come from all participating devices.

**Comment by iNPUTmice** [comment]
This might be due to prosody MAM not adding the true sender of the message
(the full jid).
In that case it would work if Conversations resumes a stream but would not
work if this is a new connection.
Unencrypted messages should be fine though. It should also be fine if you
host your muc on an ejabberd server.

There might be some other issues like server and client time out of sync
which could play a role.

In general: read the section in the Readme on how to debug Conversations
and how to get the adb logcat output.

**Comment by adoa** [comment]
According to the entries in the MySQL database, the MUC messages are sent "from=room@server/user". What do you mean by "the full JID"?
In these cases, my different clients are identified by room@server/adoa and room@server/Adoa respectively.

Just to make this clear: this problem only occurs in MUC. Normal messages from someuser@someserver to me are fine.

And yeah, now I can read the adb logcat output. I will try to check the next time I reconnect after longer offline time.

But you say that it should not occur if the former connection (or stream?) was properly shut down and not abruptly terminated due to loss of wifi connection? Even though I thought that stream management should take care of these things :-/

**Comment by iNPUTmice** [comment]
> What do you mean by "the full JID"?

MAM has a way to communicate the real JID of the contact instead of only the nick. And we need the real JID to make OMEMO work. But iirc prosody doesn't do this.

> But you say that it should not occur if the former connection (or stream?) was properly shut down and not abruptly terminated due to loss of wifi connection? Even though I thought that stream management should take care of these things :-/

The stream has to be resumed within 5 minutes. Only if it's more then five minutes (or if the app got killed) mam is used.

**Comment by silberzwiebel** [comment]
I do have a similar problem since some months (MUC messages missing in Conversations that appear in gajim). I thought it was only me, because I only used WiFi and no mobile internet on my phone and did not check back (also: it is hard to see that a message did not appear). I also do think it has something to do with loosing connection / reconnection.
I heard, however, a complaint from a user of my private server (also prosody nightly), that faced the same issue while also using mobile internet connection. Since gajim gets all messages, I suggest it is indeed some bug in Conversations (or both prosody and gajim share a bug that results in correct behavior).
I should note that the MUC in question is not encrypted, so imo OMEMO is not the problem here.

**Comment by iNPUTmice** [comment]
@silberzwiebel I'm sorry you are having troubles with Conversations. The issues you are describing are too unspecific for a bug report. I can't make anything of this. Also this is completely unrelated to the issue at hand which seems to be an issue with OMEMO (or more specifically a server that doesn't support OMEMO+MAM.) Please join the conference if you want to get some hints on how to debug this (In Short check the MAM requests conversations actually makes with adb logcat and check if client time matches server time)

Also I'm closing this issue because I do believe this is a server issue.

**Comment by devurandom** [comment]
Was there a bug report against Prosody? I couldn't find an issue in their list, when I just searched.
