### ISSUE TITLE
Add possibility to choose bar code scanner in conversations

### ISSUE THREAD

**Issue by Killerjoe** [siacs/Conversations#2154]
#### General information

* **Version:** 1.15.0
* **Device:** Galaxy Note Edge
* **Android Version:** Android 6.0 Stock
* **Server name:** self hosted
* **Server software:** prosody 0.10
* **Installed server modules:** Stream Managment, CSI, MAM
* **Conversations source:** PlayStore

#### Steps to reproduce

1. Open contact details
2. Long press on contact OMEMO key
3. Click on Barcode scan
4. Popup will appear: Install Barcode Scanner?
    This application requires Barcode Scanner. Would you like to install it?

#### Expected result

I would like to see that it is possible to choose any already installed Barcode/QR Scanner or to download and use any bar or qr code scanner for doing the verification.
I don´t want to use Barcode Scanner, because it wants access to my phone contacts.
It also would be a difficult taks to convince my friends to install this application to verify the qr codes instead of using already installed bar or qr code scanner.

**Comment by licaon-kter** [comment]
Android 6.0 can deny such access, right? I do get the need for that permission, also the app is open source, feel free to check its source code for malicious stuff.

So what other app do you propose?

**Comment by iNPUTmice** [comment]
To my knowledge there is no standardized intent to call the platforms own barcode scanner (There is none in AOSP). Thus this would lead to highly platform depended code that would probably have to be wrapped with the xzing one as fallback. I couldn't do this myself because I don't have access to a mobile phone that comes with a barcode scanner.

However this is a great way for you to participate. It seems to bother you so there is motivation to figure out how to call your platform's barcode scanner and write code that uses it from Conversations.

**Comment by licaon-kter** [comment]
I guess @Killerjoe might just want a hardcoded QR app list included.

**Comment by iNPUTmice** [comment]
> I guess @Killerjoe might just want a hardcoded QR app list included.

We but you need to be able to call the app and extract the result when it returns. And neither the call nor the return parameters are standardized.

**Comment by Killerjoe** [comment]
@licaon-kter
Yes, in Android 6.0 it is possible to restrict the app rights but not everybody has this android version right now.
I was checking some of the barcode scanner apps and honestly don´t know which one would be the best to use (one with limited permissions).
I read the faq from Barcode Scanner and some tests about it and now think that this app should be ok to use but still I would like to see the app without contacts access or a simple barcode scanner included in conversations.

@INPUTmice
I would like to participate in conversations but I currently don´t have the skills to do it.
I just have setup Android Studio and made a clone from conversations.
Additionally I read about building a barcode scanner app and include it in an app but thats not easy for me to realize it without knowledge in this area.

In general I think it would be good to have a simple barcode scanner included in conversations which only do what is needed to verify the contact.
Probably this is not intended to add a simple bar code scanner to conversations but it would make it easier for users to do the verification without the need to install an additional app.

**Comment by licaon-kter** [comment]
Not sure if that's needed, like the issues asking for a full gallery app to see images send.

**Comment by ArchangeGabriel** [comment]
Well, there is a difference between a gallery app and that barcode scanning thing: you don’t have to hardcode any gallery app, since there is a standardized intent.

So, while I have nothing against the used app, I understand and agree that having just the minimal required function of barcode scanning directly in Conversations make sense.

**Comment by revuwa** [comment]
Thanks for referring (my issue: https://github.com/siacs/Conversations/issues/2174) to this already existing, which I didn't noticed.

Like I said, I would also prefer embedding the scan functionality, even if that means that Conversations needs camera permissions, (OTP commit 'Fix Android M (6.0) Camera Runtime Persmission': https://github.com/kckrinke/onetimepad/commit/b12e0036f21bcc798e4326407a8a13de42421c5c).

OTP seems just to import 'com.google.zxing' for internal barcode scanning, (as the https://github.com/kckrinke/onetimepad/blob/master/app/src/main/java/com/onest8/onetimepad/MainActivity.java of the project shows).

Probably Conversations could go the same way?

**Comment by revuwa** [comment]
@iNPUTmice wrote:
> It is undesirable for Conversations to replicate the behavior of other apps and to include permissions for the camera.

* IMHO, in this special case it's (in good conscience) advisable to point to the behavior of another app, which does exactly what I preferred to ask, in an FOSS, (and F-Droid policy conform way). It wasn't meant that you should just steal the code for the laziness...
* I understand that it's hard to be emphatic on adding camera permissions to the IMHO privacy loving Conversations. So what's about a 'Barcode Scanner Plugin' for Conversations, which implements this embedded functionality, as other plugins, like 'Voice Recorder Plugin' do (for other functionalities)?
So users have the full control/choice on which horse they back.

> If there are others Apps that can be invoked by intents and are able to scan Aztec codes I'll happily integrate them. Just point me to documentation of those Intents. The suggested obsqr doesn't seem to have such intents.

I'll see what I can do on the obsqr side, but I'm not too confident to rock somethin' here...

**Comment by IzzySoft** [comment]
There could be a third way. Even now, the app offers two links: one goes to F-Droid (and returns a "no such app found") – and one goes to Playstore (which I want to avoid: I did install conversions via F-Droid for a reason). I have a good QR scanner, and don't want to install another one just to occasionally confirm a code. So here's my suggestion:

* some barcode scanners can save the decoded message. Or let the user place it into the clipboard. Conversions could offer the clipboard for exchange.
* let the user take a photo of the code using the device's camera app (can be opened via intent), then scan and decode the returned image
* keep the option to install that specific app as a fallback

Especially the first item shouldn't need that much code: read the string from clipboard, remove all whitespace, and compare it with the fingerprint sans all whitespace. The second bullet-point would need the QR decoding, but sans camera permission; as the encoding is already there, I guess that wouldn't be that much code either.

**Comment by jplitza** [comment]
Instead of adding support for dozens of barcode scanner apps, the barcode scanner apps should simply support opening the URI that they scanned with the app that wants to handle such URIs. Because what is actually stored in the barcodes that are used to verify OMEMO keys is an `xmpp:`-URI, for which Conversations registers a handler.

Regrettably, the Barcode Scanner app that everybody here wants to get rid of seems to be the only one that offers the option of simply opening that URI with Conversations (although it calls it "Open in Browser"). Obsqr only allows copying the whole string and doesn't detect that it is an URI (even though the barcode type says so) and [QR Scanner](https://f-droid.org/repository/browse/?fdid=com.secuso.privacyFriendlyCodeScanner) only offers to open URIs in browser apps.

And please, don't include this functionality in Conversations. The camera permissions would be unsettling in an app that also has network access, and there's a good reason why taking pictures isn't how barcode scanner apps work.

**Comment by ArchangeGabriel** [comment]
@jplitza This is a good idea. So support is to be fixed mostly within QR scanners, and users wanting to have another one should ask for them to support this.

**Comment by IzzySoft** [comment]
Just wondering: What would happen if the text decoded from the barcode would be shared to Conversions? Would it be able to deal with it accordingly (i.e. pick the right contact if already added and "confirm" it, or add the confirmed contact otherwise)? If so, any barcode scanner able to "share" the decoded scan result should work – and the user, on first call, be informed of the procedere instead of just being told to install a specific scanner (optionally with a check-box for "do not ask again").

**Comment by iNPUTmice** [comment]
> Just wondering: What would happen if the text decoded from the barcode would be shared to Conversions?

Most Barcode scanner will probably have an *open* or *view* button. If you click that button exactly what you'd think will happen. Conversations will open the conversation or a create contact dialog.

**Comment by IzzySoft** [comment]
OK – then at least for me it's a good work-around: instead of invoking the barcode reader from within Conversions, I call it directly and then "share" the result to Conversations. Will try it out at the next chance. Thanks for the fast feedback!
