### ISSUE TITLE
kill/exit app option

### ISSUE THREAD

**Issue by cptMikky** [siacs/Conversations#2185]
Hi,

sometimes Conversations uses way too much battery due to continuous disconnections from a buggy server we have at work (not the issue here).

I want to be able to kill Conversations after I'm done communicating with the server (i.e. when get off work) and now I can only do that by manually force stopping the app from apps menu, which is quite a nuisance.

An "exit app" option in menu would be nice.

 -m.

**Comment by iNPUTmice** [comment]
Just disable the buggy account.
(Manually force stopping the app won't reliably stop it anyway)

**Comment by cptMikky** [comment]
So instead of tapping through settings and app manager once a day I should tap through account settings twice a day? Sorry, not a solution.

**Comment by andersruneson** [comment]
The question is why you want to exit Conversations once per day.
What is the use case.

On 13 Dec 2016 1:30 PM, "cptMikky" <notifications@github.com> wrote:

So instead of tapping through settings and app manager once a day I should
tap through account settings twice a day? Sorry, not a solution.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/siacs/Conversations/issues/2185#issuecomment-266726674>,
or mute the thread

**Comment by cptMikky** [comment]
The use case is described in OP: 

Conversations uses way too much battery while being continuously disconnected from a buggy server. I can't fix the server and I don't need to use Jabber off-hours so the natural solution is to switch Conversations off while I'm not using it.

**Comment by andrewnenakhov** [comment]
Users have to have a way to stop app from running. I have disabled all connected accounts, yet, notification persists and no way to stop it without force killing app. 

I kinda understand developer's desire to have an eternally running app, but it's no good for users not being able to quit.

**Comment by licaon-kter** [comment]
Disable settings/expert/foreground service too.

**Comment by eazrael** [comment]
The reasons why somebody wants to close the app are irrelevant. The current ugly workaround is to kill via the android apps menu which is quite ugly. 

Personally for me, I sometimes don't want to be online, or I am  in reach of another device with a XMPP client. Maybe I am just in a meeting and need my phone but don't want do get the unimportant chatter.
