### ISSUE TITLE
Disappearing messages

### ISSUE THREAD

**Issue by herbsmn** [siacs/Conversations#2223]
This is a feature request to add disappearing messages.

**Comment by licaon-kter** [comment]
So the client app decides to actually respect the timebomb, that's why you posted here? 

Ok, so if I build my own client I can just ignore this and I can keep messages forever.

**Comment by lukes131** [comment]
I don't even understand licaon-kter's response. But I would like to agree with herbsmn that self destructing messages should be an option of users. Its extremely popular feature with everyday people (non technical).

I've heard experts disparage it before.  In my opinion, self destructing messages lets you communicate with people you don't necessarily trust and protects your communication in case the other party loses physical control of there device ie police seize it and start reading your encrypted messages.

All that encryption and security is worthless, if someone can take your phone and start reading your messages. Where I'm from, they just passed laws making it illegal to not provide your passwords to the police...

**Comment by andersruneson** [comment]
This is not something conversations can do alone without a specification.

Turn to the xsf first https://xmpp.org/about/xmpp-standards-foundation.html

If there's a standard for it, it's possible to implement it in
conversations.

On 6 Jan 2017 03:17, "lukes131" <notifications@github.com> wrote:

I don't even understand licaon-kter's response. But I would like to agree
with herbsmn that self destructing messages should be an option of users.
Its extremely popular feature with everyday people (non technical).

I've heard experts disparage it before. In my opinion, self destructing
messages lets you communicate with people you don't necessarily trust and
protects your communication in case the other party loses physical control
of there device ie police seize it and start reading your encrypted
messages.

All that encryption and security is worthless, if someone can take your
phone and start reading your messages. Where I'm from, they just passed
laws making it illegal to not provide your passwords to the police...

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/siacs/Conversations/issues/2223#issuecomment-270814293>,
or mute the thread

**Comment by iNPUTmice** [comment]
We don't want this kind of features in Conversations.

**Comment by herbsmn** [comment]
i'm curious, why is this kind of feature not wanted?

**Comment by lukes131** [comment]
Cause they like keeping records of your conversation and denying user's the ability to choose for themselves,,, What other reasons could there be..  Best to just stick with signal or telegram..

**Comment by BlauerHunger** [comment]
Conversations shouldn't restrict the user, so the only way to implement this feature would be opt-in, which would render it completely useless.

**Comment by mimi89999** [comment]
1. There is an option in Conversation to choose how long you want to keep messages.

2. Disappearing messages give you a false feeling of security because if you don't trust the person you are writing to, how can you trust, that one won't be running a modified version of Conversations, that won't respect the disappearing messages?

**Comment by herbsmn** [comment]
but it is so hip and so cool. all the kids are raving about disappearing messages.

hehe. in all seriousness though, here's how I understand things. Young ppl loved snap chat and other disappearing messages apps because they felt like digital moments were ephemeral. They're faith was misguided though because the unicorny corporations were probs keeping all their data. Those companies did try to make it hard to screen cap or otherwise capture the data that was published by the others using the app, often putting restrictions on the user that violated the user's fundamental software freedoms. It would be inconsistent with their current liberty respecting trajectory to Conversations to do a verification that the recipient isn't capturing the data that the sender is trying to send in an ephemeral way. That is the centralization trajectory, the opposite direction.

That being said, having disappearing messages in the official build of the app would still be cool af. The kids would love it!

**Comment by herbsmn** [comment]
my attempt at a joke: if a corrupt politician wants to send a series of OMEMO+XMPP messages that they know the recipient wants to have erased 1 minutes after reading them, it really does save the recipient a lot of clicks! the amount of click savings that this would provide corrupt politicians Conversations users has to be in the tens of thousands over the next 5 years!

**Comment by herbsmn** [comment]
in all through though, i spent a little while in conversations trying to figure out how to change the setting that determines how long my conversations were kept for but wasn't able to find it. i wasn't very thorough though and likely just completely missed it. i'm curious, is it user specific? in other words, can you choose to keep messages from your sister forever and delete messages from your brother that are over a week old?

**Comment by mimi89999** [comment]
> in all through though, i spent a little while in conversations trying to figure out how to change the setting that determines how long my conversations were kept for but wasn't able to find it. i wasn't very thorough though and likely just completely missed it. i'm curious, is it user specific? in other words, can you choose to keep messages from your sister forever and delete messages from your brother that are over a week old?

It is general for all senders. The setting is in advanced settings.

**Comment by herbsmn** [comment]
i was looking in Expert settings just now and didn't see it. I'll try to see if there is an "advanced settings" spot. what is it called?

**Comment by herbsmn** [comment]
is it "Don't save encrypted messages"? how long does it wait before deleting them? it doesn't say.

**Comment by iNPUTmice** [comment]
> That being said, having disappearing messages in the official build of the app would still be cool af. The kids would love it!

Kids also love sugar but kids don't always get what they want. Thankfully we know better.

And as @lukes131 pointed out there are enough messengers out they that are trying to poison our kids. So just pick something else.
