### ISSUE TITLE
SSL certificate warning when using service delegation with DNS SRV

### ISSUE THREAD

**Issue by mbirth** [siacs/Conversations#2314]
I'm using a DNS SRV entry `_xmpp-client._tcp.example.org` to point clients wanting to login e.g. user@example.org to the actual server at `xmpp.example.org`. My understanding is that this is like a forwarding/pointer, e.g. the client asks "Hey example.org, how can a client connect to your XMPP service?" and the server replies with "Use the host xmpp.example.org!"

So my certificate's common name is set to `xmpp.example.org`. However, Conversations seems to want `example.org` in the CN. I'm not sure if this is correct behaviour as I could also point clients to a completely different host (which is serving @example.org) and I believe the CN of the certificate should be verified against the hostname of the server it is actually talking to instead of the XMPP user domain.

**Comment by iNPUTmice** [comment]
Nope. You have to build a verification chain starting from something the user has entered. The user usually enters the JID and with that the domain name.
Thus we have to verify the domain name. Unless the DNS resolution is trusted with for example DNSSEC. However Conversations doesn't support DNSSEC (yet).

**Comment by rsertelon** [comment]
So we cannot use Conversations if we want to host our XMPP server on a different subdomain?

This is weird, I think it actually worked pretty well in the past, and now I can't connect :disappointed: 

At least I can say that I trust myself and validate the SSL certificate anyways. But this might prove error prone to people using my server, because when they accept the certificate it might be an attacker's one (as we know, all users tend to accept without verifying the fingerprint, nor the error message).

I plan to deploy DNSSEC but this is something that's not so easy, and that I'll need to do on my (very very little) spare time.

Can you elaborate on what security feature Conversations would sacrifice exactly if this feature would be re-implemented?

**Comment by rsertelon** [comment]
FWIW, Xabber decided to do the same as Conversations. I'm really interested in the reasons of such decision as per [RFC 6120](https://xmpp.org/rfcs/rfc6120.html#tcp-resolution-prefer) this should work.

**Comment by iNPUTmice** [comment]
> So we cannot use Conversations if we want to host our XMPP server on a different subdomain?

Yes you can. Just make the server cert out to the domain not the hostname.

> This is weird, I think it actually worked pretty well in the past, and now I can't connect 😞

Conversations never accepted the hostname for its domain verification

> Can you elaborate on what security feature Conversations would sacrifice exactly if this feature would be re-implemented?

There is no re-implementation. It was never implemented. Because this would be insecure

To repeat myself
> You have to build a verification chain starting from something the user has entered.
