### ISSUE TITLE
Feature request:  Add option to block messages from users not on the roster

### ISSUE THREAD

**Issue by speachy** [siacs/Conversations#2345]
I'm sure I'm not the only one who's been getting a boatload of xmpp spim.

Conversations allows you to block a JID after the fact, but it provides no way of setting global privacy options, such as blocking a domain or a more generic "disallow messages/etc from users not on my roster" setting that is implementable withib

On a related note, I'd also like to see Conversations automatically end a conversation (and clear the history) if you block the user -- and also when it gets notified of an updated block list from the server.  That way I don't have to manually end/clear every conversation on each device I'm using Conversations.

**Comment by SamWhited** [comment]
> blocking a domain

You can do this now by starting a conversation with that domain, and then blocking it; however, that's not exactly easy. This commit will make it easier since you can just add a domain to the block list directly: 72537b76c5fff6f06e9e4b5b20a4dfbf14b02149

> "disallow messages/etc from users not on my roster" setting

At least in my mind, this is actually an anti-pattern; one of the key benefits of XMPP is that, like email, you can get messages and presence subscription requests from people. If you block that, and both people have to add eachother to their rosters before they can talk, everything becomes much more difficult and less intuitive. It's a small feature, with a rather large impact.

**Comment by speachy** [comment]
XEP-0016 allows you to block messages independently of presence stuff.  Or am I mis-reading the spec, and subscription requests are considered "messages" for block list perspectives?

**Comment by SamWhited** [comment]
> XEP-0016 allows you to block messages independently of presence stuff

No, you're correct, but I wasn't disagreeing on technical grounds. In my mind 0016 is extremely complicated and should probably be deprecated (this is why Conversations doesn't actually support it at all right now). Either way, I assert that blocking all messages (even if it's only messages and not presence) from people not in your list is a bad thing that has much broader consequences than people tend ot realize.

**Comment by speachy** [comment]
I imagine I'm far from the only one who will gladly make the the tradeoff of requiring presence subscriptions before allowing messages -- because right now for me, spim is outnumbering legit stuff several times over, which severly undermines the utility of using xmpp to begin with.

And while a handful of domains are responsible for most of it, IMO blocking entire domains is the wrong approach to take.

**Comment by SamWhited** [comment]
> And while a handful of domains are responsible for most of it, IMO blocking entire domains is the wrong approach to take.

I agree, and so is blocking all messages from all domains unless someone is in your list. Email did not have to do this, and I rarely get email spam these days. We need to build actual spam controls, and efforts are underway to do that.

**Comment by iNPUTmice** [comment]
For my personal use case I tend to agree with @SamWhited here. However I can imagine that for some people in the current situation allowing messages from contacts only is a good enough workaround.
Be that as it may; It is virtually impossible to build a simple allow/disallow messages from strangers mechanism on top of XEP-0016 right now. If you want to implement XEP-0016 you don't get around to implement it completely. And that's too complex for a client like Conversations.

To anyone who wants to block strangers I suggest they create the rule with Gajim or something like that. You only need to create the rule once. It's not like you need access to it while you are on the road.

**Comment by speachy** [comment]
There's a saying that applies quite well here -- "Perfection is the enemy of good"

Complaining about XEP-0016's problems ignores the fact that it's literally all we have right now.  You don't need a full XEP0016 UI in order to create a single rule.  

Users need something *today*, not at some unspecified point in the future, by which point Russian spammers will have driven federated XMPP even further into utter uselessness.

(Meanwhile, before filing this ticket, I'd blocked another 15 JIDs who sent 18 messages -- including seven domains not previously on my list.  And that motivated me to return to a full-featured desktop client to re-set up the rule I was asking for)

**Comment by iNPUTmice** [comment]
>  You don't need a full XEP0016 UI in order to create a single rule.

Unfortunately you do. Because you need to parse what's already there.

**Comment by speachy** [comment]
> Unfortunately you do. Because you need to parse what's already there.

You only have to parse out the stuff you care about -- which in this case is only a small subset of the rules, completely ignoring the rest.  Meanwhile, you certainly don't have to show any of that to the user -- a single checkbox can add or remove that specific rule.

Anyway.  It's clear this won't be implemented in Conversations, and using a different client to set up this rule is a viable workaround for sufficiently-clued users.  I've filed a separate ticket for the UI enhancements to make blocking users a bit less annoying.

**Comment by iNPUTmice** [comment]
@speachy feel free to provide a pull request for this. If you can boil this down to a simple check box that actually works and doesn't have any side effects I'll happily merge this.

**Comment by Natureshadow** [comment]
Are you aware of mod_block_strangers, which appeared in ejabberd 17.03?

**Comment by speachy** [comment]
> @speachy feel free to provide a pull request for this. If you can boil this down to a simple check box that actually works and doesn't have any side effects I'll happily merge this.

Ah yes, the "show me the code" approach.  :)

In all seriousness, I'm more inclined to implement an equivalent to jjabberd/prosody's mod_block_strangers for the server running my domain (jabberd2), as I've never tried to write any user-facing Android code -- I'm most comfortable lurking deep in the bowels of embedded C.

**Comment by klement** [comment]
> @iNPUTmice To anyone who wants to block strangers I suggest they create the rule with Gajim or something like that. You only need to create the rule once. It's not like you need access to it while you are on the road.

I tried this approach - on one of the servers which I use the option to manage privacy lists is grayed out (in gajim). My guess is that the server doesn't support it. This is a company server and I don't have the option of upgrading/changing it nor do I have the option of ignoring it. Suggestions?

**Comment by iNPUTmice** [comment]
@klement well if your server doesn't support it then there is nothing Conversations could do about it anyway. Talk to your admins at work. If you receive SPIM to your work account then your company should do something about it.

**Comment by klement** [comment]
> @iNPUTmice well if your server doesn't support it then there is nothing Conversations could do about it anyway. Talk to your admins at work. If you receive SPIM to your work account then your company should do something about it.

well you could implement the option "don't play notification sound/wake screen for contacts not in the contact list". this would work nicely for this case, because the contact list is auto-managed and everybody using the server is already in without any action on user side. New contact from the outside world doesn't know  whether I'm there (because he doesn't get presence updates) so can't expect an **instant** response, thus keeping it silent doesn't break anyone's expectations.

**Comment by eugeneseppel** [comment]
> @klement well if your server doesn't support it then there is nothing Conversations could do about it anyway. Talk to your admins at work.

You've got a very nice relation to users, iNPUTmice. Change a jabber server? talk to admins? May be next time I could advice you to change the country of residence because of drug dealer next door?

I'm using Psi desktop client with jabber.ru server for about 10 years, and there are no problems with spam, because Psi (and every other adequate client) blocks messages from unauthorised contacts. You just answering that is not your problem. I don't know anything about XEP-0191, even don't want to know what it's about and what the hell is XEP, I just don't want receive spam offers.

Of course I understand that it's a open source, but nevertheless such responces for end-users requests are not acceptable for FOSS products too. I had to remove Conversations from my smartphone just because it's impossible to distract every hour for spam.
