### ISSUE TITLE
Idea: add password-protection/encryption to chats

### ISSUE THREAD

**Issue by Piruzzolo** [siacs/Conversations#2390]
Since privacy is a major concern, I'd like to protect with a password (underlying, AES or similar) the chats. More, it would be interesting to hide specified conversations from the list, in a way similar to WhatsApp's "archive chat", but using a password to lock/unlock the conversation. Thought​s?

**Comment by ulfi** [comment]
I think this is good request. I think the main reason to use Converstations instead of an other Jabber client, is the default encryption! So the consequence should be, that the Data on the Phone (especially all encrypted conversations and all files, should be stored encrypted. So the best is to support optional encryption with the anyway available "OpenKeychain" GnuPG (so you must enter the key passphrase).

**Comment by licaon-kter** [comment]
Openkeychain is not required for OMEMO FYI.

**Comment by d9h02f** [comment]
If privacy is a concern, you should be encrypting your phone, not relying on placebo application passwords.

**Comment by Piruzzolo** [comment]
Yes, but many users may want to encrypt only these conversations, not the whole phone

**Comment by iNPUTmice** [comment]
Encrypting only the app database is ineffective. Either an attacker has root on the phone at which point they could extract the encryption key from RAM or they don't have root which means the android permissions will provide enough security.
