### ISSUE TITLE
Clear notifications if read on another device

### ISSUE THREAD

**Issue by sdfg2** [siacs/Conversations#2456]
I'm not sure if this is possible, but if a message is marked as read on another device, can Conversations pick that up and cancel the notification for it?  I know it can do that if I send a message to the other person on the other device, but sometimes I just want to read what they have to say.

**Comment by iNPUTmice** [comment]
Yes that's possible and already done. The sending client needs to request message markers and the reading client should send them. (Dino, Conversations) or the reading client needs to send chat states (Gajim).

**Comment by sdfg2** [comment]
Ah, thanks for that, but I'm using gajim 0.16.6 with "Send chat state notifications" set to "All chat states" and it's not getting picked up.  Is there something else I need to do?

**Comment by iNPUTmice** [comment]
You obviously need Message Carbons on your server otherwise that chat state wont arrive on Conversations.
And I'm not sure if there are certain conditions under which Gajim sends out chat states. Maybe the receiving client needs to signal support (The client which send the message you are reading.) Also i noticed that it is sometimes a bit flaky if that chat window was already open and you are not directly switching to it. But those questions belong in the gajim muc and not the Conversations issue tracker.

**Comment by sdfg2** [comment]
Ah yes.  In case anyone else comes here trying to figure it out - chat states are only sent if the sender of the message to you supports it in their client.  So if their client doesn't support it, it won't get changed at your end, so it won't get sent via carbons so conversations won't pick it up.
