### ISSUE TITLE
Avatars are not sent in png format

### ISSUE THREAD

**Issue by laptopdude90** [siacs/Conversations#2476]
The avatars aren't sent in png format, which violates the standard. I'll gladly fix it myself(I can't imagine it's a very difficult fix) if an experienced developer could tell me which files are relevant and I should look in.

Also, when a new account is added, the avatars of the contacts aren't downloaded instantly. They take a while to come down.

**Comment by mimi89999** [comment]
@laptopdude90 #2189

**Comment by laptopdude90** [comment]
I've seen that, but the issue was closed and it still doesn't comply with XMPP standards.

**Comment by iNPUTmice** [comment]
We are aware of that issue. For now it is on purpose.

**Comment by woj-tek** [comment]
Any update on this issue? We were just investigating an issue reported in our MUC where the user complained that the same avatar was working in conversation but wasn't working in Siskin... it turned out that because avatar (resized) and converted to PNG was over the limit of various ejabberd servers, which caused termination of the connection without any indication to the user. I think not following XEP here creates not-so-good-precedence and then user reports it as "errors" in other clients.

Yes, I'm aware of the motivation - converting jpg to png results in terrible sizes but there should be better ways to address it than basically violating the specification.
