### ISSUE TITLE
UI: "Online Staus" of own Account / am i synced ?

### ISSUE THREAD

**Issue by paskalito** [siacs/Conversations#2485]
**Problem** : One get's connected to a wifi, doesn't get messages and assumes there are no. / turns on mobile data for a short time and does the same. 
Summa summarum > an unsecure feeling of especially not "internet experts" about wether or not at any given moment my phone is up to date with what people wrote me.

**Possible solution**: Have a permanent little dot or similair in the UI, that has the following states 
- red > offline
- orange > connecting
- green > connected
- green with loadingarrows > is syncing
- greeen with a checkmark > synced and up to date all messages here, there is really noone that wrote you that importrant note that the meeting place has changed.

for now i always need to open the "manage accounts" view and wait for it to get online, and then wait an uncertain amount of time for the sync respectivly opening chats scrolling up and down until i get this popup notifacication that tells  " everything is synced".

### multiple accounts
I think if one has multipe accounts one thing is that in a conversation-view it should show the status of the account one uses for that conversation.
in the main view one could maybe add a small number next to the dot on how many that are online. or one dot per account which could get very ugly..

**Comment by iNPUTmice** [comment]
1) Conversations will warn you with a notification if it is **unable** to connect.
2) If you are paranoid you can turn on 'Send button indicates status' which will turn gray if you are offline.

**Comment by paskalito** [comment]
1. thanks, the point is that people need to know how long they need to wait for that message.
 1a: a standard message popup message "all messages synced" after each connect would be awesome, and UI wise super decent. ( and i think maybe not too hard to integrate)
2. that button is used to indicate the online status of the other person in chat. not myself. (yes if it green it also means that oneself is online, but the other one is not necessarily online.)

**Comment by iNPUTmice** [comment]
I don't think the general user is concerned about whether or not a sync is complete. The general user doesn't even know what a sync is or that this is happening.
Furthermore I don't think that turning on the internet for just a short amount of time (until sync is complete) is a general usage pattern.

**Comment by paskalito** [comment]
first: thanks for your answer :)
A: Well not if name it that way i suppose. but as i tried to point out in the beginning people want and need to know that something "works" wich means a lot diffrent things to them but one of them is getting their messages.
So a message everybody understand would be "All new messages loaded" or if there aren't any " no new messages".
B: About usage patterns : it is the one of a friend of mine which resulted for her in believing that "she does not get messages / is not working" - and i think it's a pattern many people with very limited dataplans use. Also all the people i know with no dataplan do exactly the same whenever they are in a Ubahn station or somewhere else where they get "free" wifi for a short time. or they ask friends to make a hotspot shortly to check if they got messages. So in my world almost everyone does this constantly. ( except the few with big dataplans)
Moreover i think this "pattern" happens also to everyone who turns they're phone's into flight mode over night for cinema a meeting or some other reason and then reconnect. to "the internet" afterwards.

So i'm pretty sure all these people if they reconnect and open the app basicly just exactly want to know "are there new messages for me"
and if they come in the same style as the messages that appear if you scroll up till the end of a conversation. they also would be only displayed then. (when app is open)

if people just reconnect their phones and do not open the app . because they assume push works for example and/or they are connected for longer ( cause they're on home wifi or large mobile plan). they're fine just the way it is. but also won't get any disadvantages if you change it as described above.

it kinda satisfies/solves this constant need for new input that humans have and live with more than ever these days.

**Comment by thomashermes** [comment]
ok so what if that person never set up an account in the first fucking place 


Sent via the Samsung Galaxy Express 3, an AT&T 4G LTE smartphone
-------- Original message --------From: paskalito <notifications@github.com> Date: 5/16/17  12:55 PM  (GMT-07:00) To: siacs/Conversations <Conversations@noreply.github.com> Cc: Subscribed <subscribed@noreply.github.com> Subject: Re: [siacs/Conversations] UI: "Online Staus" of own Account / am i
  synced ? (#2485) 

thanks, the point is that people need to know how long they need to wait for that message.

1a: a standard message popup message "all messages synced" after each connect would be awesome, and UI wise super decent. ( and i think maybe not too hard to integrate)
that button is used to indicate the online status of the other person in chat. not myself. (yes if it green it also means that oneself is online, but the other one is not necessarily online.)


—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/siacs/Conversations","title":"siacs/Conversations","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/siacs/Conversations"}},"updates":{"snippets":[{"icon":"PERSON","message":"@paskalito in #2485: 1. thanks, the point is that people need to know how long they need to wait for that message.\r\n 1a: a standard message popup message \"all messages synced\" after each connect would be awesome, and UI wise super decent. ( and i think maybe not too hard to integrate)\r\n2. that button is used to indicate the online status of the other person in chat. not myself. (yes if it green it also means that oneself is online, but the other one is not necessarily online.)"}],"action":{"name":"View Issue","url":"https://github.com/siacs/Conversations/issues/2485#issuecomment-301880202"}}}

**Comment by licaon-kter** [comment]
@thomashermes What do you mean? (do edit your message better when answering from e-mail, alsolanguage c'mon)

@paskalito There is no problem here, there are always 2 states:
1. Account not connected (either disabled or you have the notification telling you there is an issue, eg. no connection)
2. Account is sync'ed with whatever messages are available on the server.

There is no in between.

**Comment by paskalito** [comment]
@licaon-kter Ok, i did some testing and it seems that this is almost right. - when i send myself some messages and then connect over tor and connect in conversations to my account wait until it says online and then turn it off again. i already got the message. howewer if i send myself ~8 messages in a row and do the same only the first message got loaded.
i guess if that involves more than one contact who sends you something and also some bigger stuff such as pictures. that effect will even be bigger.
also i think that the it could make a huge diffrence if the server is very busy. because from RL experience i remeber much longer waiting times for every message to arrive, especially when multiple people sent me things.

so there certainly is something in between, even if it's not very much.

but more importantly i still don't have any noticable "sign" in the mainscreen telling me if i am connectet or when i was connectet the last time. - even when i disable all accounts the mainscreen looks like usual to me and there's nothing that tells me that i am offline at the moment not able to receive anything. ( yes if i enter a chat it is telling me that i have deactivated the account which is great) (but if i'm just offline as a whole device it won't tell me that eighter (it even still tells me that other users are online, but i have seen that issue already tracked somewhere)

**Comment by paskalito** [comment]
@licaon-kter Ok, i did some testing and it seems that this is almost right. - when i send myself some messages and then connect over tor and connect in conversations to my account wait until it says online and then turn it off again. i already got the message. howewer if i send myself ~8 messages in a row and do the same only the first message got loaded.
i guess if that involves more than one contact who sends you something and also some bigger stuff such as pictures. that effect will even be bigger.
also i think that the it could make a huge diffrence if the server is very busy. because from RL experience i remeber much longer waiting times for every message to arrive, especially when multiple people sent me things.

so there certainly is something in between, even if it's not very much.

but more importantly i still don't have any noticable "sign" in the mainscreen telling me if i am connectet or when i was connectet the last time. - even when i disable all accounts the mainscreen looks like usual to me and there's nothing that tells me that i am offline at the moment not able to receive anything. ( yes if i enter a chat it is telling me that i have deactivated the account which is great) (but if i'm just offline as a whole device it won't tell me that eighter (it even still tells me that other users are online, but i have seen that issue already tracked somewhere)

@thomashermes hmm I would guess then a "no accounts set up yet" message would be apropriate..

**Comment by licaon-kter** [comment]
Afaik, the "no more messages on server" toast helps here (with issues like #2241), again a slow connection (Tor) could undermine de app flow to a point, but that's not the app's fault.

If you don't have any account you can only see a screen that asks you to either make one or enter credentials for an existing one, not much there to fix. It's a strange question to ask though.
