### ISSUE TITLE
Crash in getLatestMarkableMessage

### ISSUE THREAD

**Issue by licaon-kter** [siacs/Conversations#2623]
#### General information

* **Version:** 1.20.1
* **Device:** Xperia 6.0.1
* **Conversations source:** F-Droid

Got it twice out of the blue. Can't repro.

Logcat: https://gist.github.com/licaon-kter/37c1574461f5097b001f32f12556da40

**Comment by l-jonas** [comment]
@licaon-kter This is catched by [this](https://github.com/siacs/Conversations/commit/32b1e5b306fb52ffb413fa88de4ac1c61520514d#diff-4c3f71d560ee00efaecc70f71e718bbfR691) (so that it no longer crashes). The underlying cause was fixed by [this](https://github.com/siacs/Conversations/commit/2b39acf3525d74aaf42ba1e8ca4131997e828862#diff-4c3f71d560ee00efaecc70f71e718bbf).

**Comment by licaon-kter** [comment]
As with the other one, an one off thing.
