### ISSUE TITLE
Kotlin integration

### ISSUE THREAD

**Issue by igoreliasm** [siacs/Conversations#2653]
Hi everyone!
Just a simple question:
Is possible to use Conversations with Kotlin or only in Java?

**Comment by perfectmak** [comment]
Kotlin is interoperable with existing java code, so I'm assuming it would
be possible.

On 13 Oct 2017 04:39, "Igor Elias" <notifications@github.com> wrote:

Hi everyone!
Just a simple question?
Is possible to use Conversations with Kotlin or only in Java?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/siacs/Conversations/issues/2653>, or mute the thread

**Comment by igoreliasm** [comment]
https://kotlinlang.org/docs/reference/java-interop.html
