### ISSUE TITLE
Text styling shows formatting too

### ISSUE THREAD

**Issue by licaon-kter** [siacs/Conversations#2689]
#### General information
* **Version:** 1.22.0
* **Device:** Xperia 6.0.1
* **Conversations source:** self build (latest HEAD)

#### Steps to reproduce
1. write some styled text
2. ` *abc* _DEF_ ```GHI``` `

#### Expected result
**abc** _DEF_ ```GHI``` -> styled text

#### Actual result
\***abc**\* \__DEF_\_  \`\`\````GHI```\`\`\` -> styled text AND styling syntax

**Comment by SamWhited** [comment]
This is part of the spec and is expected behavior.

**Comment by licaon-kter** [comment]
It's the recommended (by you) behaviour:
> It is RECOMMENDED that formatting characters be displayed and formatted in the same manner as the text they apply to. 

The spec does not explain why? What's the point?

As a requirement (by you) you have:
> Messages formatted using this specification MUST NOT hinder readability...

How does seeing <HTML> tags in a web page help with that? It's the same thing.

Link to spec: https://xmpp.org/extensions/inbox/styling.html

**Comment by iNPUTmice** [comment]
>> It is RECOMMENDED that formatting characters be displayed and formatted in the same manner as the text they apply to.

> The spec does not explain why? What's the point?

To avoid false positives

Anyway this is probably not the right place to discuss the pro and cons of this (Take it to the XMPP mailing list if you are interested). However please up-vote this issue if the styling keywords bother you so we can get a feeling on how many people don't like having the styling information in there.

**Comment by zuglufttier** [comment]
I completely agree with @licaon-kter here. The current solution looks like a bug in the software.

What exactly is the correct place to discuss this?

**Comment by SamWhited** [comment]
> As a requirement (by you)

FWIW, this was not my requirement, it was a change I made after mailing list discussion. I wanted to leave it up to the individual client to decode exactly how top render this. The RECOMMENDED was a compromise position.

**Comment by zak333** [comment]
I must agree with the current behavior and don't think the text written by the user should be changed. This markup is in my opinion only a convenience and kind of best practice feature to express the formatting without using any real markup (even if the text is _not_ really written in bold etc. by the client).
But the real intention could as well be different and as iNPUTmice stated there might be false positives and users might be confused why their text has been changed.

Comparing this with Gajim and Thunderbird: They behave exactly the same, i.e. they keep the syntax and I don't think it looks broken.

Therefore I vote to keep it in Conversations too.

**Comment by iNPUTmice** [comment]
> Therefore I vote to keep it in Conversations too.

It's probably best to down vote the original issue.

**Comment by zuglufttier** [comment]
![2017-11-14-155013_2039x1398_scrot](https://user-images.githubusercontent.com/3314278/32786317-809727ae-c94b-11e7-97db-fa0e287f3c88.png)

I made up my mind and now think that showing the tags can look good and might be even better for user experience. See the attached image. Sometimes the difference between sans and monofont won't be enough to make the user aware of that so the styling might be ignored by some user completey.

But I'd love to see Conversations making the tags less pronounced so that they don't appear to be part of the normal text but rather some kind of extra information.

**Comment by zak333** [comment]
> It's probably best to down vote the original issue.
Ah, I see. Done.

So much upvotes for this? I would be interested in reading the arguments.

**Comment by licaon-kter** [comment]
Is a simple switch in Settings, "Show styling formatting" out of the question?

**Comment by j12i** [comment]
@iNPUTmice:
> It's probably best to down vote the original issue.
Do you mean this very one? Sorry, I dont follow this tracker regularly, but I would like to cast a vote on this issue. ;)

**Comment by licaon-kter** [comment]
@j12i yes, add your emoji emotion on first post here :)

**Comment by Echolon** [comment]
@zak333 Sorry, I totally disagree and I wonder why people here always care about "false positives" in an instant messenger ... Of course there are already enough misunderstandings in normal conversations. This is an issue of the way people communicate and express themselves (and typos). Not because of

**bold** or _cursive_

texts - Even Github don't cares about it because if you use it intentionally or not, it is obvious for 99.9% of the users what happened. And even if not, they gonna find out. Conversations is not a programming software or Latex - it's an instant messaging client - stick to it, keep it comfortable and don't overestimate these tiny things. 
So, if someone wants a *bold* text, just make it **bold**, that's it - or make an opt-in option to definitely see every _ symbol _ in your text.

Finally, I think this is a very tiny iteration in the XMPP world where we shouldn't waste our efforts at the moment. I am pretty sure there are other more important task to fulfill right now...

**Comment by steffanson** [comment]
I wonder with how many false postive WhatsApp users had since since they introduced this feature in 2016:

![foobar](https://user-images.githubusercontent.com/17642285/33808594-b0776512-dde9-11e7-9113-6b902c5c8e5d.png)

or Telegram:

![telegram](https://user-images.githubusercontent.com/17642285/33808634-668667ae-ddea-11e7-91e5-b08ba44f11f6.jpg)

However, in WhatsApp and Telegram you cannot deactivate it at all. To come to a compromise I am pro licaon-kter proposal to add a simple switch, "Show styling formatting".

**Comment by iNPUTmice** [comment]
The way styling information is transmitted it is impossible not to show the styling information.
