### ISSUE TITLE
Crash in XmppConnectionService

### ISSUE THREAD

**Issue by licaon-kter** [siacs/Conversations#2704]
#### General information

* **Version:** 1.22.0
* **Device:** Xperia 6.0.1
* **Conversations source:** F-Droid

Logs: https://gist.github.com/licaon-kter/27d44e64b115846d10da8acc33197caa

**Comment by iNPUTmice** [comment]
Steps to reproduce?

**Comment by licaon-kter** [comment]
Not really, was out of the blue, but when looking at the log I've seen #2703 and the device might have been low in memory.

I'll keep an eye on it.

**Comment by l-jonas** [comment]
@licaon-kter 

This was due to an empty tag for a WakeLock. It can not occur again because in the current version, it's always set. Earlier, the account data was used as tag (which somehow generated a null), but now there is only one central lock at the XmppConnectionService.

As a result, this can be closed.

**Comment by licaon-kter** [comment]
I did not see it again.
