### ISSUE TITLE
Ability to create password-protected MUCs

### ISSUE THREAD

**Issue by knoy** [siacs/Conversations#2752]
Conversations has been able to join password protected MUCs for quite a while (Sept 2014) but still can't create a MUC with a password or add a password to an existing MUC.

While not offering any real protection from server owners, it allows a basic level of access control to participants in the same way that new MUC addresses are randomly chosen. A password also offers a symbolic level of trust between groups of people and can help reinforce the idea of a private "group chat"

**Comment by harshitbansal05** [comment]
I would like to give a shot to it...

**Comment by knoy** [comment]
If this is implemented, the password should also be embedded in invites so that when a person is invited into a password-protected MUC they will automatically join it without having to enter the password

**Comment by Neustradamus** [comment]
+1

**Comment by meaz** [comment]
here is my user-case:
I have a work project. 100 people want to participate. I created a public muc so that they can all join in easily (if I create a private one, I would then have to add the 100 participants manually as contacts, which is really annoying). But I don't want anyone to be able to join: just the 100 participants. So I could give them a password and set the muc as password-protected.

**Comment by iNPUTmice** [comment]
I find passwords for muc to be an outdated and potentially insecure system. MIX for example doesn’t even have those anyway.

**Comment by meaz** [comment]
@iNPUTmice then, how would you handle my usercase (see previous comment)?

**Comment by licaon-kter** [comment]
@meaz private invite only MUC, you still need to send them the password right? How do you do that? So instead of sending emails just invite them.

**Comment by meaz** [comment]
@licaon-kter I meet all those participants in the beginning of the project, so I could just share the password orally.

To be really precise, here is the project:
I'm a teacher. I'm working with other teachers from all around Europe. I'm trying to have them moving out of Whatsapp... Each one of us have about 30 pupils. The idea is that we create about 15 working groups of about 25 pupils from the different participating countries. So, without password-potected muc, that means that I would have to manually invite 25 pupils in each of the 15 groups. With password-protected muc, I could just create the 15 muc with the same password (I don't mind other pupils knowing the password, I just care about other server users :) and share the muc addresses and passwords to my colleagues by email, or to tell it to my pupils in class.

The other problem I see with the invite possibility, is that it means that the pupils would need to first create their account, then they would have to contact me so that I  invite them in their room. It would be too complicated for them, and would mean more than 300 messages/invitation for me to make.

**Comment by licaon-kter** [comment]
You can allow users to invite other users, btw, so you invite the teachers, they invite whomever.

**Comment by meaz** [comment]
But to invite their pupils, they would need to know their jid, right? So if I get that correctly, the pupils create heir account, then contact their teacher with Conversations  to give their jid, then their teacher can invite them into the room. Am I right? (sorry, I'm just trying to understand how to make taht easy for 13 year old kids and non-techsaavy colleagues)

**Comment by licaon-kter** [comment]
@meaz if it's your server maybe you could just mass create them as `first.lastname` with some password, then the teachers invite them or again you could just add them straight from the server side. Eg. Teachers give you the pupils names you parse that, etc

You can automate this to a degree or just fallback to pupils registering, teachers inviting, etc manually

**Comment by meaz** [comment]
That what I did this year for my own server, but I was trying to find a more long-term solution as my server was just for a school year... And I'm about to show to about 150 teachers from all Europe that they could use Conversations with the server of their choice, so I want to be sure they would be able to create private-muc for their pupils easily.
At last, I guess their is no other solution than inviting manually each pupil. But thanks anyway @licaon-kter for the time you have taken to help me find a solution.
