### ISSUE TITLE
Conversations not working when in background

### ISSUE THREAD

**Issue by Sortland** [siacs/Conversations#2760]
#### General information

Version: 1.23.3
Device: 2x Huawei Honor
Android Version: Android 6.0 and Android 7.0

#### Steps to reproduce

When Conversations is sent to background on Android 6/7, it does not wake up properly when a message arrives. This is true also when in settings related parameters are set (Akku-configuration, allow it to run in background, no notification about closing the app due to power usage).

1. Send conversations into background on one of the devices
2. Wait e.g. one hour
3. send a message from the other device to the one where Conversations is in background -> now this message is in state "Waiting..."
4. Wait for several hours or continue immediately with 5:
5. Bring Conversations in foreground actively on first device -> now the message arrives

#### Expected result

The message should arrive and the user should be notified also when Conversations is in background.

#### Actual result

See above

**Comment by licaon-kter** [comment]
Three things:
* Did you do the [3 magic spells](https://www.forbes.com/sites/bensin/2016/07/04/push-notifications-not-coming-through-to-your-huawei-phone-heres-how-to-fix-it/2/)? 
* Does Settings->Expert->Enable foreground service help?
* Does [your server support Push](https://conversations.im/compliance/)? (if your app is from the Google Play store)

**Comment by Sortland** [comment]
I'm running it with exactly the same settings like WhatsApp - which is working fine and without any troubles. But I'll check these points...

**Comment by Sortland** [comment]
OK, these settings don't change anything. The point is, Conversations does not even seem to receive these messages since the sender still shows "Waiting...", so it is not only a problem of the notification not popping up!

**Comment by licaon-kter** [comment]
Waiting means the sender has issues with his/her server.

**Comment by Sortland** [comment]
We tried different servers, an own one, the one which is provided by the University of Vienna, a random one from the internet - all showed the same behaviour.  Sender and receiver always have been on the same server.
And: as soon as the receiver pushes Conversations in foreground, the "Waiting..."-state is left on sender side and the message arrives

**Comment by licaon-kter** [comment]
What does `the "Waiting..."-state is left on sender side` mean?
It stays in `waiting` even after you receive it?

**Comment by Sortland** [comment]
No, it happens exactly as described in the bugreport:
- sender submits a message
- on sender-side the message is in state "Waiting..." (small text at the end of the message)
- this situation can last several hours
- when the receiver of the message brings his App to foreground, the message arrives and on sender side the text "Waiting..." is replaced by a green trick

**Comment by Sortland** [comment]
Yes, all messages are OTR-encrypted and the Apps are configured as protected on both phones. Once again: WhatsApp is working fine by default and without doing all this configuration stuff, so I do not think it has anything to do with that.

**Comment by iNPUTmice** [comment]
> WhatsApp is working fine by default and without doing all this configuration stuff, so I do not think it has anything to do with that.

Huawei puts a few *well known* apps on the list of protected apps by default. Including WhatsApp. So that’s not an indication for anything.


Please try to send unencrypted and/or OMEMO messages. OTR is known for being extremely unreliable and will be removed in Conversations 2.0 for exactly that reason.

Also please read my entire comment and provide the output of adb logcat.

**Comment by Sortland** [comment]
Encryption is the only reason why I'm using Conversations, when you remove this function, it is of no use for me any longer and you can close this bugreport.

**Comment by iNPUTmice** [comment]
OMEMO (and PGP) are end to end encryptions as well.

**Comment by Elmi77** [comment]
i have a similar problem with a HTC-based tablet, so no huawei-crap involved here. and i really don't undertstand the OTR-argument: when the app is locked in background and does not react on incoming data, which should it be better with(out) OTR? in every case the server sends some data the client has to react on - no matter what it contains. btw: PGP is not really usable IMHO, entering the own key password again and again is not user-friendly

**Comment by licaon-kter** [comment]
@Elmi77 How does OMEMO behave?

**Comment by Elmi77** [comment]
i never got it working. it tells me it misses some keys but does not offer the possibility to generate one for an existing contact/connection. so way too complicated

**Comment by licaon-kter** [comment]
The default settings should work, if you or you contact have disabled "Blind trust before verification" in Expert Settings, or disabled presence for each other, then you'd miss some keys.

**Comment by Elmi77** [comment]
both sides are working with default parameters and all i get when trying to send OMEMO is a message "error: for this contact no usable keys are available. when they have been deleted, they need to be created new" (translated from German). only option at this point: press the "cancel"-button. so i'm sorry but this is no alternative to OTR for me since usage is unclear

**Comment by licaon-kter** [comment]
Do each contact have an OMEMO key in Account details?

Try to "Delete OMEMO keys" in Expert, for each contact and retry.

**Comment by Elmi77** [comment]
this does not change anything

the error message complains about no keys, so why should deleting the (non existing) keys help? and i do not see any way to **create** a key which seems to be necessary here!

**Comment by licaon-kter** [comment]
It is created on first message:
* Open chat
* Click lock icon - choose OMEMO
* Write something
* Send

**Comment by Elmi77** [comment]
i happily repeat it for you again: that's exactly what I'm doing and that's exactly what leads to the error message mentioned above. so it does _not_ work!

**Comment by iNPUTmice** [comment]
@Elmi77 I don't understand what you mean by 'similar' problem. If you want help the group chat might be a better place for that. Please don't hijack issues that might or may not be related with your support request.
However the group chat has lots of friendly people who might be able to help out.

**Comment by Elmi77** [comment]
wtf??? all i have done is confirming the original bug, i have not started this useless OMEMO discussion and i have not asked for it! so don't blame me for that! :-(

**Comment by Elmi77** [comment]
and "similar" means, i have the same problem with a non-huawei tablet like is described in original bug report - so what can't be understood here???

**Comment by iNPUTmice** [comment]
The problem is that OTR messages not being delivered is a very generic error case that can have various causes that may or may not depend on the XMPP provider in question or whether or not you have mutual presence subscription with your contact. You didn't volunteer that information and thus the group chat is a much better place to ask you those questions.

**Comment by Sortland** [comment]
Just to complete this "discussion": I tried it with unencrypted messages and exactly the same problem appears, messages do not arrive when Conversations has been in background for a longer time. When I try to get some messages with "adb" this does not happen at all, then everything is working as expected.

But when I read this thread here it seems to be completely senseless to file a bugreport...

**Comment by iNPUTmice** [comment]
> But when I read this thread here it seems to be completely senseless to file a bugreport...

Not senseless but thus far we haven't determined if this is in fact a bug. And experience has shown that it is much easier to provide support over (group) chat.

So you said you have enabled the foreground service. At the time when you reopen the app (after an hour or so according to your words) to you still have the foreground notification. In lack of adb logcat this might help us determine if your OS kills the app (=foreground notification is gone) or if it just kills the network connection.

Also the issue template that also asks for information like source of the app (PlayStore) and server used (does the server have push) is there for a reason.

That's why I have a problem with other people like @Elmi77 hijacking a thread because they usually don't fill out the issue template and that has important information.

**Comment by Sortland** [comment]
I switched over both ends to Zom, now using the same server and also encrypted messages everything works fine, no delays for two days. And: everything is working with default settings, no need to change lots of Android settings. So for me it does not matter if your are willing to fix this bug or not, I'm no longer using your buggy App.
