### ISSUE TITLE
absent clip paper icon version 1.23.5

### ISSUE THREAD

**Issue by gudbes** [siacs/Conversations#2788]
Hello,

I have installed version 1.23.5 today and I don't have any more clip paper icons to make pictures, voice messages,....
Is that normal?

**Comment by licaon-kter** [comment]
I can see it here ok, buildingwfrom HEAD

**Comment by neonknight** [comment]
Running 1.23.5 from Play Store (I'm on beta). Same here in group chats for one account, instead of the paper clip I get a group icon. Clicking this will open group preferences. BUT: the paper clip is still present in group chats on another account on same device as well as in single person chats for both accounts. 
Also when using the "share" function in other apps I cannot select those chats with missing paper clip icons. 

The only difference between the accounts I'm aware of is on the server side. Both servers were set up as identical as possible, except the one now missing the paper clip is prosody 0.9.10 on Debian 8, while the still working one is prosody 0.10.0 on CentOS 7. But I doubt it's a server side issue since sharing was possible in group chats with the previous version of Conversations.

**Comment by kriztan** [comment]
This has something to do with the new httpupload version. If the server doesn't support the new version, there will be no bhttpupload available. Check the availability in your account details with enabled server information.

**Comment by neonknight** [comment]
excellent hint @kriztan I updated mod_http_upload to latest hg version, now Conversations seems to be happy again.

**Comment by gudbes** [comment]
Thank you for your answers. I'll try to find time to update the module.
Otherwise little question: is this conversation compatible ejabberd

**Comment by licaon-kter** [comment]
Yes, 18.01 works fine.

**Comment by gudbes** [comment]
@licaon-kter
Thank you for your answer

**Comment by OverkillTASF** [comment]
@kriztan This seems like it was implemented in a really haphazard way. There isn't anything functionally wrong with the "old" HTTP upload as far as I can tell, yet Conversations all at once starts doing it differently, requiring server side changes? Was this a security issue or something? The few clients who haven't upgraded can do HTTP upload just fine. Most of my users are toast though, and I can't find any documentation yet on the EJabberD side as to what this "new version" of http_upload is about or when it is going to land in stable code.

**Comment by licaon-kter** [comment]
@OverkillTASF Whasn't this about a Prosody issue? You experience it with ejbberd too? The upload :0 ...

**Comment by OverkillTASF** [comment]
@licaon-kter Yes, Ejabberd 16.09. Same problem. I'm sure, as with Prosody, upgrading on the server side would work, but especially without understanding what change was made on the client side and why it "broke" things, that's very frustrating. I'm looking at what it will take to get to a more recent version of Ejabberd in my environments, but I'm not even sure what the minimum version would be to support whatever Conversations is enforcing.

**Comment by licaon-kter** [comment]
That's old, yes it was fixed, update to 18.01 please.
What OS?

**Comment by OverkillTASF** [comment]
Believe all are Debian stable branch.

**Comment by licaon-kter** [comment]
This https://jabber.at/p/apt-repository/ ?
