### ISSUE TITLE
Allow widget to send message to a specific contact

### ISSUE THREAD

**Issue by spaetz** [siacs/Conversations#2823]
I love conversations so much, I have installed it on all my relatives' phones :-). However, I would like to have a widget that opens conversations with a specific contact's chat open, similar in how there are widgets to directly start typing an SMS to someone, or starting a call.

When I open a person's contact details in the addressbook and click on the saved xmpp: address, I get asked whether I want to use conversations for "Send via Start Conversation". This is exactly what I want as a widget on my homescreen :).

I work around this by adding a bookmark to firefox containing an "xmpp://jid@jabber.de" URL and saving that bookmark on my homescreen using Firefox. This kind of works (but I do not get the contacts image as icon, just a question mark..), but feels like a very clumsy workaround. (it briefly opens Firefox, and then directly conversations).

Adding a "add contact to homescreen" where we now have a "share contact via xmpp URL" would be a great way to achieve this, imho.

P.S. I am putting a 20€ bounty on this one.

**Comment by harshitbansal05** [comment]
@spaetz personally i also felt the need for the same and would love to work on this issue, if it is agreed by the maintainers..

**Comment by Xohoo** [comment]
this is already possible with android 8 (long press on the conversations icon in the launcher)

**Comment by harshitbansal05** [comment]
@Xohoo , but users of oreo constitute a very low percentage of all android users.

**Comment by harshitbansal05** [comment]
@iNPUTmice may I work on it?

**Comment by Donyme** [comment]
I would like to work on it, @iNPUTmice  can i continue?

**Comment by harshitbansal05** [comment]
@Donyme i have already asked for the same.

**Comment by iNPUTmice** [comment]
You don’t have to ask for permission to work on things.
Issues marked as pr-welcome are exactly that. Merge decisions for PRs for other issues depend on how well they are execute, how difficult / complicated it will be for me to maintain them in the future. and if they have any negative side effects on usability.

GSoC applications don't necessarily depend on merged code; If you for example provide a PR with high quality code and a wonderful UI that allows me to remote control my espresso maker I might not merge it because it is not something for mainline Conversations but i will still appreciate the execution.

**Comment by iNPUTmice** [comment]
This has been implemented in 2.1.0
