### ISSUE TITLE
I would like to show a new sample logo that i make for Conversations. Hope you will accept this sample contribution

### ISSUE THREAD

**Issue by sachoosaini** [siacs/Conversations#2859]
![conversations sample logo](https://user-images.githubusercontent.com/10970138/37251167-860eb828-2530-11e8-983d-7b798f06e9df.png)

**Comment by sachoosaini** [comment]
![conversations sample logo2](https://user-images.githubusercontent.com/10970138/37251537-e53092f2-2537-11e8-8943-659ab92b6edc.png)

**Comment by licaon-kter** [comment]
Is this some self-assigned utopian.io task that you did in the hopes of winning some crypto-currency?

**Comment by whitetornado** [comment]
mwohahaha good try but let the original

Op 11 mrt. 2018 10:00 schreef "Licaon_Kter" <notifications@github.com>:

Is this some self-assigned utopian.io task that you did in the hopes of
winning some crypto-currency?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/siacs/Conversations/issues/2859#issuecomment-372099912>,
or mute the thread

**Comment by uchchishta** [comment]
You forgot to follow the guidelines: https://material.io/guidelines/style/icons.html#icons-product-icons

**Comment by sachoosaini** [comment]
@licaon-kter nope. This using conversations. I am a self taught user, I am still student. So want to contribute something. There are people out there who do not need anything in return of😁

**Comment by iNPUTmice** [comment]
I think we'll stick with the current one for now.
