### ISSUE TITLE
Dialog not retained across configuration change.

### ISSUE THREAD

**Issue by harshitbansal05** [siacs/Conversations#2860]
#### General information

* **Version:** 1.23.8
* **Device:** Redmi Note 3
* **Android Version:** Android 5.1.1 Stock
* **Server name:** xmpp.jp
* **Conversations source:** self build (latest HEAD)

#### Steps to reproduce

1. Open `StartConversationActivity`.
2. Click create group or create conference fab.
3. Rotate screen

#### Expected result

The dialog must be retained across configuration change.

#### Actual result

The dialog dismisses.

**Comment by l-jonas** [comment]
I'm planning to do the same thing for the other dialogs at the StartConversationActivity.

This change also keeps the dialog for the options of the new conference if the member selection is canceled.

**Comment by licaon-kter** [comment]
@l-jonas FYI, [Conversations 2.0.0 in already in beta](https://twitter.com/iNPUTmice/status/971781842872492032), and it's developed on the [app_compat](https://github.com/siacs/Conversations/tree/app_compat) branch.

Try to rebase your changes.

**Comment by iNPUTmice** [comment]
Yes development currently happens in the unfortunately named app_compat branch. Sorry for the confusion.

The new ConversationsActivity in the app_compat branch also has some ideas on how to call onBackendConnected() on a fragment from the activity. TLDR: Instead of registering a listener i just find all fragments from the Activity’s onBackendConnected(), iterate over them and then call onBackendConnected() on all active fragments.

**Comment by harshitbansal05** [comment]
@l-jonas I have already started to work on it, so you kindly take any other issue.. Thanks

**Comment by l-jonas** [comment]
@harshitbansal05 Sorry

@iNPUTmice Would it be possible to document how contributions should be made (which base branch, ...)? Ideally as markdown in the master branch so that everyone finds it.

**Comment by iNPUTmice** [comment]
@l-jonas Yes I'm sorry about that. The master branch has always been the 'default' branch where active development happens. And it will return to that state in a few days time. I've just been doing a lot of refactoring for the upcoming version 2.0 that at times put Conversations in an unstable state so development couldn't happen on the master branch.
If you want you can just sit it out and wait for things to return to normal. Otherwise; just work on the app_compat branch for now.

**Comment by iNPUTmice** [comment]
This has been fixed in 2.0.0-beta.3
