### ISSUE TITLE
OOM when showing details of a large conference

### ISSUE THREAD

**Issue by wiktor-k** [siacs/Conversations#2894]
#### General information

* **Version:** 2.0.0-rc.1
* **Device:** Note8
* **Android Version:** Android 7.1.1 Sock
* **Server name:** self hosted
* **Server software:** prosody 0.10 
* **Installed server modules:** Stream Managment, CSI, MAM
* **Conversations source:** PlayStore Beta Channel

#### Steps to reproduce

1. Join a big MUC, e.g. I'm using gateway to connect to IRC `#rust@irc.mozilla.org` and it has currently 1190 participants,
2. Try to show conference details,

#### Expected result

I can see conference details. Maybe the list of participants is omitted or truncated but the details window works.

#### Actual result

The app hangs and quits with OutOfMemory error.

#### Debug output
```
java.lang.OutOfMemoryError: OutOfMemoryError thrown while trying to throw OutOfMemoryError; no stack trace available
```

**Comment by SoyaLeaf** [comment]
Sorry for disturbing you，
I am trying to fix this issue, but I don't know how to use gateway to connect to irc and I also did not find a group chat which with a large number of participants, so I can't test it...

I tried to search on Google how to connect to irc, but it seems that I didn't find a good tutorial... maybe it's because I don't speak English well enough.

Could you help me? thanks. :-)

**Comment by wiktor-k** [comment]
@SoyaLeaf contact me (info in my GitHub profile link) via xmpp or email and I can arrange you access to my IRC gateway for the time being.
