### ISSUE TITLE
Missing the user list in MUC 

### ISSUE THREAD

**Issue by acnapyx** [siacs/Conversations#2992]
#### General information

* **Version:** 2.1.2
* **Device:** OnePlus One A0001
* **Android Version:** Android 6.0.1 (Cyanogenmod 13.1.2)
* **Server name:** self hosted
* **Conversations source:** F-Droid

#### Steps to reproduce

1. Open MUC

#### Expected result

Icon with contact list

#### Actual result

Icon missing, only three dots menu and lock for encryption icons available. (Yeah, I know, this function is moved to the menu 
as "Group chat details".)

This is more like usability/design issue than a bug. When joining a MUC I'm used to be able to easily see the people who are online, as it was in pre-2.1.x. Present UI forces me to make more clicks to achieve the same result I've achieved before. What is the reasoning behind this decision, and is it possible to put an option to enable/disable this behaviour for those who do not want to tap on menu and choose "Group chat details" every time they want to see who's currently in the MUC?

**Comment by iNPUTmice** [comment]
It has been moved to the overflow menu because
* the corresponding *Contact details* for 1:1 chats is in the overflow menu as well
* It was in different places (overflow menu, icon) depending on screen size and whether or not HTTP upload was available
* Three icons in the action bar is too much (attach, lock, group details)
