### ISSUE TITLE
Openfire with http plugin does not work with latest conversations version 

### ISSUE THREAD

**Issue by 111usman** [siacs/Conversations#3059]
i m using openfire 4.2.3. with http upload component which once you shared(thanks for this).But conversations latest version 2.2.2 does not show http server available in server info... I have also tried to use openfire plugin which is available on openfire site. But same result... Previously i used to edit conversations code and manually add pull request #2900 to it .That worked correctly with openfire server and server show http upload available...

**Comment by iNPUTmice** [comment]
Unable to reproduce. Works fine for me. I think if you configure it correctly it would work even on Conversations `<=2.2.1`

**Comment by v8star** [comment]
mee too with conversations 2.2.2 and ejabberd 18.01. With v2.2.1 http_upload was available with ejabberd 17.x

**Comment by licaon-kter** [comment]
@v8star It should work just fine on ejabberd (18.01-18.04), quote your ejabberd http_upload block or logs of the errors bot from Conversations and ejabberd if possible.

**Comment by v8star** [comment]
the problem can be the ssl cert? i'm just testing it with gajim with a pc and when i try to upload via http an image, came out an error about cert. I'm thinking because i see that was added for each ejabberd service another host after nameserver.tld, in this case "upload" 

The cert is from a private PKI and CA is trusted (pc and phones) via policies: conversations never gave to me warnings about cert.

And when i started ejabberd service, i get some warning, the related one is:

"No certificate found matching 'upload.im.***.net': strictly configured clients or servers will reject connections with this host; obtain a certificate for this (sub)domain...."

**Comment by licaon-kter** [comment]
@v8star Even self-signed ones need to include ALL your domains that you use. Add them all to your SAN in the cert.

**Comment by iNPUTmice** [comment]
I suggest that for help with misconfigured servers you use the conference.

**Comment by 111usman** [comment]
Thanks All for your suggestions and guidance
