### ISSUE TITLE
Quicksy Password

### ISSUE THREAD

**Issue by dermitdemdino** [siacs/Conversations#3288]
I set up Quicksy on Android with SMS verification. How do I get my password to set up the account +49123456789@quicksy.im in Gajim on the desktop?

**Comment by licaon-kter** [comment]
Should be available on 2.3.7 iirc.

If on F-Droid, it will be build on the next build cycle.

**Comment by dermitdemdino** [comment]
This is great. Thanks for the info.

**Comment by iNPUTmice** [comment]
FWIW for technical reasons you need to reinstall the app if you want to discover your password that way.

**Comment by Rik44444** [comment]
Hi, i have this similar question, i'd like to access my quicksy xmpp account via Jitsi on Desktop. I tried entering the 6-digit authsms code that I received for Quicksy, but that did not work. I also cannot find a setting relating to this. How do i get the password, so that I can add the account to Jitsi Desktop?

**Comment by licaon-kter** [comment]
@Rik44444 Account - menu - password?

**Comment by Rik44444** [comment]
yeah that worked thanks, had only found the 'regular settings', not the Account settingS!
