### ISSUE TITLE
fcd version of Conversations not updated

### ISSUE THREAD

**Issue by bahur142** [siacs/Conversations#3401]
Hello
On two of my devices I am using self-compiled version of Conversations. Until now I had have no problems. But today I am trying to compile v2.4.2 and when the compilation finished, it shows me "**Conversations-2.3.11-conversations-free-compat-debug.apk**".
Then tried to compile variant FreeComatRelease, and the produced file is the right one: **"Conversations-2.4.2-conversations-free-compat-release-unsigned.apk"**.
But the problem is that FCR version does not want to run on my Android 4.4.4. 
Just FCD version works for me. I am attaching two screenshots what my Android Studio shows.

And my question here is, why the FCD version is not updated? Is this a problem in my Android Studio?
Thanks for the great product and the patience you have!

![android_studio apks](https://user-images.githubusercontent.com/30805725/53753728-a388c700-3eba-11e9-8996-e5a124a6894a.jpg)

![android_studio](https://user-images.githubusercontent.com/30805725/53753745-ab486b80-3eba-11e9-8cce-a5173f7c6b6b.jpg)

**Comment by iNPUTmice** [comment]
You probably need to set up signing keys when you want to use release instead of debug. However this is not Conversations specific; just general android development. I’m sure a search engine of your choice will find you a tutorial on how to do this.
It's probably easiest to just go with the debug version though.
