### ISSUE TITLE
Feature Request: different color by account

### ISSUE THREAD

**Issue by racuna** [siacs/Conversations#3402]
#### General information

* **Version:** 2.4.1+fcr
* **Device:** Redmi Note 5
* **Android Version:** 8.1.0 
* **Server name:**  movim.eu, diasp.org, disroot.org
* **Server software:** movim, diaspora
* **Installed server modules:** I dunno
* **Conversations source:** F-Droid

#### Steps to reproduce

1.having more that one xmpp account
2. talk to somebody
3. disable some accounts to know which account I'm using to talk to somebody

#### Expected result

Assign colours for each account (custom or automatically), and show them on the list of recent conversations

**Comment by iNPUTmice** [comment]
The design philosophy of Conversations is that you have different contact on different accounts and can infer from the contact what account you are using. For example your work contacts on your work account and your friends on your personal account.
Optimizing for the use case where you have multiple accounts 'for backup purposes' or because you want to experiment is not something we try to cover.
