### ISSUE TITLE
Feature request: Matrix protocol support

### ISSUE THREAD

**Issue by bes1002t** [siacs/Conversations#3427]
I think conversations is the best jabber Clients which exist. At work I'm using jabber very offen, but for private communication we host our own Matrix Server. I would like to use one client for both protocols, jabber and Matrix.

So what do you think about the long term goal to implement the Matrix protocol into conversations?

**Comment by licaon-kter** [comment]
April 01 has passed...

> but for private communication we host our own Matrix

Why not XMPP?

**Comment by poVoq** [comment]
Matrix.org has an experimental XMPP bridge now called bifröst. This allows you to join any federated Matrix channel with a XMPP client. It's still a bit buggy, but overall it works fine.

**Comment by zinid** [comment]
> Why not XMPP?

Because Matrix is much superior to XMPP: it's a modern HTTP+JSON based protocol with git-like replication, with a lot of features planned.

**Comment by licaon-kter** [comment]
@zinid Oh, I didn't realise, XML is rather old indeed.

Tell me more about those planned features.

Can I run a Matrix server for my 2 dozen users on my current RPi1/256Mb? That would be nice...

**Comment by bes1002t** [comment]
This request is not only about personal comfort, because I could simply use the XMPP Matrix binding as @poVoq mentioned (even if there are several bugs).

But there are specific advantages for conversations. At the moment you could just use Riot as Matrix reference implementation, but not with XMPP alone. There is a whole new community rising, using Matrix (also the French government). Conversations could increase the diversity of clients for this community.

**Comment by iNPUTmice** [comment]
I’m not a fan of multi protocol clients as I have personally never used a good one.

**Comment by bes1002t** [comment]
Sorry @iNPUTmice but that is a really Bad reason to close this ticket.

1. you never used one means there isn't one?
2. I think pidgin is doing well
3. for conversations it would be really easy to implement this from a user experience point of view, because conversations is already providing a multi account principle. It would be just another account with just another protocol. For sure it needs some effort to make this working in a user friendly way. But this feature opens a whole new market for conversations.

Additionally there is already a Android SDK for Matrix which could be simply implemented.

**Comment by zinid** [comment]
Even Yaxim decided to implement Matrix:
https://yaxim.org/blog/2019/04/01/yaxim-enters-the-matrix/

**Comment by licaon-kter** [comment]
@bes1002t What is Pidgin doing well exactly? Dying?

> Additionally there is already a Android SDK for Matrix which could be simply implemented.

_Simply_? Count the Android clients: https://matrix.org/docs/projects/clients-matrix 

But there's [Pattle](https://git.pattle.im/pattle/android), right?
> Currently Pattle is a native Android app made purely in Kotlin and using the official Matrix Android SDK.
This might change in the future. I'm not very satisified with how the current Android SDK is designed and documented (barely at all). I have been working on my own SDK in the past, but because the Matrix spec is still incomplete, this deemed to be a hard task.

:confused:

**Comment by zinid** [comment]
> I'm not very satisified with how the current Android SDK is designed and documented (barely at all)

@licaon-kter I've heard there is a plan to redesign the library and write the documentation.

**Comment by licaon-kter** [comment]
@zinid RiotX in Kotlin indeed, that's why I'd rather have Conversations rewriten in Kotlin first (2020 iirc) thes support Matrix in time for the Dendride released, of course. 

Hope those Tezos grants are put to good use.

**Comment by Mikaela** [comment]
I fear that Matrix support bloats clients and would make Conversations as unusable as Riot on my phone. Conversations is almost immediately usable, but Riot requires me to wait every time I launch it or press the switch app button within it and immediately select it again and MiniVector is not any better.

In my opinion better option would be using the Matrix XMPP bridge when it gets MAM support (https://github.com/matrix-org/matrix-bifrost/issues/64), there is a quick [address syntax](https://github.com/matrix-org/matrix-bifrost/wiki/Address-syntax) in their wiki.

On multi-protocol clients, I have understood that Pidgin is missing support for many XEPs making using XMPP on it a pain, but I haven't used it with XMPP in ages, because last time I heard it was missing OMEMO support which I need.
