### ISSUE TITLE
Quicksy shuts down when dismissed from recent apps list.

### ISSUE THREAD

**Issue by 9662** [siacs/Conversations#3450]
#### General information

* **Version:** Quicksy – version unknown
* **Device:** Unknown
* **Android Version:** Unknown
* **Server name:** quicksy.im
* **Server software:** Unknown
* **Installed server modules:** Unknown
* **Conversations source:** Google Play

#### Steps to reproduce

1. User boots up phone
2. User uses Quicksy to communicate
3. User uses other applications
4. User removes Quicksy from Android's “recent applications” list

#### Expected result

User should remain logged in and reachable.

#### Actual result

User's Quicksy shuts down and User is no longer reachable (status changes to offline). When User manually opens Quicksy again (or reboots phone), he becomes reachable again and queued messages are delivered to him.

#### Debug output

This does not occur to me but to a contact of mine, hence the absence of detail. He uses a mid-range regular Android phone, not rooted or otherwise modified. Quicksy was downloaded from Google store.

**Comment by licaon-kter** [comment]
Disable battery optimizations.

See advice on https://dontkillmyapp.com for that brand, if available.

**Comment by iNPUTmice** [comment]
Without information on what device the user in question has there is absolutely nothing we can do about it.
In general (vanilla Android) when the app is swiped away from recents it will automatically restart itself. On top of that on Android 8+ swiping it has no effect at all since the foreground service is automatically enabled.
On top of that Quicksy (from Play) uses Push by default so even if it were to be killed it should be woken up by push notifcations.

So Conversations in general and Quicksy in particular has multiple mechanisms in place to work reliable. Unless the Vendor messes with it; In that case take a look at the link @licaon-kter posted.

If the device is Android 7 or older it can help to enable the foreground service in the expert settings (Quicksy has that as well.)

For further questions I invite you to our group chat on XMPP.
