### ISSUE TITLE
"Ignoring broken session exception because checkForDuplicase failed"

### ISSUE THREAD

**Issue by Moarc** [siacs/Conversations#3490]
Conversations 2.5.3, F-Droid build
Redmi 7 and Redmi 4X
Android 9 and Android 7.1 (MIUI)
own ejabberd instance, version 19.05, with mod_http_upload, mod_mam, mod_offline, mod_pubsub, mod_push among others

I start typing. The other side gets the '$name is typing' message, but after I send the message, nothing shows up. It also doesn't work the other way around. OMEMO keys are manually verified using the QR code, and show up with a green shield under 'contact details'. 
The logs show "ignoring broken session exception because checkForDuplicase failed" when a message should be received. This only happens between two Conversations instances, and Conversations<->Psi/Gajim on the same accounts works perfectly. Of course, when troubleshooting this issue, I first disconnected the desktop clients on both sides.

**Comment by iNPUTmice** [comment]
You probably restored a backup which broken the session in the first place.
Automatic session repair (because it could trigger a chain reaction) tends to err on the side of caution and only fires if it can with absolute certainty verify that a message hasn’t been processed twice. For that MAM must be enabled for the account in question. (So we get stanza-ids)
