### ISSUE TITLE
Incorrect certificate warning when using SRV records

### ISSUE THREAD

**Issue by julijane** [siacs/Conversations#3585]
#### General information

* **Version:** 2.5.12+pcr
* **Device:** Moto G5
* **Android Version:**  Android 8.1.0
* **Server name:** self hosted
* **Server software:** prosody 0.9.12
* **Installed server modules:** does not matter
* **Conversations source:** PlayStore

#### Problem description

(Not using the standard template here because it makes no sense).

My XMPP address is jule@julijane.de. There is no XMPP server on julijane.de buth there are SRV-Records for XMPP service pointing to the actual XMPP server jabber.fqdn.org.

Conversations complains that there is a certificate issue, probably because the certificate presented by jabber.fqdn.org does not contain "julijane.de". It does however contain "jabber.fqdn.org" which is the server designated by SRV record. So there is no certificate issue and conversations should not complain. If the certificate would need to include "julijane.de" (in this case) it would make using SRV records rather pointless, as I would have to have julijane.de pointing to the same IP as the XMPP server is running on or do some awful tricks to get a certificate including it.

**Comment by licaon-kter** [comment]
Enable advanced connection settings, input actual server address in account settings, helps?

**Comment by iNPUTmice** [comment]
The certificate has to be valid for something the user has entered. (To create a trust chain)
Usually this is the domain part of the Jabber ID. The hostname is only derived from the domain part via unsecure DNS and thus does not complete the trust chain. (Unless it is in which case Conversations will happily accept it.)

**Comment by julijane** [comment]
@iNPUTmice Please reopen the issue. I think you have not though this through properly.

Your argument about "unsecure DNS" does not make sense. Because if that is your stance then the same applies to the certificate in the first place. Every Lets Encrypt certificate, so the vast majority of all certificates in use today, is also only verified by "unsecure DNS". If you reject "unsecure DNS" then you have to reject almost all certificates in use today.

Also DNS does not have to be "unsecure" and in my case it is not. My zone "julijane.de" is secured by DNSSEC, thus the SRV record can be totally trusted.

Furthermore: The possibility to use SRV records to delegate to another hostname is a part of the XMPP specification. It is accepted practice in other clients and of course it will NOT make any problems in S2S communication. With your reasoning you make it pointless to use SRV records and then you are simply not compliant to the XMPP specification. 

Please reconsider this.

**Comment by iNPUTmice** [comment]
You can - at your own risk, because this is broken in a surprising number
of networks - enable DNSSec in the expert settings of Conversations and
your certificate will be accepted if it only contains the hostname (and you
have the records signed)

The Let's encrypt analogy doesn't hold up because for one to fail I only
need to MIM you for the other to fail I need to MIM you *and* Letsencrypt.

**Comment by vpelletier** [comment]
> You can [...] enable DNSSec in the expert settings of Conversations and your certificate will be accepted if it only contains the hostname (and you have the records signed)

As of 2.10.2 on an Android 8.0.0, this is not working for me.
- `${domain}.com` has DNSSEC enabled
- `_xmpp-client._tcp.${domain}.com` SRV record is considered secure by https://dnsviz.net/, and points at `jabber.${domain}.com`
- `jabber.${domain}.com` is a CNAME record pointing at an A record in the same domain, which is also considered secure by https://dnsviz.net/ (which follows the CNAME and also validates the A record)
- the certificate contains `jabber.${domain}.com` in its X509v3 Subject Alternative Name, signed by letsencrypt

Still, Conversations shows a "Domain not verifiable" error (approximate message, "Domaine non vérifiable" in my UI's French locale) error, without more details and without the dialog which used to exist and allowing the user to say whether they trust the received certificate.

I believe that the LAN it is running in has working DNSSEC (but I am not fully sure how I can check this, especially in a way which would be representative of what Android/Conversations is doing).

I believe my android OS truststore should be able to validate the certificate, but I am not sure how to check that (AFAIK Firefox comes with its own root CA bundle, I am not sure about Chrome, and I do not identify a way too launch the basic android browser).

I do not know whether bringing the old dialog asking the user whether they trust a given certificate is good (was it removed on purpose ?). But I believe it would be nice to have more details on what exactly is causing validation failure. Here are a few overlapping ideas:
- is DNSSEC (when enabled) failing for some reason, and for which record ?
- what is the last domain considered trusted by Conversations ?
- is Conversations failing to validate the SSL certificate trust chain ?
- is Conversations failing to locate the trusted domain in the SSL certificate ?

Maybe they could be displayed below the login form while logging in, with green-tick or red-cross indicating which failed. Maybe visible only in case of failure.

Alternatively, is there a way to replicate the checks Conversations is doing in order to have more detailed error reports ?

On a tangential topic, and more out of curiosity than anything else, what is the DNSSEC option controlling, exactly ? Is it enabling DNSSEC validation at all, or is it making DNSSEC validation mandatory ? If it is the former, wouldn't it make more sense to opportunistically validate DNSSEC, and if it fails to only consider user-input domain as trusted, but if it succeeds then the chain of records would be followed to the end or to the last DNSSEC success (whichever comes first) ? Then, the option could be to make DNSSEC validation mandatory, preventing even user-input domain from being trusted if its resolution cannot pass DNSSEC checks.
