### ISSUE TITLE
Option to set status

### ISSUE THREAD

**Issue by jkufner** [siacs/Conversations#451]
I prefer to be 'Away' rather than 'Online'. I also want to set custom status message. Conversations is currently always 'Online'.

It would be nice if there is a simple option to set status and message, just like it is in most other clients. This would also allow elegant way to solve #442, since one of the statuses would be offline.

I guess the top or bottom of conversations list would be a good place.

**Comment by crosser** [comment]
I'd like to extend this feature request:
I should be possible to set two separate statuses: one for when the screen is on and unlocked, and another for when the screen is off or locked.

**Comment by woj-tek** [comment]
There are two new options added (52a5e72b02e748780dc14b2a5f595df41f8c3f92) but there is one problem with it - generating abundance of presence changes even in case of simple checking notifications.

Could this option be extended/changed so that user would be way on mobile and only only when Conversations are are in the foreground?

**Comment by iNPUTmice** [comment]
I think the original issue was about *setting* the status. As this is implemented in 1.12.0 I believe this issue can be closed now.
