### ISSUE TITLE
Extended/Advanced Notifcation Settings

### ISSUE THREAD

**Issue by moshpirit** [siacs/Conversations#629]
Usually, if we get named in any client, this one highlight the message and notify us. Conversations should include that too.

Maybe the message can be shown with bold letters and change the notification options:

**→ Method 1**
Now:
- Conference notifications [✔]

Next releases:
- Conference notifications
   - Always
   - Only if someone names me
   - Never

**→ Method 2**
Or maybe you can notify it just like another private message (the best option in my view).

**Comment by Nekmo** [comment]
I really like this solution. :)

**Comment by moshpirit** [comment]
We're notified already when someone name us (the sentence it's not bold or italic or highlight in any other way, but it works), I don't know if this issue should be open anymore.

**Comment by Nekmo** [comment]
Sorry, I'm starting with Conversations. All messages from MUC are notified to me, even I'm not named. I don't know if there is a solution for this. The feature of this report resolve this issue.

**Comment by moshpirit** [comment]
Even if you silence/mute the MUC? Sorry, I don't know the exactly word used in English

**Comment by jkufner** [comment]
There should be checkbox in settings to disable MUC notifications.

**Comment by Natanji** [comment]
I have fixed this bug more than three months ago, see https://github.com/siacs/Conversations/pull/1023 -> it would be great if my pull request could be incorporated into Conversations somewhen soon.

**Comment by iNPUTmice** [comment]
Hi,


after talking to some people the notification behaviour in 1.6.x changed to always notify in private conferences.
Meaning in small conferences (group chats) for you and a couple of close friends you will always be notified while the behaviour for public conferences stays the same (notify when highlighted)

I feel like this is what most people were trying to achieve when asking for this settings.

Is there anyone still out there whose itch is not getting scratched by that?

If so please describe your use case a little bit closer. (Meaning who would you like to get notified and what type of conference we are talking about.)

**Comment by Natanji** [comment]
I will get back to you about this after the weekend and describe this in more detail, but I want to make sure that you know one use case beforehand that I actually have in a WhatsApp group (but since Conversations wants to be similar, it's just as good of a use case).

My sports club has a huuuuge WhatsApp group with all 60 or so people that are part of it. They regularily post a lot of stuff that doesn't interest me there, like training videos, funny gifs etc. - but they also announce e. g. changes to training dates there. Thus it would be important to me to never ever get notofied for the obnoxious funny gifs, but absolutely when someone writes about changes in the training dates (which always includes words like "Halle" or names of certain trainers or weekdays).

I'll get back to you for a different use case after the weekend, as I said, and I can also post screenshots of my proposed (and implemented) solution.

Am 27.08.2015 11:08 schrieb Daniel Gultsch <notifications@github.com>:

Hi,

after talking to some people the notification behaviour in 1.6.x changed to always notify in private conferences.
Meaning in small conferences (group chats) for you and a couple of close friends you will always be notified while the behaviour for public conferences stays the same (notify when highlighted)

I feel like this is what most people were trying to achieve when asking for this settings.

Is there anyone still out there whose itch is not getting scratched by that?

If so please describe your use case a little bit closer. (Meaning who would you like to get notified and what type of conference we are talking about.)

**Comment by moshpirit** [comment]
Maybe creating a new command "/all" or something like that could highlight the bubble to everyone.

**Comment by Natanji** [comment]
Creating new, obstruse commands that other people have to remember to use for specific other clients is *not* what you want. Notifications should be a choice of the receiver, not the sender.

Am 29.08.2015 01:22 schrieb moshpirit <notifications@github.com>:

Maybe creating a new command "/all" or something like that could highlight the bubble to everyone.

**Comment by Natanji** [comment]
So, as I said I wanted to get back to this issue, because right now I am more happy to use an own a bit outdated, patched version of Conversations than the up-to-date one; all of this just because this *one* feature is missing. I can't use Conversations properly without it.

This is because I have a MUC with some friends of mine (around 7-10 people in it at all times) in which I am usually not interested in reading every single message immediately, so getting mentioned for *every* message definitely is not okay. But when someone mentions certain topics or people, I want to be notified. Only mentioning my username is also not sufficient. A few reasons why:
- I have multiple names in that conference because I'm often in it with multiple devices and accounts at the same time. I want to be notified when any of these are mentioned, the others should not have to have to mention every single one of them to get me to answer.
- I also have a real-life nickname that people call me by, which is different from my birth name. So I want to be mentioned for this as well.
- Certain topics interest me and might require immediate action. Let's say I want to be mentioned whenever "Halo" is mentioned, because then the discussion will be about when we'll play Halo the next time, and a quick response from me would be useful.
- My relationship partner are also in this chat. When their name is mentioned, I want to be notified; for instance somebody might ask "Does anybody know if X is feeling okay again?" then I might be able to answer this, and thus it would be good for me to get a notification. And it should also be understandable that while I'm not usually interested in every single conversation, I will usually want to take part in conversations where my partner plays a role. ;)

I would love to hear your thoughts on this, and I really wonder if I'm the only person here who would find more notification options useful - some support from the others here would be nice. ;) Plus I still fail to see the *counterindication* to having this feature that I already implemented. It doesn't really cost you anything to have it, since I already wrote a patch (it would have to be slightly modfied for the newest version, but I'm willing to do that if you give me the green light). It's currently tucked away nicely below the other MUC options/participants list, so it doesn't get in the way of the average user that is fine with the default behaviour.

PS: I believe the 1.6.x changes are also quite a bit counterintuitive. IMHO notifications should not depend on the privacy status of a conference, those are two semantically very different things. It's about other people being able to join the conference or not, and muddling this with "when do you get notifications" seems outright weird to me. I think asking a user about their preferred notification behaviour upon creating or joining a conference would be much better UX design.

Also note, an important difference between WhatsApp and Jabber is that Jabber is widely used with Desktop clients with a real keyboard on which people can type much longer and faster. This can also happen in a private conference, and notifying people about every single message would get very annoying and force people to turn off notifications completely. Maybe I understood the changes wrongly, but if you can't set this to "notify when highlighted" anymore but this use case instead forces you to completely mute the MUC, something is broken with your design.

**Comment by moshpirit** [comment]
Not a developer but maybe you could add your patch as a plugin for now to let us know what's using your version of Conversations in order to let the real developers (like iNPUTmice) to see what do you really want and see how to deal with your petition.

It's just the suggestion of a normal user who has no idea about coding.

**Comment by Natanji** [comment]
To my knowledge, Conversations doesn't have plugin support, so I don't really get what you are asking? I have designed my solution after chatting about it with @iNPUTmice half a year ago, and my pull request had been open ever since https://github.com/siacs/Conversations/pull/1023. My version of Conversations is a tiny bit outdated by now (last updated it 2 months ago, based on v1.4.5 I believe), but works well nevertheless and can be found here for anyone to try out: https://github.com/natanji/Conversations/

Here are two screenshots that show the options I implemented, and how adding keywords works.

![notification options_0](https://cloud.githubusercontent.com/assets/887286/9628615/a9f5d81a-516c-11e5-9c2a-014015870a56.png)
![notification options_1](https://cloud.githubusercontent.com/assets/887286/9628614/a9f4b08e-516c-11e5-8719-bd26ffc3c868.png)

**Comment by moshpirit** [comment]
It does, in fact, you can use the ChatSecure's audio recorder plugin and 2 location plugins designed for Conversations, so AFAIK, it does (please, correct me if I'm wrong).

Your notification system looks great for me but maybe a little complicated for a basic user so I would change the menu for something simpler, like:

- Specific notifications [_] (if it's checked, then it let you to configure it, if not, it would use default notifications)
  - Notify every message
  - Never get notifications from this user

The keywords and username notifications could be implemented in a general view (for all the rooms or individual rooms, in this case, it could be changed "disable notifications" to "configure notifications"). I prefer the first option: general notifications about keywords and mentioned username for all the rooms.

**Comment by Natanji** [comment]
What would the use case be for never getting notifications from a specific user? The way I see it, this isn't Twitter where you need to mute specific people. ^^

**Comment by moshpirit** [comment]
Name it "disable" if you want, it's just a different name for the option.

**Comment by jotwewe** [comment]
I'd like to add my use case, which is not about conferences. I'd like to configure notifications depending on senders' JID and a keyword (like xabber implements it): my smart home sends messages via xmpp, some of which is just nice to know and should not make my smartphone make noise. In case there's an error or even alarm at home, it is supposed to notify me. So the sender of the message is the same, "notification or not" depends on keywords.

**Comment by Natanji** [comment]
I'm working on an implementation, but at the moment, this will only be for conferences. You can easily construct your use case by just making your smart home JID send the messages to a jabber MUC then, of course. I think it's a very rare case, and don't want to confuse users with this option for every single contact. That will get messy.

**Comment by iNPUTmice** [comment]
fixed in a3e136b5504641f9782b9d94e35311dad19fbc1d
