### ISSUE TITLE
Retry failed PGP decrypt

### ISSUE THREAD

**Issue by tbeitter** [siacs/Conversations#632]
If decrypt of a message failed it would be nice to be able to trigger a retry, just like you can resend messages in the long press menu.

**Comment by blitz** [comment]
I've also Seen spurious failures to decrypt openpgp messages.

**Comment by iNPUTmice** [comment]
I personally have stopped using PGP encryption a while ago. That means I can no longer eat my own dog food. And dogfooding generally is what makes Conversations such a great product. While I don't see an immediate reason to remove OpenPGP support from Conversations I think everyone would be better of if the PGP encryption part would be handled by someone who actually uses this on a daily basis.

So I'm calling out for someone to take over the responsibilities with OpenPGP. A first step would be to migrate to the new API version of openpgp-api. Later on you there are several open issues like:

#632
#711 (Decryption when in background) - Important one imho
#822
#957
#1013
#1299

If you are interested in that you would be given a lot of freedom in the architectural decisions.
Changing the way keys are discovered (JID lookup, instead of presence announcement) might also be an interesting step.
