### ISSUE TITLE
very high power consumption when unable to connect to account

### ISSUE THREAD

**Issue by jelmer** [siacs/Conversations#676]
Even when I just have it on in the background and don't chat, conversations takes up a lot of battery on my Nexus 5. It uses up 25% as far as the "Battery" window in Settings is concerned, which puts it on a shared first place with Screen.

**Comment by DefyMiners** [comment]
0.1.0 handles jid login better when network connection cycles.

Trepn showed approximately 0.42 mah for a day of conversations [no talking to people] 0.9.3, and nearly identical with foreground service.

Xabber dev was slightly higher for the day 0.68 mah [no talking to people]. 

ChatSecure test next weekend since its interface is similar to conversations [or visa versa].

**Comment by iNPUTmice** [comment]
Is this still a problem?

**Comment by jelmer** [comment]
No, this seems to be solved. Thanks!
