### ISSUE TITLE
Search by words and date in Conversation

### ISSUE THREAD

**Issue by ghost** [siacs/Conversations#703]
Hello,

It would be nice if you can search by words and go to a specific day in the history of a conversation.

Thank you.

**Comment by kolAflash** [comment]
Agree!
Especially in long conversations you won't be able to find anything without both features.
Have a look at Pidgin's great history feature.

**Comment by devurandom** [comment]
Jump-to-date is a nice thing, and even more useful than search-by-date.

I just worry that the UI might be overloaded by adding more and more options to the menus. Maybe adding a swipe-menu on the left would be in order. Like this one: ![Facebook for Android swipe-menu](http://i.stack.imgur.com/TjcZk.jpg)

**Comment by kolAflash** [comment]
A swipe-menu would be one great way to do it!

I know, this raises the complexity of the user interface. But if you want to use Conversations for some time, features like this become important. If Conversations doesn't provide those features, it's a nice xmpp-client for some weeks. But after some month of messages you might want to switch to a client with a feature like this.

Alternatively consider to put "professional" features like this one into an add-on für the normal conversation. Or put an option "activate professional features" into settings. So you can keep it simple for beginner-users.

By the way, exporting+importing history goes the same way:
https://github.com/siacs/Conversations/issues/501

**Comment by jkufner** [comment]
I do not like another big menu.

Current layout is fine, but action arrangement is ineffective. It would
help a lot if some actions were moved to another screens, like block
contact does not have be in chat menu, it can be in contact detail.

All avatars should have a long press menu with relevant options. This
will move some advanced features away from main menu too.

Instead of many contact-related actions in main menu a single item to
open contact details should be fine. Since all these actions would be
available in the contact detail screen.

This will mean one extra click in many cases, but it will improve
discoverability of features and application will be more intuitive.

**Comment by devurandom** [comment]
@jkufner +1

**Comment by weiss** [comment]
I think a message content search and an option to jump to specific dates are unrelated features.  Personally I'm interested in the former, so I created a separate issue (#1315) and [posted a Bounty][1] on that.  Others interested in this feature might want to contribute as well ...

[1]: https://www.bountysource.com/issues/25371199-feature-request-message-search

**Comment by iNPUTmice** [comment]
Closing as duplicte of #1315.
