### ISSUE TITLE
Decryption when app is in background

### ISSUE THREAD

**Issue by mase76** [siacs/Conversations#711]
Hi!
The (GPG) encrypted messages should be decrypted immediately, as long as the
private key is unlocked. When using the carbons feature, writing messages with
an other client, conversations is taking a long time to decrypt when returning, when
there is a large amount of messages. No decryption is being done when not in
foreground or the screen is locked.

**Comment by Bogdan-D** [comment]
I don't see it's necessary, or decrypt only if key is cached. Generally decrypt in background is security hole

**Comment by iNPUTmice** [comment]
I personally have stopped using PGP encryption a while ago. That means I can no longer eat my own dog food. And dogfooding generally is what makes Conversations such a great product. While I don't see an immediate reason to remove OpenPGP support from Conversations I think everyone would be better of if the PGP encryption part would be handled by someone who actually uses this on a daily basis.

So I'm calling out for someone to take over the responsibilities with OpenPGP. A first step would be to migrate to the new API version of openpgp-api. Later on you there are several open issues like:

#632
#711 (Decryption when in background) - Important one imho
#822
#957
#1013
#1299

If you are interested in that you would be given a lot of freedom in the architectural decisions.
Changing the way keys are discovered (JID lookup, instead of presence announcement) might also be an interesting step.

**Comment by iNPUTmice** [comment]
fixed in 1.7.3
