### ISSUE TITLE
Conversations does not comply with Googles default security standards

### ISSUE THREAD

**Issue by speendo** [siacs/Conversations#858]
I tried Conversations yesterday and I am very impressed! It works flawlessly with my jabber account.

However, at first I failed to connect to GTalk. After a while I got an automated mail from google, stating that there was an insecure app that wanted to connect to my account.

The mail had a link to this page: https://www.google.com/settings/security/lesssecureapps allowing me to use a "less secure authentication" technique. There was also this other link to a more informative page: https://support.google.com/accounts/answer/6010255

When I enabled "less secure authentication" Conversations could connect to my Google account.

I think it would be preferable if Conversation could use the "more secure authentication".

**Comment by plsng** [comment]
What exactly is the difference between less and more secure apps? 'The latest security standards' is rather vague.

**Comment by SamWhited** [comment]
This is somewhat misleading on Google's part. Conversations does support "the latest security standards", Google doesn't. What they really mean is that they want you to use "Google's security standards". Because Google does not support `SCRAM-SHA-1` authentication, and uses their own auth method instead (`X-GOOGLE-AUTH` or something like that, can't remember what they call it), Conversations is forced to fall back to a less secure alternative.

Bug Google about this, they have been resistant to change in the past, and I suspsect won't be performing any further upgrades now that they are moving towards using Hangouts exclusively and removing XMPP support. Note that Google's XMPP implementation is somewhat insecure in general, and because of this is not compatible with most other nodes in the network (they don't support ANY encryption for server to server connections).

**Comment by speendo** [comment]
I feel like I cannot say anything relevant to this topic that isn't already said.
I found this explanation about the difference between more and less secure apps (however, I don't know if it's true): http://security.stackexchange.com/a/72371

For some random user, it might be a dealbreaker if gtalk doesn't work out of the box. I don't know much about authentication protocols. But for me it also is a "bad feeling" to enable "less secure apps" in my GMail account (without knowing what that does exactly).

Conversations still is useful for me, as I have a Jabber account as well. Adding my GTalk account would however improve the usefulness.

**Comment by SamWhited** [comment]
Google Talk is considered an end-of-life product. That article is correct, Conversations has to fall back to the `PLAIN` mechanism (just sending your username and password) because Google doesn't support any reasonable authentication mechanisms (Oauth is nice, but not commonly used for XMPP).

Conversations could support it, but very few servers use it [citation needed], and supporting Google Talk would be a waste of time (IMO) since it's most likely going to be shut down in favor of Hangouts anyways (the transition is already in progress; I don't know what percentage of users have to upgrade before Google kills it entirely though).

**Comment by speendo** [comment]
<cite>
As long as you are connecting to Google over TLS (you are, Conversations doesn't support plain connections), you should be fine, even using the PLAIN auth mechanism.
</cite>

Just to make it clear: I am not worried about Conversations. I am worried, that one day I could download another app or program that would try to connect without any security mechanism. This would be an issue I would not notice if I enable "less secure apps" in GTalk.

**Comment by iNPUTmice** [comment]
The gtalk experience isn't gonna be a good one anyway. This is why Conversations doesn't advertise as being compatible with gtalk or facebook or whatever.
Conversations heavily relies upon modern XEPs that neither gtalk nor facebook support.
Gtalk and facebook users should really migrate to a proper XMPP server. (Facebook users will have to in April this year anyway.)

**Comment by jkufner** [comment]
Daniel Gultsch wrote, on 10.1.2015 18:54:
> Gtalk and facebook users should really migrate to a proper XMPP server.
> (Facebook users will have to in April this year anyway.)

Very nice sollution is to use private Jabber server with jabber2jabber
transport. Then you can use Facebook chat or GTalk and not worry about
security. As a bonus Facebook will see the same IP address all the time
so it protects your privacy.
