### ISSUE TITLE
conference name disappears from time to time

### ISSUE THREAD

**Issue by kriztan** [siacs/Conversations#859]
A conference created with official PlayStore version 0.10 loses its name from time to time. 
Steps to reproduce: create a conference with conversations, invite some contacts, rename the conference to anything else... wait... after some time the conference name is only a list of the users. After renaming this conference on my desktop via gajim, the name is persistent.

**Comment by iNPUTmice** [comment]
I think the problem arises due to the fact that conferences that are being created via the join conference dialog are not being marked as persistent.

since 18eb18794988ab94979020060e9bee9fe7fd9b67 rooms are being marked as persistent as soon as the user changes the subject or does any other kind of changes to the conference
