### ISSUE TITLE
Add support for last message correction (XEP-0308)

### ISSUE THREAD

**Issue by SamWhited** [siacs/Conversations#864]
[XEP-0308][xep0308] allows messages to be sent as corrections of the previous message.

I'd love to see Conversations at least have support for viewing messages which have been corrected. I was thinking that there could be some sort of small icon (next to the read receipt) to indicate when a message has been corrected, and an option in the long press context menu could allow you to toggle between the corrected text and the original text (or possibly just tapping the icon if it presents a big enough target).

As a second step, a long press context menu on the previous sent message could show an "edit message" option which, when selected, would paste the message back into the view, allowing you to edit it (Gajim also changes the color of the text entry box to give you a visual indication that you're editing an existing message).

Thoughts?

[xep0308]: http://xmpp.org/extensions/xep-0308.html

**Comment by iNPUTmice** [comment]
I'll have to think about that. Getting the UX right for that probably won't be easy. A simple toggle between corrected and and original wont do the trick because there might be several corrections.

On the technical side of things there are even more things to consider like MAM and the fact that for correcting messages we should probably do a disco request first to see if the recipient has support for that. And disco isn't something we are doing right now (because thus far it didn't really matter whether or not the recipient had support for for example message markers)

On a personal note: I'm not a fan of changing history...

This is not a 'NO' to this feature but since this would mean a lot of work this isn't something that can make it into 1.0

**Comment by SamWhited** [comment]
Good points all; I deifnitely don't like the idea of changing history, which is why an interface for viewing the original message (or messages, as you pointed out) would be important.

**Comment by devurandom** [comment]
I sometimes make typos, where a feature like Skype's support for `s/…/…/` is great to replace a single word with a correction without cluttering the chat with messages.

**Comment by SamWhited** [comment]
Started working on support for this in [this branch](https://github.com/SamWhited/Conversations/tree/xep0308). To start I was going to add a read-only interface (you couldn't correct messages yourself, but if something sent you a message with a correciton the UI would display it). I added message correction hints to the database, and now I've got to figure out how the UI would work, which turns out to be trickier than I'd imagined since the message you're correcting could be merged with other messages, and I don't like the idea of "un-merging" them (though maybe this is the best way).

If anyone has thoughts, I'm all ears.

**Comment by cultixate** [comment]
Is there a XEP that would allow the message sender to be notified the recipient client is archiving messages?  Assume each participant is using current/same Conversations version? 

I prefer both sides to not-log for OTR.

**Comment by neufeind** [comment]
Well, Slack (web-application) for example has a small grey icon next to the message to show it was edited at least once. You only get to see the last message there but are aware something changed since the original one. That icon is so greyed out that it doesn't distract, but is visible if you watch out for it.
Maybe that icon could also be a trigger to show a diff between the original and the last version then. Showing the original separate upon click? Or maybe just show in red the characters removed, in green the ones inserted? I'm thinking of some diff like gerrit or so displays it.

**Comment by SamWhited** [comment]
I was thinking something similar might be nice; an icon to show that it was edited (doesn't matter how many times, you only get the original message and the latest edit), and an item in the long-press context menu for the message which either swaps it to the original message, or swaps it to a diff between the two.

**Comment by TameOfGroans** [comment]
I would prefer the diff markup

**Comment by SamWhited** [comment]
I've started work on this a couple of times and then forgotten about it... I should really get back on it.

RE the UI: After thinking about it some more I don't think showing a diff makes much sense; it will just be an extra something to confuse users or make things difficult for users who are red/green color blind. Just a list of revisions would probably be the cleanest and easiest to use UI.

I'll at least update my branch for this in a bit so that it's based on the current code base; though I probably won't be able to finish the read-only version this weekend.

**Comment by TameOfGroans** [comment]
if not colorized diff then red lining -- without color instead retain only the strike through,  replacing red bold with merely bold.

**Comment by TameOfGroans** [comment]
^ with an icon to itemize changes as you indicated. [no edit option in my mobile fennec interweb client]

**Comment by Christian-X** [comment]
I'd like this feature as well. UI-Wise, i think it would be great to have an Icon on the Message ("Corrected") plus a new long-press message menu item - "Message Details"

This could show timestamps for sent, receeived, displayed chat markers for the various resources of the receiving user... (similiar to what whatsapp does)

**Comment by SafwatHalaby** [comment]
Doesn't this feature oppose Conversation's principle of simplicity? It looks like a redundant bloat to me.

**Comment by abbradar** [comment]
It would be nice to have, at least to be able to see other people' changed messages. Right now they are shown as just new ones, which can be confusing.

**Comment by knoy** [comment]
I agree, this could be a cool feature and I think @SamWhited 's suggestions for the UI sound pretty simplistic to me

**Comment by tbeitter** [comment]
Just ran into this today, I would appreciate it, too.
