### ISSUE TITLE
Conversations looses Connection

### ISSUE THREAD

**Issue by ChristianWendt** [siacs/Conversations#876]
A Issue i encounter quite often and which makes conversations very unreliable (almost useless) to me is conversation loosing the connection to the server and not issuing a reconnect while in the background:

* Phone/Conversations is idle for a prolonged time.
* At some point, server[own prosody instance] notices the connection is no longer available and hibernates the session
* Conversations won't notice that the connection is dead, no notification arrives
* In the moment you open Conversation (put it into foreground), Conversations notices its connection is dead and tries to reboot it - if i'm lucky its in my session hibernation timeout and everything is replayed, otherwise i might be lucky that the new message was offline stored.

I don't think its a phone/network issue:

Yesterday we decided to install a 2nd messenger on the same phone (xabber). Overnight my partners' conversations dropped connection - only xabber played a notification on the message this morning.

Catlog shows Conversations making a new connection in the instance it comes to foreground.

**Comment by Draghtnod** [comment]
I have the exact same problem with Conversations and i was thinking if i should file bugreport about this the last days. Thanks for doing it. :)

I see two main problems here:
1) The connection loss. Leave Conversations alone for a while or switch networks while the screen is off. Conversations just won't reconnect. (This even happens if the service is active in the expert menu! Tested for more than a week now!)
2) The message loss. If Conversations or the Phone just lost it's connection and the server thinks it is still online, messages won't get offline stored and are lost. The sender is forced to retry, which is highly annoying.

This together leaves a very unreliable feeling. I can't trust that my message is delivered when the buddy gets online. I can't trust that my buddy is online if he doesn't tap on the app every 10 minutes. It forces the user to fall back to other messaging apps/sms or call.

Right now: Buddy offline for 10 hours. Me tapping into Conversations and looking at my account: Connecting...

**Comment by iNPUTmice** [comment]
Do you have the ability to check with current HEAD? I believe this has been fixed.
(I need to do some more excessive tests myself)

**Comment by Draghtnod** [comment]
Nope sorry. I'm on 0.10. Is problem 2 fixed as well? How?

**Comment by mzsergiu** [comment]
Do you have a custom ROM on your phone or a custom kernel? I had this problem on a customer kernel I installed. With the default one (4.4.2) conversations is not dropped or put to sleep.

**Comment by Draghtnod** [comment]
Galaxy S4 standard ROM (4.4.2) with kernel 3.4.0 from November 27th. My friend has the same phone and the same problems.

**Comment by iNPUTmice** [comment]
If you like you can sign up to our [beta test program](https://github.com/siacs/Conversations/blob/development/README.md#beta)

**Comment by digititus** [comment]
Same issue. Conversations 1.0, ejabberd, Android 5.0.1 stock ROM's. Not problem with xabber on same connection.

**Comment by iNPUTmice** [comment]
> Same issue. Conversations 1.0, ejabberd, Android 5.0.1 stock ROM's. Not problem with xabber on same connection.

can we get a adb logcat output for that?

**Comment by digititus** [comment]
> can we get a adb logcat output for that?

Will try and get something for you

**Comment by cultixate** [comment]
>  install a 2nd messenger on the same phone (xabber). Overnight my partners' conversations dropped connection

assumes same JID used by both clients.

- Exit/kill both apps
- Start Conversations first
- Start Xabber Dev

Does conversations swiftly crash?

**Comment by ChristianWendt** [comment]
This Issue is fixed for me in the 1.0-beta - i haven't seen a single case of it since i use it :+1:
