### ISSUE TITLE
Allow specifying nick when creating/joining MUC

### ISSUE THREAD

**Issue by gaaf** [siacs/Conversations#914]
I would like an option to specify the nickname to be used in a MUC directly when joining the MUC.

I'm using the mod_irc module for ejabberd and there is a need to be able to specify the nick before a connection is attempted. The default nick (username part of the JID) is almost always already in use on the irc servers i use.

**Comment by iNPUTmice** [comment]
You can enter the full jid into the join conference like `someroom@server.tld/mynick`

TBH I didn't know that feature existed myself and I'm going to push something to make this a little bit more bullet proof but I think it's a nice solution because specifiying the nick before hand is probably only something that more advanced users will need and more advanced users won't be having a problem with entering the full jid.
