### ISSUE TITLE
Connection parameters

### ISSUE THREAD

**Issue by andreas-p** [siacs/Conversations#942]
Apparently, there are no connection parameters that can be modified. Specifically, I miss the option to set a server address that is different from the chat domain.

**Comment by SamWhited** [comment]
Please search (all issues, open and closed) before posting a new issue; this has been discussed many times.

**Comment by kriztan** [comment]
Please have a look into the readme: https://github.com/siacs/Conversations#where-can-i-set-up-a-custom-hostname--port

**Comment by andreas-p** [comment]
Unfortunately, I can't add SRV records for this domain. I need the manual setup option.

**Comment by somebody873425** [comment]
+1 some servers have more than one open port. i would like to be able to choose

**Comment by andreas-p** [comment]
Since this issue comes up again and again, there's obviously a need for manual settings. 

I DID search for open issues concerning this request before opening a new one, and the next wannabe-user of Conversations will probably do as well because all other non-proprietary xmpp clients offer manual settings and will find its absence a deficiency. 

While it's certainly desirable to have all parameters auto-configured via SRV records, real life is different. Please consider the manual options.

**Comment by jkufner** [comment]
Yes, it comes up quite often, but there are some significatn downsides
of such feature.

Jabber is federated service. It means that servers need to be connected
together to provide full service. If some server is misconfigured, it
degradates user experience of all users, not only of those on the
misconfigured server.

There are no problems like this with e-mail and it works on the same
principle, only using MX records instead of SRV.

Actually there are only few usecases which require manual configuration.
First is useless provider, second is private and closed server. Both of
these can be easily overcome with VPN, and in both cases VPN will solve
few other problems user will have anyway.

By not supporting manual configuration, Conversations make overall user
experience better, and forces users to solve real problems.

**Comment by iNPUTmice** [comment]
> and forces users to solve real problems.

very much this.

The only scenario I can imagine where it is impossible to setup SRV records is dyndns (DON'T RUN YOUR XMPP SERVER ON DYNDNS).

Port 443 firewall constrains can easily be overcome by simply announcing that port over SRV as well. (You can have many SRV records.)

A server admin who is incapable of doing this probably shouldn't be a server admin.

**Comment by plsng** [comment]
Besides, if you still want manual configuration, you can always use any of the other clients that support it, or fork Conversations and add the configuration yourself.

**Comment by andreas-p** [comment]
There can be many reasons why an administrator is not able to modify DNS, besides from "being incapable". 
I want to solve a distinct problem with XMPP in a private environment. Actually, I CAN add SRV records for the target environment, but not in the test environment. So I can't test Conversations, which rules it out for later deployment.
Suggesting to fork appears counterproductive for a project that needs to get traction.

**Comment by jkufner** [comment]
@andreas-p: You do not need SRV record if the JID domain is the same as
A record of the server. You can also use custom DNS server with modified
records to make test environment more real.

**Comment by jkufner** [comment]
@plsng: Fork or modification is not an option. It costs too much time.

**Comment by andreas-p** [comment]
Custom DNS server, forking code.... all not too viable.
Seems Conversations should be named YANUXC (Yet Another Non-Universal XMPP Client)
