### ISSUE TITLE
PGP does not work with OpenPGP card

### ISSUE THREAD

**Issue by crosser** [siacs/Conversations#957]
Conversations 0.8.2
OpenKeychain 3.1.2
Using Yubikey NEO (no private keys on the android device).

When in a conversation I tap the padlock icon and select OpenPGP, I am prompted for the OpenPGP PIN, and then presented with "Hold YubiKey against the back of your device" screen. When I touch yubikey to the back of the phone, the "Hold YubiKey" screen disappears for a moment and then appears again. This repeats indefinitely until I tap the "back" button, at which time encryption type is back to what it was before selecting OpenPGP.

My OpenKeychain + YubiKey work fine with K-9 Mail.

**Comment by Anders-Linden** [comment]
Conversations 1.2.0
OpenKeychain 3.1.2 (31200)
Status: Not working

When I chose OpenPGP encryption in the message I will be displayed Passphrase question I input  pin code. Then I have to select OpenPGP encryption again, and then the "Hold YubiKey against the back of your device" comes up, put my Yubikey there and it disappears as it should.

The conversation is back to plain text :/

OpenKeychain + Yubikey NEO (U2F) (fresh by generation via gpg --key-edit)

**Comment by MathieuVachon** [comment]
Same Loop behavior with Conversations : 1.4.4-beta2 (Source Build)

OpenKeyChain : 3.2.3 (Source Build)

Receiving encrypted message and trying to decrypt in Conversations simply does not work with YubiKey

**Comment by caelor** [comment]
I see the same behaviour @crosser observes when trying to publish my public key via Conversations, and behaviour @Anders-Linden reports when trying to switch to OpenPGP encryption.

Conversations 1.4.3 (F-Droid)
OpenKeyChain 3.2.3  (F-Droid)

I am unable to decrypt received PGP messages.

**Comment by iNPUTmice** [comment]
I personally have stopped using PGP encryption a while ago. That means I can no longer eat my own dog food. And dogfooding generally is what makes Conversations such a great product. While I don't see an immediate reason to remove OpenPGP support from Conversations I think everyone would be better of if the PGP encryption part would be handled by someone who actually uses this on a daily basis.

So I'm calling out for someone to take over the responsibilities with OpenPGP. A first step would be to migrate to the new API version of openpgp-api. Later on you there are several open issues like:

#632
#711 (Decryption when in background) - Important one imho
#822
#957
#1013
#1299

If you are interested in that you would be given a lot of freedom in the architectural decisions.
Changing the way keys are discovered (JID lookup, instead of presence announcement) might also be an interesting step.

**Comment by SamWhited** [comment]
In my case when publishing a key I am never prompted for a PIN. Instead, I select a key and immediately enter the loop (select a key again, key selection pops up, select a key again, key selection pops up...)

As far as I can tell from a quick glance this evening, `OpenPgpApi.RESULT_CODE_USER_INTERACTION_REQUIRED` is being returned (as you'd expect), but the result intent (found via `(PendingIntent) result.getParcelableExtra(OpenPgpApi.RESULT_INTENT)`) doesn't actually do anything — it just returns `RESULT_OK` and the original `SIGN` intent in `onActivityResult` (which starts the process over assuming that it actually has the data it nees now)

This makes me think that OpenKeychain is returning the wrong event and that it's a bug with YubiKey support on their end, though I didn't see anything after a quick glance through the issue tracker (@dschuermann might have more info?). We may also just be doing something wrong to trigger this, but I didn't see what off the top of my head. There's next to no chance the `SIGN` event should be returning `RESULT_OK`, however (there's no signature, and there never could be since we were never prompted to tap the NFC device and enter our PIN to unlock the signing key).

**Comment by iNPUTmice** [comment]
OpenKeychain has changed the way the API works. Wild speculation based on what @SamWhited said. The YubiKey API doesn't fall back to the old Account-based API.

(In older versions you would always send and Account String in the form of 'User <user@domain.tld>' to the API. On first access it would find or create a key for you. This has now changed. On first access you will get your own key id, store that and communicate that id to the api in subsequent requests.)

In any case it is probably a good idea to migrate to the new API.

**Comment by SamWhited** [comment]
Ah, interesting; that's easy enough. Their README still details the old API.

**Comment by crosser** [comment]
In conversations 1.6.7 behaviour changed - when I touch the lock icon, it now asks for the pin, tells me to touch Yubikey (as a sidenote, Yubikey is not the only NFC OpenPGP card in the market!), then asks me to take away Yubikey, and the lock icon is still unlocked and the entry area says "Send unencrypted message". So, still does not work, but slightly differently. Openkeychain version is 3.5.1.

**Comment by dschuermann** [comment]
@crosser They changes you mention are solely on OpenKeychain's side. For naming discussions please look into https://github.com/open-keychain/open-keychain/issues/1471

**Comment by iNPUTmice** [comment]
is this fixed in 1.7.3? I don't have a yubikey so I can't test this myself.

**Comment by Anders-Linden** [comment]
I have a Yubikey with PGP so I can test this during this weekend.

**Comment by jfjallid** [comment]
@iNPUTmice 
I have conversations 1.14.4
OpenKeychain 4.1 
and a yubikey neo with only subkeys.

When I select OpenPGP for encryption I'm first prompted for a pin to access the security token of my key. Then a loop begins:

I'm prompted to hold the yubikey to the back of my phone and then to hold it there once it is close enough just for a moment after which it says that I should remove the security token. Upon removal it loops back to prompting me to hold the yubikey to the back of the phone. When pressing abort it says that the conversation is unencrypted.

**Comment by crosser** [comment]
Just an update, with conversations 1.19.0 and openkeychain 4.4.1 behaviour is the same as described by @jfjallid in the previous comment.

**Comment by iNPUTmice** [comment]
Please check if 8696cf2235a7b57f4434f4b2408ba9a658dd080f fixes your issue.

**Comment by wiktor-k** [comment]
I did tests with Conversations 1.23.0 and OpenKeychain 4.8.1 with OpenPGP card (Yubikey 4) and decryption indeed **does work now**. Previously I've also experienced decrypt-loops. Currently sending simple `jabber:x:encrypted` messages from Desktop works, Conversation decrypts them, shows lock icon, etc..

FWIW adding OpenPGP key to account looked like a decrypt-loop (constantly asking to unlock the card via OpenKeychain) but I could cancel and decryption of messages worked (sounds like a minor glitch).

**Comment by crosser** [comment]
Confirm fixed in 1.23.1
