### ISSUE TITLE
UX: Signup screen

### ISSUE THREAD

**Issue by allo-** [siacs/Conversations#968]
Some feedback i got from a non-technical user:
"What should i enter in the user@domain field when creating an account?"

What about a domain chooser with some well-known public servers, like beem or some other clients have it during signup? And a label on the username field "choose your name", when the signup checkmark is set.

**Comment by jkufner** [comment]
> What about a domain chooser with some well-known public servers, like
> beem or some other clients have it during signup?

It is already implemented. Just type '@' and it should appear.

Maybe link to some tutorial could help.

**Comment by iNPUTmice** [comment]
@jkufner That doesn't work on initial account creation. That only works with known domains that appear in the roster.

@allo- The problem is as soon as Conversations starts to make suggestions this will essentially break federation. But agree with you that on the long run Conversations will be better of with providing that information. However this is a delicate matter that should be handled with a lot of consideration.

**Comment by allo-** [comment]
hmm, here it seems only to suggest three domains from people in my contact list (current playstore version). But it should be visible before somebody starts typing, as it seems that non-technical users stop before even trying, if its not obvious.

A short setup-wizard would be cool. "choose your server" "choose your name" "your name is (not) free" "you're ready to use Conversations"

**Comment by plsng** [comment]
Maybe you could parse the [Public XMPP Server Directory](https://xmpp.net/directory.php) available on xmpp.net somehow and make Conversations suggest servers based on the latest rankings? Of course those rankings only take into account the security used, so whether or not they support any useful XEPs would still be up in the air.

**Comment by allo-** [comment]
I guess there should be some manual review.
The list has two important factors:
  - age (possible indicator, if the service may last for some while or not)
  - technical security

But it does not cover trust, usage policies and other stuff. I guess recommending a server should include some manual review. And this list has servers with manual (web-based) registration in there, which is another problem.

**Comment by jkufner** [comment]
In addition to security, also reliability must be considered. Therefore
at least Stream Management must work unconditionally.

Extending this server directory with automated tests, which asks for
supported xeps could be useful.

**Comment by allo-** [comment]
Another thing, which profits from a "known server" list:

  - you can set "enforce TLS" for servers known to provide TLS
  - maybe even certificate pinning would be useful.

**Comment by jkufner** [comment]
Converstaions always requires TLS.

**Comment by the-solipsist** [comment]
I agree that this should be approached carefully. But it should definitely be implemented, since with Conversations we finally have a client that *first time XMPP users* can also use with ease.  But they can't do that unless they a) have an account; b) have friends also using XMPP.

I would suggest asking "Do you have an existing chat (XMPP) account?", and if no:
Saying, "Let's create one so that you can chat with you friends. Please enter your desired"
Username:
Password: [Maybe with a password meter]
Chat Server (choose any one): [List of 12 popular services]

**Comment by allo-** [comment]
For password meters: account for the "more lengh is better than special characters". 

People use ``$3cur3`` as password assuming it's better than ``IreallyloveXMPPforchatting``, while the second one would be more secure in most cases.

**Comment by iNPUTmice** [comment]
Conversations has a new welcome screen now (actually since version 1.12 or something but I forgot to close here)
