### ISSUE TITLE
A campaign 

### ISSUE THREAD

**Issue by moshpirit** [siacs/Conversations#971]
You have said several times to include some features if you get paid for this. What about making a campaign as [MediaGoblin did](http://mediagoblin.org/pages/campaign.html)?  
Something like:
- 100 € → New themes, wallpaper and date marks in conversations
- 150€ → Legacy file transfer too for a better communication with other apps
- 200€ → Proxy and Captcha options
- 300€ → User location support
- 500€ → MUC file transfers
- 750€ → iOS and Windows Phone apps
- 1000€ → Conversations get free in every store

**This is just an example**
And please, excuse my English.

**Comment by jkufner** [comment]
Some time ago I've seen feature-oriented fund raiser. Like Kickstarter,
but people vote with money for designated features (and the feature gets
implemented once its goal is reached), which is very different and much
better approach than Kickstarter's stretch goals (at least for software
development).

**Comment by jkufner** [comment]
Finally I found it: https://www.bountysource.com/

**Comment by iNPUTmice** [comment]
Well the option of hiring me to implement new features already exists (and is being used) however this is of course something only companies can afford who resell Conversations or use it otherwise.

To pledge to specific features as an individual I would - as @jkufner pointed out - suggest to use something like bounty source because for me it is much easier than setting up a real campaign like MediaGoblin did. If bountysource gets enough traction and has been successfully used for 2-3 issues/features I would consider offering a real campaign with stretch goals and stuff like that.

I would also like to point out that I'm in no way trying to blackmail individual users of Conversations to pay me money or a feature will never get implemented I'm just trying to get the word out that I'm available for hire which will give customers timely delivery of their required features.

And last but not least a word to:
> 1000€ → Conversations get free in every store

The 2-3 bucks (depending on your country) at the Play Store is not something I'm planning on making money of. I just believe that people should pay for quality software. The everything must be free mentality will otherwise ruin the entire industry. 3 bucks is less than an ice cream cone or a hot dog in Manhattan and people buy that everyday without even thinking twice about that. Why should a piece of software you use everyday be free only because it is somewhat immaterial?
Plus Conversations already is free. It's free software. What you pay for is the convince of getting automatic updates and not having to rely on shady third party sources. And paying for convince is a widely used business model. Paying for something you could also get for free with a little more afford. Think gym memberships. 

I know those points were only examples but I wanted to take the chance to comment on my reasoning on why Conversations is for sale in the play store.

**Comment by andersruneson** [comment]
You'd probably get 100-1000 times more installs if Conversations were free
in play store which in turn would get you more attention from companies
that would like to hire you for company-branded versions of Conversations.

The reason I found conversations was due to somebody on the xabber mailing
list mentioned Conversations, and the reason that I was on the xabber
mailing list was due to it was the best android xmpp client I found but it
wasn't actively developed anymore (so I was on the list to wait for it to
wake up again).

My point is that Conversations is listed very low in the play store search
results (when searching for xmpp) and it would get higher if it was for
free.

/Anders

**Comment by plsng** [comment]
I think @andersruneson has a point, if Conversations were free in the Play Store more people would download it, more people would know about it and more people would find out there's a way to donate to and/or hire you. If someone wants to pay for the app, they will, regardless of whether it's donationware or paid up front. If they don't want to, they aren't going to get it from the Play Store anyway.

Not to mention, if someone's already paid for the app, I think chances are low they will send some more money your way through a donation; the thought of donating wouldn't even cross my mind if I had already bought it.

Also, last time I checked the Play Store required a credit card (or PayPal account) to buy things, which is not something everyone has.

**Comment by simontretter** [comment]
Paying for conversations might not get people to download it, but those who do are more likely to use it. And active users are far more important to the growth of this kind of software than mere downloads. I am running my own small server for family and friends. Those who really want to use it will pay for a good xmpp client. Those who also value the fact that you don't need any google stuff go the donation / f-droid route.

**Comment by moshpirit** [comment]
>To pledge to specific features as an individual I would - as @jkufner pointed out - suggest to use something like bounty source because for me it is much easier than setting up a real campaign like MediaGoblin did. If bountysource gets enough traction and has been successfully used for 2-3 issues/features I would consider offering a real campaign with stretch goals and stuff like that.

Do you know if is it possible to use BountySource without Google Wallet? because I'm here defending free software and a free Internet, so I'm not going to give Google access to my money as I'm not doing it with PayPal.

>I would also like to point out that I'm in no way trying to blackmail individual users of Conversations to pay me money or a feature will never get implemented I'm just trying to get the word out that I'm available for hire which will give customers timely delivery of their required features.

Yes, don't worry, we want to collaborate because you earned it with this awesome project. 

>And last but not least a word to:
    >1000€ → Conversations get free in every store

It was just an example, I didn't know your view on this aspect. But not everybody trust Google this much. Maybe a "free Conversation" option would be right but this is offtopic.

Thanks and good luck with this :) let us know if you decide to use one of these ways to get more donations.

BTW, I tried to add you via Conversations to tell you that I don't have a PayPal account nor Bitcoins and asking you if does exist another way, but a friend's just told me she has a PP account, so I'll donate my part this weekend.

**Comment by TameOfGroans** [comment]
Conversions as branding brings the protocol much closer to the "xmpp texting" notion to edge out "sms texting"

While I refrain from hate as a habit I do justly hate adware which by construction is malware. That said I cannot advocate the not-free adware evil-business practice. However, is there room for

Lite Conversations 
&
Conversations

Perhaps the former would not support multiple accounts, and have nearly zero configuration options [selectable].

/end thought project

**Comment by iNPUTmice** [comment]
Ok I'm closing this because this is getting off topic. If someone wants to sponsor or donate to an issue you can use existing platforms like bountysource or just contact me and tell me you are willing to give x bucks if I implement a feature.

**Comment by moshpirit** [comment]
@iNPUTmice sorry for comment this here, (does exist any kind of XMPP room or something to ask these things?) but it's any way to make Conversations compatible with the ChatSecure plugins? that way, we could create our own plugins and colaborate even more with the both projects (well, I can't because I'm not a developer, but helping two projects at the same time must be a huge motivation).  
Once again, thank you very much for your work.

**Comment by andersruneson** [comment]
https://github.com/siacs/Conversations#conversations-doesnt-work-for-me-where-can-i-get-help
"You can join our conference room on conversations@conference.siacs.eu ."

**Comment by moshpirit** [comment]
Thanks, @andersruneson, sorry for disturbing you
