### ISSUE TITLE
Support for XEP-0153

### ISSUE THREAD

**Issue by zxiu** [siacs/Conversations#983]
I have read the issue #69 and understand the reason for XEP-0084.
Pity until now some server haven't support 0084 yet - as our ejabberd server.
I would like to implement this feature and a first test was successful.
What not sure is if @iNPUTmice would like to merge this feature in to the project (so i will write clean code with same coding style) or would simply implement a direct but dirty code just for our own demand ?
Btw, i am a newbie in Git please forgive my poor english as well :smile:

**Comment by sezuan** [comment]
Why don't you just enable PEP in ejabberd? There are some issues in the older versions (2.1.x) but with version 14.xx it works pretty well.

**Comment by SamWhited** [comment]
XEP-0153 is a historical XEP which should not be implemented. I've just made a motion to the XSF to obsolete it officially. It's on the new business for the next council meeting.

**Comment by iNPUTmice** [comment]
as @sezuan and @SamWhited pointed out you should avoid implementing this. Upgrading your ejabberd server to 14.12 is a good idea anyway. However if for some reason you go ahead and implement this anyway I might consider merging a read-only support for that. If done carefully enough this wouldn't lead to  any unnecessary bandwidth consumption (because clients announce the hash of the image in the presence) and would give some users some more pretty pictures for the roster.

**Comment by zxiu** [comment]
@sezuan we dont know very much about ejabberd and erlang...so could you please tell me is that module you mean called mod_pubsub? For i can't find 0084 on ejabberd page..
> This module offers a Publish-Subscribe Service (XEP-0060). The functionality in mod_pubsub can be extended using plugins. The plugin that implements PEP (Personal Eventing via Pubsub) (XEP-0163) is enabled in the default ejabberd configuration file, and it requires mod_caps.

**Comment by sezuan** [comment]
@zxlu

**Comment by iNPUTmice** [comment]
r/o support for vcard avatars has been implemented in 5136bf9832b9a7aeb59926b42fe6a6632452c1ef
